wappalyzer/wappalyzer

- src/drivers/webextension/images/icons/Simple Analytics.svg
- src/technologies/s.json
https://simpleanalytics.com
https://nomadlist.com/
https://remoteok.com/
https://betalist.com/
https://missiveapp.com/
https://spencertweedy.com/
https://leavemealone.app/
https://fontsarena.com/
https://enspirit.be/
https://blog.adriaan.io/
and many more: https://github.com/search?l=HTML&q=scripts.simpleanalyticscdn.com&type=Code
> Add Simple Analytics / Analytics

- src/technologies/g.json
https://www.godaddy.com/
http://outrightgeekery.com/
http://acolyer.org/
> Add GoDaddy / hosting

- src/technologies/s.json
https://www.siteground.com
https://www.modeles-de-cv.com/
https://blog.sqlauthority.com/
http://www.818today.com/
https://www.abante.com.ph/
> Update SiteGround / hosting

- src/drivers/webextension/images/icons/Hostpoint.svg
- src/technologies/h.json
https://www.hostpoint.ch/
https://support.hostpoint.ch/de/produkte/domain/haeufig-gestellte-fragen/wie-lauten-die-nameserver-von-hostpoint
https://www.meister-uhren.ch/
https://www.wildbaerheule.ch/
https://www.landschaftsinitiative.ch/
> Add Hostpoint / hosting

- src/drivers/webextension/images/icons/Infomaniak.svg
- src/technologies/i.json
https://www.infomaniak.com/fr
https://www.infomaniak.com/fr/support/faq/2026/nom-de-domaine-fonctionnement-dns-zone-dns-a-record-mx-record
http://caritasge.ch/
https://www.grand-chene.ch/fr/
https://www.astuces-brico.fr/
> Add Infomaniak / hosting

- src/drivers/webextension/images/icons/One.com.svg
- src/technologies/o.json
https://www.one.com/en/
https://help.one.com/hc/en-us/articles/360000841638
https://stap.dk/
https://bd-byg.dk/
http://wadmanns.dk/
> Add One.com / hosting

- src/technologies/a.json
https://shop.coop.co.uk/
https://www.shopmoment.com/
https://placeit.net/
> Update Algolia / search engines #4413

- src/technologies/l.json
https://github.com/aFarkas/lazysizes
https://www.microsoft.com/en-gb/
https://www.rt.com/
https://www.box.com/
https://www.urbandictionary.com/
http://roaring.earth/
https://www.ceneo.pl/
> Add LazySizes / JS lib #4787

- src/drivers/webextension/images/icons/Uploadcare.svg
- src/technologies/u.json
https://uploadcare.com/pricing/
https://www.doktortakvimi.com/
https://bandsintown.com/
https://daedaluswallet.io/
https://www.ubiq.fr/
https://riabiz.com/
https://www.cuadrosdeluxe.es/es/
https://www.damart.co.uk/
> Add Uploadcare / IaaS #4443

- src/technologies/a.json
https://developer.apple.com/documentation/businesschat
https://www.ms.gov
https://www.metro-cc.ru
https://www.ksk-koeln.de
https://www.pbz.hr/
https://citylink.pro/
https://midco.com/
https://alwayshodl.com/
https://utensili.store/
https://www.dashikipride.com/
https://muscledoctor.co.uk/products/surge-performance-hydration-fuel
> Add Apple Business Char / Live Chat #5237

- src/technologies/o.json
http://aiontech.com.tw/owa/auth/logon.aspx?url=http://aiontech.com.tw/owa/&reason=0
https://readyspace-he.com/owa/auth/logon.aspx?url=https://readyspace-he.com/owa/&reason=0
https://mail.smc.com.sa/owa/auth/logon.aspx?url=https%3a%2f%2fmail.smc.com.sa%2fowa%2f&reason=0
https://www.hmail.sg/owa/auth/logon.aspx?url=https%3a%2f%2fwww.hmail.sg%2fowa%2f&reason=0
https://mail.euchost.com/owa/auth/logon.aspx?url=https%3a%2f%2fmail.euchost.com%2fowa%2f&reason=0
https://owa.tgm.ac.at/owa/auth/logon.aspx?url=https%3a%2f%2fowa.tgm.ac.at%2fowa%2f&reason=0
https://webmail.exchangecorp.com.br/owa/auth/logon.aspx?url=https%3a%2f%2fwebmail.exchangecorp.com.br%2fowa%2f&reason=0
https://216.176.178.100/owa/auth/logon.aspx?url=https%3a%2f%2f216.176.178.100%2fowa%2f&reason=0
> Update Outlook Web App / Webmail #5329

- src/technologies/c.json
> Update Choices / Miscellaneous #5338

- src/technologies/x.json
https://kb.x-cart.com/
https://www.flair.ie/
https://www.coolblades.co.uk/
https://tstindustries.com/
https://www.thewinnersjournal.com/cart.php?target=cart
http://www.miniatures-workshop.com/
https://urbanclotheslines.com/
https://www.cueandcase.com/
http://midnightcd.net/
> Update X-Cart / ecommerce #5336

- src/drivers/npm/driver.js
- src/technologies/c.json
https://cloudinary.com/pricing
https://www.so-net.ne.jp/
https://reverb.com/
https://www.fiu.edu/
https://www.bergdorfgoodman.com/
https://my.xcelenergy.com/
https://surewerx.com/s/
https://www.coeliac.org.au/s/
> Update Cloudinary / DAM, CDN

- src/technologies/a.json
https://ant.design/
https://identitys.co.nz/
https://tron.network/
https://relocatte.com/
https://scrf.ae/
https://en.x-mol.com/
> Update Ant Design / UI frameworks #5349

- src/technologies/h.json
https://digitalserver.ir/
https://karenbaby.ir/
https://filinco.ir/
https://yellowshopp.com/
> Add HighStore / ecommerce

- src/drivers/webextension/images/icons/U-KOMI.svg
- src/technologies/u.json
https://u-komi.com/en/
https://u-komi.com/
https://kawaya.com/
https://www.tsunorice.com/
> Add U-KOMI / Reviews

- src/technologies/e.json
https://envothemes.com/free-envo-shop/
https://abovegroundpoolbuilder.com/
https://www.nakispiko.com/
https://www.calzaturificiocaltavuturese.it/
https://tiendacostarica.cr/
http://diaelektrik.com/
> Add Envo Shop / WP theme

- src/technologies/t.json
https://themezee.com/themes/wellington/
http://www.steves-internet-guide.com/
https://cracksversion.com/
http://livejupiter2.net/
> Add ThemeZee Wellington / WP themes

- src/technologies/t.json
https://www.themehorse.com/themes/attitude
http://www.devforum.jp/
https://vedaradio.fm/
http://www.agirsursoi.com/
http://www.alfredplacechurch.org.uk/
http://www.protosolution.com/
https://russelltours.com/
> Add Theme Horse Attitude / WP themes

- src/technologies/e.json
https://envothemes.com/free-envo-ecommerce/
https://www.academicapparel.com/
https://www.autodesguacelegazpi.com/
https://www.innova-deals.com/
http://www.ciftlikshop.com/
https://www.marketnewsrelease.com/
https://wirelesstigre.com/
> Add Envo eCommerce / WP themes

- src/technologies/t.json
https://themeansar.com/free-themes/newsberg/
http://www.guidograndt.de/
https://boobsrealm.com/
https://shareinfo.pl/
https://www.worldofwrestling.it/
https://www.footballweeks.com/
> Add Themeansar Newsberg / WP themes

- src/technologies/a.json
https://athemes.com/theme/hiero/
http://besta.live/
https://cheapvaping.deals/
http://meandr.org/
https://viralbob.com/
> Add aThemes Hiero / WP themes

- src/technologies/a.json
Added the changes suggested in #5385
> improved afterpay detection

- src/technologies/d.json
Django is a open source software
Ref = https://github.com/django/django
> Improve Django

- src/technologies/w.json
Wagtail implies "Python",
Also Wagtail is open source software.
Ref = https://github.com/wagtail/wagtail
> Improve wagtail

- src/technologies/o.json
https://global.direct.asda.com
> Update Olapic / Content curation #5364

- src/technologies/g.json
https://support.google.com/merchants/answer/7105655?hl=en
https://www.jetpens.com/
https://www.qualitylogoproducts.com/
https://www.sevmak.com.tr/
https://www.hookedonline.com.au/
https://www.firstclasswatches.co.uk/
> Add Google Customer Reviews / Reviews #4347

- src/technologies/f.json
https://github.com/staaky/fresco
https://mackie.com/
https://www.japantimes.co.jp/
https://panda.com.sa/
http://www.ritsumei.ac.jp/
http://superstari.co.kr/
https://alnilebank.com/
> Add Fresco / JS lib #4318

- src/drivers/webextension/images/icons/Muuri.svg
- src/technologies/m.json
https://muuri.dev/
https://runnet.jp/
https://www.gran-turismo.com/us/
https://buymobile.com.au/
https://www.additive-net.de/de/software/uebersicht
> Add Muuri / JS lib

- src/technologies/m.json
https://mybb.com/
https://raidforums.com/
https://hackforums.net/
https://v3rmillion.net/
https://ogusers.com/
https://bestblackhatforum.com/
https://python-forum.io/
> Update MyBB / Message boards

- src/technologies/g.json
Proof : 
- https://github.com/go-macaron/macaron
> Grafana-Patch

- src/technologies/g.json
> Gitea Patch

- src/technologies/c.json
https://developers.cloudflare.com/logs/reference/log-fields/zone/nel_reports
https://togel.pages.dev/
https://firehunt.pages.dev/
https://twitch.pages.dev/
https://fluenticons.pages.dev/
> Add Cloudflare Network Error Logging / issue tracker

- src/technologies/a.json
**Changes:**
- Add ActiveCampaign Site Tracking native integration script source URL (*.app-us1.com)
- Add ActiveCampaign Pages scripts source URL (*.ac-page.com)
- Add URL pattern for ActiveCampaign Platform (<account>.activehosted.com)
- Add URL pattern for ActiveCampaign Pages (<account>.ac-page.com)
- Add pricing info ([Price on asking available contacting Sales team](https://www.activecampaign.com/pricing?em=999999&term=yearly&features=1))
> Improve ActiveCampaign detection

- src/drivers/webextension/images/icons/Rotic.svg
- src/technologies/r.json
https://rotic.ir/fa-ir
https://rotic.ir/fa-ir
https://pegah.ir/
https://miladzandi.ir/
> Add Rotic / Live chat

- src/technologies/a.json
http://adriver.ru
https://lifehacker.ru/
https://hotline.ua/
https://www.rbc.ru/
https://www.mvideo.ru/
https://iz.ru/
https://www.kino-teatr.ru/
https://www.playground.ru/
https://rg.ru/
> Update AdRiver / Advertising

- src/technologies/a.json
http://adverticum.net
https://index.hu/
https://888.hu/
https://www.jofogas.hu/
https://www.startlap.hu/
https://videa.hu/
https://www.borsonline.hu/
> Update Adverticum / advertising

- src/technologies/a.json
https://apostrophecms.com/
https://ilumy.com/
https://www.michelin.fr/
https://bayanat.cgii.co/
http://mykg.id/
> Update ApostropheCMS / CMS

- src/technologies/a.json
https://developer.apple.com/sign-in-with-apple/
https://bandsintown.com/
https://www.therealreal.com/
https://www.sinemalar.com/
https://roosterteeth.com/
https://www.spacecloud.kr/
> Update Apple Sign-in / authentification

- src/technologies/a.json
https://www.appointy.com/
https://www.dictionary.com/
https://www.marshallstreetdiscgolf.com/
https://www.westkinassociates.com/
https://www.unishost.com/
https://www.ubikes.com/
> Update Appointy / Appointment scheduling

- src/technologies/a.json
https://arastta.org/
https://shop.davvi.no/
https://mail.discgolfparker.no/
https://hageredskaper.no/
http://handmadeboutique.ro/
> Update Arastta / ecommerce

- src/technologies/a.json
http://aurelia.io/
https://www.erd.hu/
http://bluespire.com/
https://www.franklintempleton.com.cn/
https://desygner.com/
https://www.danaheru.com
https://sigillum.pl/
http://tenderwizard.com/
https://www.bariloche2000.com/
https://mobilijeune.actionlogement.fr/
> Update Aurelia / JS framework

- src/technologies/b.json
https://tongji.baidu.com/
http://www.weather.com.cn/
> Update Baidu Analytics / analytics

- src/technologies/s.json
https://sellix.io/
https://motiontokens.com/
> Update Sellix / ecommerce  #5528

- src/technologies/b.json
https://www.banshee-php.org/
https://www.banshee-php.org/
> Update Banshee / CMS

- src/technologies/b.json
https://getbento.com/plans/
https://www.myccasa.com/
https://www.silvermoonbakery.com/
https://www.mayataqueria.com/
https://www.lottiespub.com/
https://www.theempanadamaker.com/
https://www.buffalobrostexas.com/
https://www.urbancantina.com/
> Update Bentobox / CMS, reservation&delivery

- src/technologies/c.json
fix category, remove implies add requires
> Update CareCart products / Shopify apps, cart abondonment

- src/technologies/a.json
- src/technologies/l.json
update categories, add requires
https://www.arcxp.com/
https://www.infobae.com/america/
https://www.lanacion.com.ar/
https://www.leparisien.fr/
https://tw.appledaily.com/home/
https://www.reuters.com/
> Update Lootly,Loox Update Arc publishing -> Arc XP

- src/technologies/a.json
- src/technologies/l.json
https://shop.rubynz.com/estore/style/rs21661-bh.aspx
https://www.bambinoandmore.co.uk/designer-boys/aurea-grey-and-white-fairsle-jumper
> Update LayBuy, AfterPay / BNPL

- src/technologies/r.json
https://remix.run/
https://kentcdodds.com/
> Update Remix / Web server, Js framework

- src/technologies/r.json
https://www.google.com/recaptcha/about/
https://www.globo.com/
https://www.gianteagle.com/
https://www.rottentomatoes.com/
http://samsungcsportal.com/
https://www.springer.com/
https://www.callofwar.com/index.php
> Update reCAPTCHA / security #4447

- src/drivers/webextension/images/icons/Rokt.svg
- src/technologies/r.json
https://www.rokt.com/
https://1-day.co.nz/
https://www.yesglasses.com/
https://www.surfstitch.com/
https://www.ediversitynetwork.com
> Add Rokt / personalistion

- src/technologies/s.json
request #5584
Website: https://www.wired.com/story/general-paul-nakasone-cyber-command-nsa/
> Update SoundCloud / widget #5584

- src/technologies/b.json
- src/technologies/v.json
http://videojs.com
https://news.walla.co.il/item/3483489
Brightcove, VideoJS
https://www.vmware.com/ru.html
> Update VideoJS, Brightcove #5558

- src/technologies/a.json
- src/technologies/b.json
https://putyourlightson.com/plugins/blitz
https://plugins.craftcms.com/blitz
https://github.com/putyourlightson/craft-blitz
https://imagecomics.com/
https://www.transparency.org/en/
https://thebreakthrough.org/
https://www.impraise.com/
> Update Blitz / performance

- src/drivers/webextension/images/icons/Lit.svg
- src/technologies/l.json
https://lit.dev
https://merkur.dk/privat/
https://www.1lottoland.com/
https://procureship.com/
> Add lit-element,lit-html / js lib

- src/technologies/l.json
> Update lit / js lib #5600

- src/drivers/webextension/images/icons/YouCan.svg
- src/technologies/y.json
https://youcan.shop/en/prices
https://dealzat.com/
https://azarshop.net/
https://maroc.youcan.shop/
https://fouad.youcan.shop/
https://smartshopdz.com/
> Add YouCan / ecommerce

- src/technologies/b.json
Update tech name: 
pros:
1. clear stats with false positive results
2. actual product name
> Update Bloomreach Discovery / search engine, personalisation

- src/technologies/a.json
- src/technologies/b.json
- src/technologies/c.json
- src/technologies/e.json
- src/technologies/g.json
- src/technologies/h.json
- src/technologies/j.json
- src/technologies/l.json
- src/technologies/m.json
- src/technologies/n.json
- src/technologies/o.json
- src/technologies/p.json
- src/technologies/r.json
- src/technologies/s.json
- src/technologies/t.json
- src/technologies/w.json
- src/technologies/z.json
Deleted everywhere where it is not necessary, web sites lead to github mainly.
> fix pricing for oss tech

- src/technologies/g.json
- src/technologies/n.json
https://github.com/gnuboard
https://shopping365.co.kr/
http://kweng.kr/
http://ckipm.com/
https://sir.kr/
https://amina.co.kr/
> Add Gnuboard / cms , improve Naver / analytics

- src/technologies/a.json
https://astro.build/
https://astro.build/
> Update Astro / page builder #5635

- src/technologies/m.json
https://microsoft.github.io/monaco-editor/
https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements
https://godbolt.org/
https://www.typescriptlang.org/play
https://firepad.io/
> Add Monaco Editor / Rich text editor #5636

- src/technologies/c.json
https://www.cubecart.com/
http://microfresas.com.br/index.php?act=viewProd&productId=100
https://www.cubecart.com/
https://csmfgusa.com/Shop/
https://www.gamesitetemplates.com/index.php
https://shoprainbowartglass.com/
https://troutflies.com.au/index.php
> Update CubeCart / ecommerce

- src/technologies/c.json
https://www.covermanager.com/
https://cristinaoria.com/
https://gasparrestaurant.com/
https://lamonteria.es/
> Update CoverManager / reservations-delivery

- src/technologies/c.json
http://contao.org
http://filmages.ch/
https://aquacomputer.de/
https://kirche-bewegt.ch/
https://charcounter.com/ru/
https://www.kd-maerkte.de/
https://english.lingolia.com/en/
> Update Contao / cms

- src/technologies/c.json
http://www.cs-cart.com
https://whipplesuperchargers.com/
https://www.snoekwonen.nl/
https://www.cortland.pl/
https://mac24h.vn/
https://chiemtaimobile.vn/
https://www.homeschooldiploma.com/
> Update CS Cart / ecommerce

- src/technologies/c.json
https://www.carbonads.net/
http://www.eclipsecolorthemes.org/
http://browserhacks.com/
https://getbootstrap.com/
https://tinypng.com/
> Update Carbon Ads / advertising

- src/technologies/c.json
https://cargo.site/
https://mosaic.org/
https://adriennevanderwerf.com/
https://patrikas.pro/
https://pablogenoux.com/
https://ohezin.kr/
https://forthcoming.studio/
> Update Cargo / page builder

- src/technologies/c.json
https://chamilo.org/en/
https://learn.infiniteheap.com/
https://sikola.unhas.ac.id/
https://www.campusiesrfa.com/
https://tehuacan.cursosugmex.com/
> Update Chamilo LMS

- src/technologies/c.json
https://clarity.design/
https://app.codingrooms.com/
https://marketplace.cloud.vmware.com/
https://uniamerica.br/
https://my.uni-bayreuth.de/cmlife/welcome/sub-organizations
https://www.constanta.dariusmotors.ro/
https://www.dcvw.ro/
> Update Clarity / UI frameworks

- src/technologies/c.json
https://coinhive.com
https://futurdrone.com/gb/
https://armeriavarona.com/
> Update CoinHive Captcha

- src/technologies/s.json
https://www.sap.com/products/commerce-cloud.html
https://www.e-bebek.com/
https://www.teknosa.com/
https://www.hansgrohe.co.uk/
> Update SAP Commerce Cloud / ecommerce

- src/technologies/a.json
https://azure.microsoft.com/en-us/pricing/details/monitor/
https://www.centraalbeheer.nl/
https://www.salzburg-ag.at/
https://www.friso.com.hk/
https://www.friso.co.id/
https://egopowerplus.com.au/
https://www.thriftbooks.com/
https://www.providence.org/
> Add Azure Monitor / Analytics, Performance

- src/technologies/p.json
https://www.pendo.io/pricing/
Add analytics category
Fix available false positive results
> Update Pendo / analytics, user onboarding

- src/drivers/webextension/images/icons/demandbase.svg
- src/technologies/d.json
Demandbase is one of the largest enterprise B2B personalization and analytics companies in the market.
> Add Demandbase

- bin/convert.js
- package.json
- yarn.lock
Mostly this was frustrating me with the setMaxListener output. I believe this is mostly under the hood with the conversion package, so I adjusted and masked where I could. Ultimately, it's a much cleaner output.
- Attempt to increase listeners
- Remove excessive warning output
- Add better CLI output
> Update SVG / PNG conversion script

- src/technologies/s.json
https://www.tobi.com/product/77966-tobi-sweetness-swiss-dot-cotton-stripe-midi-dress?color_id=110872
> Update Sezzle / BNPL #5685

- src/drivers/webextension/images/icons/Cloudimage.svg
- src/technologies/c.json
https://www.cloudimage.io/en/pricing
https://www.gilmar.es/
https://www.heise.de/
https://www.apotheken-umschau.de/
https://www.banquepopulaire.fr/
https://www.tme.eu/gb/
> Add Cloudimage / CDN, DAM #5689

- src/technologies/d.json
http://www.atex.com/products/dm-polopoly (Redirects to the new CMS Atex Ace. But it doesn't seem to be popular yet. As long as I leave it) 
https://www.irishtimes.com/
https://www.larena.it/
> Update DM Polopoly / CMS

- src/technologies/d.json
Replace html -> dom, add desc, oss
> Update Dart / PL

- src/technologies/d.json
https://disqus.com/pricing/
https://otakustream.tv/
> Update Disqus / comment system

- src/technologies/d.json
https://www.dokuwiki.org/
https://doc.ubuntu-fr.org/
https://faq.o2switch.fr/
https://winscp.net/eng/docs/lang:ru
> Update DokuWiki / Wiki

- src/technologies/d.json
https://duopana.com/
https://academiamedica.com.br/
https://sabersistemico.com.br/
https://interacaofitness.com.br/
https://comunidadedoestagio.com/
https://mulheresquedecidem.com.br/
> Update Duopana / cms, blogs , page_builder

- src/drivers/webextension/images/icons/Vuetify.svg
- src/technologies/v.json
https://vuetifyjs.com
https://www.stitcher.com/
https://www.bnext.com.tw/
> Update Vuetify / UI framework  #5706

- src/drivers/webextension/images/icons/UptimeRobot.svg
- src/technologies/u.json
https://uptimerobot.com/pricing/
https://www.wappalyzer.com/
https://stats.uptimerobot.com/ywB8Zhq40
https://www.stream4free.live/
> Add UptimeRobot / issue tracker

- src/technologies/h.json
https://www.hcltechsw.com/commerce
https://www.dillards.com/?facet=dil_shipinternational:Y
https://www.dillards.com/webapp/wcs/stores/servlet/LogonForm?storeId=301&langId=-1&catalogId=301
https://www.costco.ca/
https://www.boots.com/
> Update HCL Commerce / ecommerce #5733

- src/technologies/o.json
https://www.oracle.com/cx/
https://www.burberry.com/
https://www.barnesandnoble.com/
https://www.wind.gr/
https://www.whitehouseblackmarket.com
https://www.chicos.com/
https://www.soma.com/
> Update Oracle Commerce,Cloud / ecommerce #5735

- src/technologies/e.json
https://www.enable.co.il/
https://www.checkid.co.il/
https://mynames.co.il/
https://www.upress.co.il/
> Update Enable / accessibility #5750

- src/technologies/b.json
https://bambuser.com
https://kyliecosmetics.com/en-us
> Update Bambuser / miscellaneous #5772

- src/drivers/webextension/images/icons/Chatwoot.svg
- src/technologies/c.json
https://www.chatwoot.com/pricing/
https://binary.ninja/
https://paydro.com/
https://halom.me/he/
https://myownconference.ru/
https://cambackup.com/
> Add Chatwoot / live-chat #5776

- src/technologies/l.json
https://github.com/google/libphonenumber
https://www.coop.ch/
https://bullandcleaver.com/
https://groupme.com/
https://www.specialized.com
https://www.getinbank.pl/
https://madisoncollege.edu/
https://www.partylite.com/
> Add libphonenumber / js lib #5839

- src/technologies/c.json
https://github.com/brix/crypto-js
https://vov.vn/
https://frontier.com/
https://www.bancolombia.com
https://puhutv.com/
http://miaopai.com/
> Add crypto-js / js lib #5838

- src/technologies/o.json
> Update Optimizely / a-b-testing #5867

- src/drivers/webextension/images/icons/Qwik.svg
- src/technologies/q.json
https://github.com/builderio/qwik
https://www.builder.io/
> Add Qwik / web framework #5844

- src/technologies/p.json
https://wicg.github.io/priority-hints/
https://www.weddingwire.com/biz/in-tuscany-wedding-tuscany/c21b317f550243c4.html
> Add Priority Hints / performance #5903

- src/technologies/a.json
- src/technologies/c.json
- src/technologies/f.json
- src/technologies/h.json
- src/technologies/l.json
- src/technologies/o.json
- src/technologies/r.json
- src/technologies/s.json
https://github.com/AliasIO/wappalyzer/issues/5912
> Improve categorisation

- src/drivers/webextension/images/icons/Vitals.svg
- src/technologies/v.json
https://vitals.co/#pricing
https://juorge.com/
https://shopkey.doyustudio.com/
https://www.gearrangers.com/
> Add Vitals / Shopify app, marketing automation #5902

- src/technologies/k.json
https://kibocommerce.com/press-events/kibo-certona-cloud-commerce-personalization/
https://www.amway.com/
https://www.bodybuilding.com/en-KZ/index
https://www.windsorstore.com/products/reusable-gel-lift-pasties-071010272999?variant=17617768841267&rrec=true
> Update Kibo Personalization / personalisation #5962

- src/technologies/w.json
https://www.prnewswire.com/news-releases/wunderkind-acquires-smarterhq-to-supercharge-growth-for-enterprise-ecommerce-301174291.html
https://www.harborfreight.com/
https://www.bornshoes.com/
https://www.saveacup.com/
https://www.shoeline.com/
> Update Wunderkind / marketing-automation #5948

- src/technologies/t.json
Examples:
https://mav.farm
https://spline.design
https://m2icondb.com
https://github.com/home
https://bruno-simon.com
https://richardmattka.com
https://web.blockbench.net
> Updated Three.js Detection

- src/technologies/s.json
https://www.splunk.com/en_us/observability/real-user-monitoring.html
https://www.visitestonia.com/en/
https://www.home4you.ee/
https://plumbr.io/
> Add Splunk RUM / rum #6003

- src/categories.json
> Update category groups

- src/technologies/c.json
See: https://github.com/zaproxy/zap-extensions/pull/3697
> Fix comscore pattern

- src/technologies/a.json
https://aws.amazon.com/ru/s3/
https://www.ieee.org/
https://emojipedia.org/apple/
> Update Amazon S3 / miscellaneous #6009

- src/technologies/g.json
https://shop.shiseido.com.my/products/power-infusing-concentrate
> Update Grab Pay Later / bnpl #5891

- src/technologies/a.json
https://www.chicos.com/store/product/Travelers-Classic-Twist-Back-Dress/570325500?color=2664
https://rothys.com/products/the-virtual-gift-card
> Update ApplePay / payment proc #5850

- src/technologies/g.json
https://acoustic.com/tealeaf
https://gonutrition.com/
https://yunomi.life/
https://gearbunch.com/
https://bymilaner.com/collections/clutches/products/the-meg-woven-clutch?variant=39488094175290
> Add GTranslate app / shopify-app, translation #5793

- src/categories.json
- src/technologies/m.json
Fix group, add dom for modiface
> Fix group, add dom for modiface

- src/technologies/s.json
> Update Salla / ecommerce

- src/technologies/a.json
just pickup version also check #5883 rquest
> Update Afterpay / payment proc,bnpl #5883

- src/technologies/g.json
> Update Grafana / analytics #4567

- src/technologies/o.json
https://mohinhtrungbay.vn/
https://canlaco.com.vn/
https://bestmevn.tk/
> Update OnShop / ecommerce

- src/technologies/a.json
https://polinations.com/
https://franquiacna.com.br/
https://momently.com/
https://www.datkanikzelf.nl/
> Update Astro / ssg, js framework

- src/technologies/r.json
> Update RxJS / js lib

- src/technologies/o.json
> Update Olark / live-chat #6032

- src/technologies/l.json
https://www.loopreturns.com
https://www.vitalydesign.com/
https://amourvert.com/
https://excisionmerch.com/
https://dudeperfect.store/
https://thewodlife.com/
> Update Loop Returns / returns #6039

- src/technologies/m.json
fixed here
https://material-kit-react.devias.io/
https://www.jofogas.hu/
normal here
https://www.shutterstock.com/ru/
https://www.sigmaaldrich.com/
https://ants.gouv.fr/
> Update MUI / ui-frameworks

- src/technologies/c.json
> Update Cloudflare / cdn

- src/technologies/l.json
https://wordpress.org/plugins/litespeed-cache/
https://benifershop.com/
> Update Litespeed Cache / WP plugin

- src/technologies/l.json
https://apoorv.pro/lozad.js/
https://www.pchome.com.tw/
https://www.grid.id/
https://altema.jp/
https://www.jawapos.com/
https://toyokeizai.net/
https://www.ivoox.com/
https://www.gridoto.com/
> Add Lozad / javascript lib, performance #5807

- src/technologies/s.json
> Update Sanity / CMS

- src/technologies/h.json
- src/technologies/j.json
- src/technologies/o.json
- src/technologies/s.json
- src/technologies/t.json
https://github.com/wappalyzer/wappalyzer/issues/5912
> More updates to categorisation

- src/technologies/b.json
https://www.theorietoppers.nl/
> Update BigCommerce / headless ecom

- src/technologies/m.json
> Update Magento / ecommerce

- src/technologies/g.json
https://apps.shopify.com/globo-color-swatches
https://www.fabulegsmelissa.com/
https://rivieratowel.com/
https://vapor95.com/
> Add Globo Color Swatch / shopify-app #5815

- src/technologies/f.json
https://getfirepush.com/
https://apps.shopify.com/firepush
https://www.puravidabracelets.com/
https://www.masteringthemix.com/
https://wearenations.com/
> Update Firepush / marketing-automation, shopify-app #5819

- src/technologies/h.json
https://www.hyperspeed.me
https://apps.shopify.com/hyperspeed?locale=cs
https://cg-mobile.com/
https://goldiluxehair.com/
https://tabatashop.com/
https://www.greeneroom.ie/collections/color-wow/products/color-wow-dream-filter-250mls
> Update Hyperspeed / performance, shopify-app #6154, #6153

- src/technologies/a.json
> Update Algolia / search-engine #6145

- src/technologies/r.json
https://www.reevoo.com/pricing
https://www.currys.co.uk/products/tcl-32rs520k-roku-32-smart-hd-ready-led-tv-10226910.html
> Update Reevoo / reviews #6087

- src/technologies/m.json
https://www.maxmind.com
https://www.bluejeans.com/
http://epson.com/
https://www.jeep.com/
https://www.lkbennett.com/
> Update MaxMind / geolocation, browser-fingerprinting #6031

- src/technologies/a.json
> Update Amazon S3 / miscellaneous #6009 #6015

- src/technologies/b.json
https://thebase.in/
https://524seisaku.official.ec/
https://www.mothers-shop.jp/
> Update Base / ecommerce #6180

- src/technologies/a.json
https://www.automizely.com/marketing/pricing
https://www.xmpow.com/
https://nardellidesign.com/
https://www.rosegoldandblack.com/
https://sixthreezero.returnscenter.com/
https://maatluxe.returnscenter.com/
https://oldgringoboots.returnscenter.com/
> Update Automizely / marketing automation

- src/technologies/b.json
https://www.automizely.com/marketing/pricing
https://panamericana.pe/
https://myip.cx/
https://scipy.org/
https://onejav.com/
https://hoff.ru/iwaf-captcha
no traces
https://japanpub.de/shop/product/7/
> Update Bulma / UI framework

- src/technologies/s.json
http://prohost.wf/
http://www.nannyexpress.pl/login
https://www.postlab.fr/ ?
> Update Symfony / web-frameworks

- src/technologies/m.json
https://mui.com/
https://pomfretcard.com/
> Update MUI / ui-framworks

- src/technologies/t.json
https://www.thg.com/
https://www.wappalyzer.com/technologies/ecommerce/the-hut-group?utm_source=popup&utm_medium=extension&utm_campaign=wappalyzer
> Update The Hut Group / Miscellaneous

- src/technologies/r.json
https://rechargepayments.com/
https://checkout.rechargeapps.com/r/purchase/thanks/25963e393ad4498182ed67f2d5b94944/?shop_url=olipop-store.myshopify.com
> Update Recharge / payment-processors

- src/technologies/v.json
https://demov2.subsapp.com/#/login
https://my.subsapp.com/#/login
https://columbia.ru/
> Update Vue.js / js framework

- src/technologies/s.json
https://spongebed.me
https://www.spotify.com
https://www.sky.com
> Update Svelte / js frameworks

- src/technologies/h.json
https://app.evervault.com/login
https://www.iscorp.com/
https://uwaterloo.ca/
https://www.bestchange.ru/
https://www.dish.com/
> Update hCaptcha / security

- src/technologies/a.json
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-RUM.html
https://github.com/aws-observability/aws-rum-web
https://github.com/aws-observability/aws-rum-web/blob/main/docs/npm_installation.md
https://github.com/aws-observability/aws-rum-web/blob/main/docs/cdn_installation.md
https://www.cbssports.com/
https://www.woot.com/
https://www.aleks.com/
https://www.hagebau.de/
https://www.enistation.com/
> Add Amazon CloudWatch RUM / rum

- src/technologies/g.json
> Remove Google Remarketing Tag / retargeting

- src/drivers/webextension/images/icons/Kaltura.svg
- src/technologies/k.json
https://corp.kaltura.com/pricing/
https://www.su.se/
http://go.com/
https://www.teacherspayteachers.com/
https://www.bollywoodlife.com/
https://www.learnaveda.net/login/index.php
https://www.cricketcountry.com/
https://www.tricocipro.com/login/index.php
https://www.rfa.org/english/
> Add Kaltura / video-player, livestreaming

- src/drivers/webextension/images/icons/JouwWeb.svg
- src/technologies/j.json
https://www.jouwweb.nl/prijzen
https://www.fleurive.nl/
https://www.mediterra-tegels.nl/
https://www.emmassweetdelights.co.uk/
https://www.stones-lifestyle.nl/
https://www.dushibidajewelry.com/
> Add JouwWeb / page builders

- src/technologies/z.json
https://farmacialoreto.it/
https://almitrans.eu/
https://thienvu.com.vn/
https://globalmalls.com.vn/
> Update Zozo / ecommerce

- src/technologies/t.json
https://tri.be/our-work/the-events-calendar/
https://theeventscalendar.com/
https://ru.wordpress.org/plugins/events-calendar/
https://www.metasolutions.net/
https://www.georgetown.edu/
https://www.bcit.ca/
https://pfctraining.com/training-schedule/
> Update The Events Calendar / wp-plugin

- src/technologies/r.json
https://slicing-brandshoe-gary.vercel.app/
> Update React / js framework

- src/technologies/a.json
**website**
https://docs.microsoft.com/en-us/azure/frontdoor/
**examples**
https://www.ipcoop.com
https://www.raa.com.au
https://www.globalpayments.de
> Added Azure Front Door

- src/drivers/webextension/images/icons/Letro.svg
- src/technologies/l.json
https://service.aainc.co.jp/product/letro/
https://www.stellarhollywood.com/
https://basefood.co.jp/
https://www.nissen.co.jp/
https://brightage.jp/
https://www.weleda.jp/
https://claircos.co.jp/
> Add Letro / reviews, content-curation

- src/technologies/p.json
http://prebid.org
https://www.kiwilimon.com/
https://www.phillymag.com/
https://www.thegamer.com/
https://wsvn.com/
> Update Prebid / advertising

- src/technologies/p.json
https://www.paypal.com/uk/webapps/mpp/paypal-virtual-credit
https://www.desigual.com/en_GB/22WWVDX15160.html
https://www.gak.co.uk/en/tascam-tm-70-dynamic-podcasting-microphone/942851
https://www.nationalbusinessfurniture.com/
https://www.eurocarparts.com/swimming-pools
https://www.halloweencostumes.com/dorothy-costume-long-dress.html
https://www.joules.com/Women/Clothing/Atherstone/Waterproof-Trench-Coat?size=10&id=214489|MARNAVY|10
https://www.babymonitorsdirect.co.uk/product/callowesse-apprise-baby-breathing-monitor-twin-pad-set/
> Add PayPal Credit / bnpl #4500

- src/technologies/g.json
https://www.gatsbyjs.com/products/cloud/image-cdn/
https://www.anthonyboyd.graphics/
https://www.albiernats.com/
replace html to dom
> Add Gatsby Cloud Image CDN / cdn #5890

- src/technologies/p.json
https://popper.js.org/
https://parcoursup.fr/
http://abc.gob.ar/
https://www.fasthosts.co.uk/
https://www.systemrequirementslab.com/
> Update Popper / miscellaneous #5946

- src/technologies/h.json
https://apps.shopify.com/ultimate-sales-boost
https://hextom.com/case_study/ultimate-sales-boost
https://www.sainsmart.com/
https://chinahobbyline.com/
https://paul-hewitt.jp/
https://www.tupperware.com/
https://www.sofamania.com/
https://www.theimmart.com/
https://www.naipocare.com/
> Add Hextom Ultimate Sales Boost / shopify-app #5969

- src/drivers/webextension/images/icons/MageWorx.svg
- src/technologies/m.json
https://www.mageworx.com/magento2-extensions.html
https://www.aarong.com/
https://www.inova.com.mx/
https://www.havan.com.br/
https://www.lampadaribesanza.com/it/search/sd
> Add MageWorx Search Autocomplete / search-engine

- src/technologies/g.json
> Update Google AdSense / advertising

- src/technologies/m.json
> Update Microsoft ASP.NET / Web frameworks

- src/technologies/m.json
https://github.com/AzureAD/microsoft-authentication-library-for-js
https://totaloffice.com.au/
https://www.stacywitbeck.com/
https://redlist-webapp-qa.azurewebsites.net/login
https://edelvivesdigital.com/
https://pbx.io/portal/
https://cuk.pl/
> Add Microsoft Authentication / authentication, javascript-libraries

- src/technologies/c.json
https://www.syncfusion.com/javascript-ui-controls
just add additional parameters
> Update Crisp / live-chat

- src/technologies/p.json
- src/technologies/y.json
Fix Plyr desc add css attr , YouTube add scriptSrc attr
https://finofilipino.org/page/2/
https://mihaaru.com/
https://www.mehilainen.fi/
https://www.trelleborg.se/
https://finofilipino.org/page/2/
https://www.aflac.com/
> Update Plyr, YouTube / video-players

- src/technologies/a.json
- src/technologies/l.json
https://design-smart-spaces.com/
> Update Linkedin Insight Tag, Adroll

- src/technologies/b.json
http://bulma.io
https://ndcacctsolutions.com/
> Update Bulma / ui-frameworks

- src/technologies/m.json
https://to-do-app-3d745.web.app/
> Update Mui / ui-framework

- src/technologies/m.json
https://github.com/onokumus/metismenu
https://my.superior.edu.pk/
https://retail.sahaj.co.in/
https://www.swoole.com/
https://www.nekopost.net/
https://fresh-cards.ru/
https://www.itdks.com/
https://lottolyzer.com/
> Add metisMenu / js lib

- src/drivers/webextension/images/icons/Tebex.svg
- src/technologies/t.json
https://www.tebex.io/
https://store.hypixel.net/
https://store.nopixel.net/
https://store.rustacademy.net/
> Add Tebex / ecommerce

- src/technologies/w.json
https://doc.webzi.ir/
https://webzi.ir/pricing
https://petstore.ir/
Returns fall-positive results
"generator": "^Webzi"
> Update WebZi / page builder, cms #6419

- src/technologies/r.json
https://cosbots.imonitor.live/register
https://hh.ru/
https://www.linkedin.com/feed/
> Update React / js framworks

- src/technologies/m.json
https://www.mailerlite.com/features/website-builder
https://www.jcfoundationtrust.org.uk/
https://www.micloudbiz.com/
> Add MailerLite Website Builder / page-builders

- src/technologies/w.json
https://wp-rocket.me/pricing
https://www.auricularestop.net/
> Update WP Rocket / wp-plugin

- src/drivers/webextension/images/icons/Webzie.svg
- src/technologies/w.json
website
https://www.webzie.com/
examples
https://www.dogs-cats.co.il/
https://www.chabad-judaica.com/
https://www.smilephone.co.il/
https://www.toys-express.co.il/
https://www.pashutrihut.co.il/
https://www.first-sport.co.il/
https://www.avinary-pro.com/
https://www.holylandlegacy.co.il/
https://www.deal-shop.co.il/
https://www.decoclick.co.il/
https://www.thebigmall.co.il/
https://www.anak-rihut.co.il/
https://www.pilotshop.co.il/
https://www.footballworld.co.il/
https://www.pumps4u.co.il/
https://www.emanueel.co.il/
https://www.at-work.co.il/
https://www.shakedsport.co.il/
https://www.zerimyafim.co.il/
https://www.yashir-la.co.il/
PS: this is webzie.com, not WebZi.ir
> add webzie / page builder

- src/drivers/webextension/images/icons/Mailman.svg
- src/technologies/m.json
http://list.org/
https://github.com/terencehonles/mailman
https://lists.sharedweight.net/postorius/lists/
https://lists.swinog.ch/postorius/lists/
https://lists.luv.asn.au/mailman3/postorius/lists/
https://lists.wikimedia.org/postorius/lists/
https://lists.fedoraproject.org/archives/
https://lists.opensuse.org/archives/
> Add Mailman / email

- src/technologies/a.json
https://docs.aws.amazon.com/waf/latest/developerguide/waf-captcha.html
https://seesaawiki.jp/
> Add AWS WAF Captcha / security #6021

- src/technologies/a.json
https://www.onthemap.com/accessibly/
https://www.wappalyzer.com/technologies/personalisation/accessibly/
https://fabdog.com/
https://www.fuegobox.com/
https://tonymoly.us/
https://strangerco.com/
https://fivepawns.com/
https://www.backjoy.com/
> Update Accessibly / accessibility #6034

- src/drivers/webextension/images/icons/Nacelle.svg
- src/technologies/n.json
https://nacelle.com/
https://iliabeauty.com/collections/face
https://blendjet.com/
https://byltbasics.com/products/womens-essential-cropped-crew
> Update Nacelle / ecommerce #6049

- src/technologies/a.json
> improve aws waf captcha

- src/drivers/webextension/images/icons/CodeSandbox.svg
- src/technologies/c.json
website:
- https://codesandbox.io/docs/embedding
examples:
- https://www.framer.com/docs/examples/
- https://swr.vercel.app/examples/basic
- https://react-query.tanstack.com/examples/basic
> Add CodeSandbox Detection

- src/technologies/l.json
- src/technologies/p.json
- src/technologies/s.json
https://www.jcponline.com.au/shop/asus-expertbook-14-fhd-400nits-intel-i5-1135g7-16gb-512gb-ssd-win10-pro-fingerprint-backlit-military-grade-3yr-wty-w10p/
> Update Paypal,LatitudePay,Laybuy,Splitit / bnpl, payment_proc #6071

- src/technologies/n.json
> Add Next.js version check

- src/drivers/webextension/images/icons/GoKwik.svg
- src/technologies/g.json
https://www.gokwik.co/
https://www.fablestreet.com/
https://evolvesnacks.com/
> Add GoKwik / miscellaneous #6095

- src/technologies/f.json
Added two additional js entries
> Updated Flutter

- src/technologies/d.json
Update description
Remove outdated dom detection
Remove outdated exclude
Added more JS detections
Removed outdated scriptSrc
Updated website
> Updates for Dart language

- src/technologies/v.json
https://github.com/valeriansaliou/vigil
https://status.crisp.chat/
https://status.pikomit.com/
https://status.kitsune.tv/
> Add Vigil / issue-tracker #6094

- src/drivers/webextension/images/icons/Stencil.svg
- src/technologies/s.json
https://stenciljs.com/
https://www.redbull.com
https://www.hostelworld.com/
https://www.blazeui.com/
http://nmclive.co.uk/
https://targetjobs.co.uk/
https://instamusic-c15fe.firebaseapp.com/
https://corehacker-10883.firebaseapp.com/
> Add Stencil / web-frameworks #6132

- src/technologies/t.json
https://store.hypixel.net/
https://store.spoonkidrust.com/
> Update Tebex / ecommerce

- src/drivers/webextension/images/icons/Weblication.svg
- src/technologies/w.json
https://www.weblication.de/cms/produkte.php
https://scholl.de/
https://gollwitzer-kollegen.de/
https://www.frauenkappelen.ch/de/index.php
https://varius-reisemobile.de/de/index.php
> Add Weblication / cms

- src/technologies/c.json
- src/technologies/w.json
http://www.absmathematics.com/
https://calendly.com/jaredrwright/assessment?month=2022-07
> Update Calendly / appointment-scheduling

- src/technologies/a.json
http://aws.amazon.com/s3/
https://www.bikeleasing.de/
> Update Amazon S3 / cdn

- src/technologies/a.json
https://www.police.be.ch/de/start.html
> Update Adobe Experience Manager / cms

- src/technologies/y.json
https://www.noonacademy.net/
just desc and link updates
> Update YUI / js -lib

- src/technologies/s.json
https://statamic.com/release-notes
https://www.eug-immobilien.de/
https://www.eug-immobilien.de/cp/auth/login
> Update Statamic / cms

- src/technologies/s.json
https://swiperjs.com/
https://musedash.peropero.net/#/
https://shaders-slider.uiinitiative.com/
> Update Swiper / js lib

- src/technologies/m.json
https://cms.maxencedev.fr/
https://mpo-47.fr/
https://survivia-mc.fr/
> Add MaxenceDEVCMS / cms

- src/technologies/a.json
- src/technologies/i.json
https://en.wikipedia.org/wiki/Application_Request_Routing
https://www.iis.net/downloads/microsoft/application-request-routing
http://auction.co.kr/
https://app.ncss.gov.sg/
https://www.cornell.edu/
> Add Application Request Routing / load-balancers

- src/technologies/a.json
- src/technologies/c.json
- src/technologies/e.json
- src/technologies/f.json
- src/technologies/g.json
- src/technologies/h.json
- src/technologies/j.json
- src/technologies/m.json
- src/technologies/o.json
- src/technologies/p.json
- src/technologies/r.json
- src/technologies/s.json
- src/technologies/t.json
- src/technologies/u.json
- src/technologies/v.json
- src/technologies/z.json
Small MR to fix 1 erroneous CPE and add new CPE refs to various technologies.
> Adding new CPEs to various technologies

- src/technologies/u.json
Updated the dom pattern for "Utterances" as suggested in issue #6575. This fixes the issue.
Cheers!
> fix utterances pattern #6575

- src/technologies/f.json
https://flickity.metafizzy.co/
https://unisa.edu.au/
https://smile.io/
https://rothys.com/
https://www.broward.org/
http://tfetimes.com/
https://getintopc.com/
https://newatlas.com/
> Update Flickity / js-lib #6241

- src/drivers/webextension/images/icons/Next Total.svg
- src/technologies/n.json
https://www.next.co.uk/
https://www.reiss.com/
https://www.next.co.il
>  Add Next Total / ecommerce #6265

- src/technologies/a.json
- src/technologies/v.json
https://animate.style
https://www.motorola.com/us/
https://www.avon.com.br/
https://www.zaobao.com.sg/global
https://jakarta.go.id/
http://filmai.in/
https://mee6.xyz/
https://github.com/asika32764/vue2-animate
https://koolearn.com/
https://www.golfchannel.com/
https://restu-averian.vercel.app/
> Add Vue2-animate / miscellaneous , Update Animate.css / ui-framework

- src/technologies/j.json
https://www.j2store.org/
https://ru.leco.com/
> Update J2Store / ecommerce

- src/technologies/c.json
https://github.com/underground-works/clockwork-app
https://underground.works/
https://7.undercovernl.com/auth/login
http://ldce.ac.in/
https://casabo.com.py/
http://exlot.it/
http://motokarovadraha.sk/
https://app.mobileoptin.com/
> Add Clockwork / development

- src/technologies/d.json
> Update Divi / wp-theme, page-builder, wp-plugin

- src/technologies/m.json
https://dynamics.microsoft.com/ru-ru/commerce/overview/
https://www.erath.com/
https://www.hosports.com/
https://www.elicit.wine/
https://www.adventure-works.com/
> Add Microsoft Dynamics 365 Commerce / ecommerce

- src/technologies/v.json
> Update Vue / js-frameworks

- src/drivers/webextension/images/icons/Rain.svg
- src/technologies/r.json
https://www.rainpos.com/
https://www.closetohomestores.com/
https://www.threadbearfabrics.com/shop-online.htm
https://musicstore.oldtownschool.org/
> Add Rain / ecommerce #6656

- src/technologies/s.json
https://h2outdoor.nl/Hottubs/
https://bestmarket.tv/ru
> Update Shopware / ecommerce

- src/technologies/m.json
> Update Matomo Analytics

- src/technologies/j.json
https://judge.me/pricing
https://www.pompeii3.com/
> Update Judge.me / reviews

- src/technologies/p.json
Just remove html, update broken link and add oss
> Update particles.js / js-graphics

- src/technologies/c.json
https://support.cloudflare.com/hc/en-us/articles/200168056-Understanding-Rocket-Loader
https://hamariweb.com/
https://www.harrods.com/en-kz/
https://www.mackintosh.com/gb/man
> Add Cloudflare Rocket Loader / performance ##6283

- src/technologies/t.json
https://dsmall.csdeshang.com/admin/Login/index.html
> Update ThinkPHP / web-framework

- src/technologies/u.json
> Update UptimeRobot / issue-trackers

- src/technologies/s.json
> Update Saleor / ecoomerce

- src/technologies/f.json
https://www.probuilds.net/
https://www.breitbart.com/
https://monkeytype.com/
> Update Font Awesome / font-scripts

- src/technologies/d.json
http://dragonsite.co.in/chatlive/index.dgn
> Update Dragon / programming-languages

- src/technologies/v.json
https://dortania.github.io/OpenCore-Install-Guide/extras/monterey.html
> Update VuePress / static-site-generator

- src/drivers/webextension/images/icons/Kotlin.svg
- src/drivers/webextension/images/icons/Ktor.svg
- src/technologies/k.json
https://ktor.io/
https://kotlinlang.org
https://bookfinder.spoilers.tn.it/
> Add Kotlin / pl, Add Ktor / framework

- src/technologies/a.json
> Update Amplitude / analytics #6701

- src/technologies/l.json
https://business.linkedin.com/marketing-solutions/ads
https://www.teamviewer.com/en/
https://www.lastpass.com/
https://toggl.com/
https://www.vkmag.com/
https://www.eleman.net/
https://www.upward.careers/
> Add Linkedin Ads / advertising

- src/technologies/a.json
- src/technologies/s.json
https://www.salesforce.com/solutions/small-business-solutions/help-desk-software/
https://github.com/forcedotcom/aura
https://www.i-car.com/s/
https://www.promocash.com/s/
https://my.xcelenergy.com/s/state-selector?return=%2Fs%2F
https://www.chicagocares.org/s/
https://customersupport.ecisolutions.com/s/login/?ec=302&startURL=%2Fs%2F
https://my.sma-service.com/s/?language=en_US
https://www.paccarusedtrucks.com/s/
> Add Salesforce Desk / crm , Aura / UI framework

- src/technologies/k.json
https://keap.com/
https://aulacm.com/
> Update Keap / crm

- src/technologies/i.json
http://www.igodigital.com/
https://www.crunchbase.com/organization/igodigital
https://www.crunchbase.com/organization/exacttarget
https://www.salesforce.com/products/marketing-cloud/email-marketing/?d=www.exacttarget.com/&internal=true
https://www.mbusa.com/en/home
https://www.justfly.com/
https://www.arlo.com/en-us/
https://www.aarons.com/
https://www.merrell.com/US/en/home
https://www.enfamil.com/
> Add iGoDigital / personalisation

- src/drivers/webextension/images/icons/Lengow.svg
- src/technologies/l.json
https://www.lengow.com/
https://www.promod.pl/pl-pl/
https://www.habitat-automatisme.com/
https://lagunasport.com/en/
https://www.lulu-berlu.com/
https://www.maxisport.com/
> Add Lengow / miscellaneous

- src/drivers/webextension/images/icons/Meilisearch.svg
- src/technologies/m.json
https://www.meilisearch.com/pricing
https://www.fantasyalarm.com/
https://thechocolatelife.com/
https://www.loireavelo.fr/
https://tauri.app/
> Add Meilisearch / search-engine

- src/drivers/webextension/images/icons/Better Uptime.svg
- src/technologies/b.json
https://betterstack.com/better-uptime/pricing
https://status.feedly.com/
> Add Better Uptime / issue-tracker #6365

- src/drivers/webextension/images/icons/QuickSell.svg
- src/technologies/q.json
https://quicksell.co/
https://toyport.in/
> Add QuickSell / ecommerce #6399

- src/technologies/m.json
https://github.com/magewirephp/magewire
https://activeshop.com.pl/
https://syis.pl/
> Add Magewire / miscellaneous #6409

- src/technologies/f.json
https://fresh.deno.dev/
Updated for v1.1
> Update Fresh dom

- src/technologies/f.json
https://github.com/fudforum/FUDforum
http://fudforum.org/forum/
https://forum.livedating.me/
https://forum.planete-cartables.net/
> Add FUDforum / message-boards #6494

- src/technologies/t.json
https://github.com/ganlanyuan/tiny-slider
https://xuite.net/
https://www.eluniversal.com.mx/
https://www.film.ru/
https://www.junkmail.co.za/
https://malcat.fr/
https://ganlanyuan.github.io/tiny-slider/demo/
> Add Tiny Slider / js lib #6570

- src/technologies/k.json
https://www.now14.co.il/tochniot_meleot/%D7%A9%D7%99%D7%93%D7%95%D7%A8-%D7%97%D7%99/
> Update Kaltura / video-players #6583

- src/drivers/webextension/images/icons/NodePing.svg
- src/technologies/n.json
https://nodeping.com/pricing.html
https://status.ramnode.com/reports/statusevents/7MHS7LS2GN
> Add NodePing / issue-tracker #6662

- src/technologies/s.json
https://statically.io/
https://ww1.modrsbook.com/
http://underscorejs.org/
http://directapp.net/
https://flipshope.com/
https://jobchjob.in/
https://guanajuato.gob.mx/
> Update Statically / cdn

- src/technologies/p.json
Add cookie + x-redirected-by header (value can be "Polylang" or "Polylang Pro")
> Improve Polylang detection

- src/drivers/webextension/images/icons/Bricks.svg
- src/technologies/b.json
https://bricksbuilder.io/
https://www.traffic-masters.net/
http://educacionviva.com/
https://www.powermax.com/
https://facilyta.com.br/
> Add Bricks / page-builder, wp-theme

- src/technologies/o.json
https://webmail.candwmail.com/
http://mundoentretenido.com/
https://privateemail.com/
> Update Open-Xchange App Suite / webmail, email #6781

- src/technologies/v.json
https://my.awesomebible.de/
https://www.eventsprout.com/
https://www.v-system.sk/
> Update Vue.js / js-framework

- src/technologies/a.json
https://mylesthe.dev/projects
https://getbem.com/
https://24saat.net/
> Update Astro / static-site-generator

- src/technologies/g.json
> Update Google Tag Manager / tag #6729

- src/technologies/r.json
https://rankmath.com/
https://fixourwebsite.com/
https://cricketaddictor.com/
https://setare.com/
> Update RankMath SEO / seo, wp-plugin

- src/drivers/webextension/js/driver.js
- src/drivers/webextension/js/popup.js
- src/drivers/webextension/js/utils.js
- src/drivers/webextension/manifest-v3.json
- src/technologies/d.json
https://www.acromedia.com/
https://www.vejdirektoratet.dk/
https://www.egmont.com/
> Update Drupal / cms

- src/drivers/webextension/js/driver.js
- src/drivers/webextension/js/popup.js
- src/drivers/webextension/js/utils.js
- src/drivers/webextension/manifest-v3.json
- src/technologies/p.json
https://github.com/vuejs/petite-vue
https://sgsparebank.no/
https://etne-sparebank.no/
https://sso.no/
https://516.ru/
https://learntla.com/
> Add petite-vue / miscellaneous #6320

- src/drivers/webextension/js/driver.js
- src/drivers/webextension/js/popup.js
- src/drivers/webextension/js/utils.js
- src/drivers/webextension/manifest-v3.json
- src/technologies/v.json
> Fix DOM selector

- src/technologies/s.json
Example site
* https://www.squiz.net/matrix
> Update Squiz Matrix details.

- src/technologies/u.json
Example site
* https://www.rbg.vic.gov.au/
> Update Umbraco detection.

- src/technologies/d.json
Example site 
* https://www.anbg.gov.au/
> Improve dreamweaver detection

- src/technologies/i.json
> Update Instatus / issue-tracker #6823

- src/technologies/h.json
https://github.com/h2o/h2o
https://www.ngnl.org/
https://www.rgbstock.com/
https://peco-japan.com/
https://www.mourjan.com/
> Add H2O / web-servers #6826

- src/technologies/p.json
> Update Prismic / cms

- src/technologies/e.json
https://mexen.pl/
https://www.123lazienka.pl/
https://marjoman.es/en/
https://ferrolan.es/
> Update Elasticsearch / search-engine

- src/technologies/a.json
> Update Astro / ssg

- src/technologies/s.json
https://smtpjs.com/
https://www.scholasticus.com/
https://daralber.ae/ar/home
https://www.nanus.com.br/
https://stepup.ae/
https://ksar-elkabbaba.com/
> Add SmtpJS / email

- src/technologies/s.json
https://www.imotionsecurite.com/index-eng.html
> Update Slider Revolution / widget

- src/technologies/t.json
https://forbesforms.typeform.com/to/kUAuZU1U?typeform-source=github.com
> Update Typeform / surveys

- src/technologies/p.json
https://phprs.net/
http://www.regionycr.cz/
https://radiocolor.cz/
https://www.cibulka.net/petr/index.php
https://bdjm.cz/
https://fatym.com/
http://www.sberatel-ksk.cz/
> Add phpRS / cms

- src/technologies/p.json
Polylang have 2 version, a free on WP.org and a premium.This PR is detecting the difference.
> Detect if Polylang Pro or Polylang is used

- src/technologies/u.json
> Update Umami js detection

- src/drivers/webextension/images/icons/Sourcepoint.svg
- src/technologies/s.json
https://sourcepoint.com/
https://qz.com/
https://www.si.com/
https://www.sky.com/
https://www.avclub.com/
https://www.telegraph.co.uk
https://www.thesun.co.uk/
https://jalopnik.com/
https://reelrundown.com/
https://turbofuture.com/
https://www.n-tv.de/
https://www.haymarket.com/
> Add Sourcepoint / cookie-compliance

- src/drivers/webextension/images/icons/BookStack.svg
- src/technologies/b.json
https://www.bookstackapp.com/
https://docs.usbx.me/
https://wikishare.xyz/
https://anfarch.org/
https://demo.bookstackapp.com/
implies confirm
https://github.com/BookStackApp/BookStack
cpe
https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=BookStack
> Add BookStack / documentation

- src/technologies/s.json
http://www.y-media.be/
https://www.monde-diplomatique.fr/
https://www.xboxygen.com/
https://blog.juliendelmas.fr/
> Update SPIP / cms

- src/technologies/a.json
> Update AOS / js-lib

- src/drivers/webextension/images/icons/wBuy.svg
- src/technologies/w.json
https://www.wbuy.com.br/planos/
https://www.upah.com.br/
https://www.guriaperfeita.com.br/
> Add wBuy / ecommerce

- src/technologies/c.json
- src/technologies/m.json
- src/technologies/o.json
- src/technologies/p.json
https://apex.oracle.com/en/
https://kegel-sport.info/
https://www.titelbank.nl/
https://realpaycollect.com/
https://www.auctim.com/
https://april-capital.ru/
https://ksc.uz/
> Add Oracle Apex  / page-builder , Update CKEDITOR,MonacoEditor, Prism

- src/technologies/c.json
https://www.cloudflare.com/products/turnstile/
https://demo.turnstile.workers.dev/
https://with-cloudflare-turnstile.vercel.app/
> Add Cloudflare Turnstile / security #6847

- src/technologies/c.json
- src/technologies/v.json
https://vkcom.github.io/VKUI/
https://vtosters.app/
> Add VKUI / ui-framework, Remove Cloudflare NEL #6778 

- src/technologies/l.json
https://www.logicommerce.com/
https://www.eurekakids.com/
> Update LogiCommerce / ecommerce

- src/technologies/u.json
https://www.thomann.de/intl/hotdeals.html
> Update UserLike / live-chat

- src/technologies/o.json
https://exchange.oxid-esales.com/OXID-Products/OXID-eShop/OXID-eShop-Professional-Edition-6-Professional-Edition-6-Stable-PE-6-0-x.html
https://www.schindelhauerbikes.com/en/home/
Professional Edition 
Enterprise Edition
Community Edition"
> Add OXID eShop Professional Edition / ecommerce

- src/technologies/d.json
https://github.com/sandoche/Darkmode.js
http://bitturk.net/?p=home&pid=1
https://learnmmd.com/
https://nabla.no/
https://www.milesfeed.com/
https://getstayactive.com/
http://gitcdn.link/
> Add Darkmode.js / js-lib

- src/technologies/i.json
https://www.dialogtech.com/
https://www.invoca.com
https://monroeengineering.com/
https://www.watermarkcommunities.com/
> Update Invoca / analytics, marketing-automation

- src/technologies/s.json
> Update Saleor / ecommerce

- src/technologies/a.json
> Update Animate.css / ui-frameworks

- src/technologies/c.json
https://chimpmatic.com/
https://www.modehuisblok.nl/
> Add Chimpmatic / wp-plugin

- src/technologies/a.json
https://angular.io/
https://angular.io/
> Update Angular / js-frameworks

- src/technologies/e.json
Example site
* https://www.ato.gov.au/
> Add Ektron CMS

- src/technologies/s.json
Example sites
* https://www.qld.gov.au/
* https://www.health.qld.gov.au/
Detections found in the docs https://matrix.squiz.net/manuals/keyword-replacements/chapters/global-keywords
> Better Squiz Matrix detection.

- src/technologies/v.json
- https://vercel.com/analytics
examples
- https://vercel.com/
- https://rgllm.com/
- https://www.mailing.run/
- https://lioncityhacks.com/
- https://mario.dev/
> Add Vercel Analytics

- src/technologies/c.json
https://magneticmarketing.com/
http://unet-marketing.de/
http://sonsofstrength.com/
> Update ClickFunnels / page-builders

- src/technologies/g.json
https://sarcadass.github.io/granim.js/
https://asdfiles.com/
https://soliddrive.co/
https://www.adpushup.com/
https://pushassist.com/
https://iitgn.ac.in/
http://www.readytoship.com.au/
> Add Granim.js / js-lib

- src/technologies/o.json
The Okta template was not detecting a lot of Okta instances. I updated the template to include current Javascript elements for better matching
> Template update

- src/categories.json
- src/drivers/webextension/_locales/ca/messages.json
- src/drivers/webextension/_locales/de/messages.json
- src/drivers/webextension/_locales/el/messages.json
- src/drivers/webextension/_locales/en/messages.json
- src/drivers/webextension/_locales/es/messages.json
- src/drivers/webextension/_locales/fa/messages.json
- src/drivers/webextension/_locales/fr/messages.json
- src/drivers/webextension/_locales/gl_ES/messages.json
- src/drivers/webextension/_locales/gr/messages.json
- src/drivers/webextension/_locales/id/messages.json
- src/drivers/webextension/_locales/it/messages.json
- src/drivers/webextension/_locales/ja/messages.json
- src/drivers/webextension/_locales/ko/messages.json
- src/drivers/webextension/_locales/nl/messages.json
- src/drivers/webextension/_locales/pl/messages.json
- src/drivers/webextension/_locales/pt/messages.json
- src/drivers/webextension/_locales/pt_BR/messages.json
- src/drivers/webextension/_locales/ro/messages.json
- src/drivers/webextension/_locales/ru/messages.json
- src/drivers/webextension/_locales/sk/messages.json
- src/drivers/webextension/_locales/tr/messages.json
- src/drivers/webextension/_locales/uk/messages.json
- src/drivers/webextension/_locales/uz/messages.json
- src/drivers/webextension/_locales/zh_CN/messages.json
- src/drivers/webextension/_locales/zh_TW/messages.json
- src/technologies/h.json
- src/technologies/p.json
- src/technologies/v.json
Hyva Themes, Vue Storefront, PWA studio
> Add Ecommerce frontends / category

- src/technologies/h.json
https://help.hcltechsw.com/digital-experience/9.0/admin-system/layout_toolbar_customization.html
https://www.sda.it/wps/portal/sdait.home/
https://wwwn.bradescoseguros.com.br/
https://www.liquigas.com.br/wps/portal
https://www.hcltechsw.com/
https://www.magnasistemas.com.br/wps/portal/internet
> Update HCL Digital Experience / cms

- src/drivers/webextension/images/icons/Next.js.svg
- src/technologies/n.json
> Update Next.js icon

- src/technologies/s.json
https://simplesamlphp.org/
https://github.com/simplesamlphp/simplesamlphp
https://www.bportugal.pt/
https://www.th-koeln.de/
https://www.psfk.com/
https://www.musicalvienna.at/de/home
https://www.wien-ticket.at/de/home
https://www.heraklion.gr/
> Add SimpleSAMLphp / authentication

- src/technologies/i.json
https://www.pirobase-imperia.com/de/solutions/imperia-cms
https://www.nuernberg.de/internet/stadtportal/index.html
https://www.uni-muenster.de/de/
https://www.lotto-bayern.de/
https://www.strato.de/
https://www.daad.de/de/
https://www.strato.nl/
https://www.strato.es/
fixed:
imperia CMS 11. to  imperia CMS  11.3.4 or imperia CMS  11.3.4_1
> Update imperia CMS / cms

- src/technologies/s.json
https://www.storyblok.com/pricing
http://4k.com/
https://www.tele2.nl/
https://en.ryte.com/
https://bevolta.com/
removed meta couldn't find examples and [#1539 ](https://github.com/wappalyzer/wappalyzer/pull/1539) example links broken and not looks safe  and anyway https://www.wappalyzer.com/technologies/cms/storyblok/ here 0 results
> Update Storyblock / cms

- src/technologies/t.json
> Update Twitter Emoji / font-scripts

- src/technologies/r.json
https://ygosu.com/
https://www.rbc.ru/
https://citypark.re/
https://academy.qwerio.net/
> Update RightJS / js-framework

- src/drivers/webextension/images/icons/Obsidian Publish.svg
- src/technologies/o.json
https://obsidian.md/pricing
https://notes.nicolevanderhoeven.com/Obsidian+Publish
https://help.obsidian.md/Obsidian/Index
https://integralguide.com/%E2%AD%90%EF%B8%8F+Start+Here/About
https://publish.obsidian.md/chromatically/publish+homepage
> Add Obsidian Publish / documentation

- src/technologies/f.json
Example pages using funding choices:
1. https://www.indiatoday.in/
2. https://www.phonearena.com/
> Add Funding Choices to technologies

- src/technologies/s.json
- https://segment.com/
- https://www.loom.com/
- https://www.digitalocean.com/
> Update Segment Detection

- src/technologies/v.json
> Update VTEX / ecommerce

- src/technologies/t.json
https://speedmatters.org/
https://farras-arrafi.my.id/
> Update Tailwind CSS / ui-framework

- src/technologies/v.json
> Update Vue.js / javascript-frameworks

- src/drivers/webextension/images/icons/Heap.svg
https://www.heap.io/blog/heaps-new-brand
> Update Heap icon

- src/technologies/o.json
https://tyapk.ru/blog
Dont see many results, should work without false positives results
> Update October CMS / cms

- src/technologies/f.json
https://www.fleksa.com/fleksa-pricing
https://eatarian.com/
https://restaurant-nidda.de/en
https://delitadka.de/en
https://bhojangrih.de/en
https://smartpizzas.de/
> Update Fleksa / Reservations & delivery

- src/drivers/webextension/images/icons/Axios.svg
- src/technologies/a.json
- https://axios-http.com/
- https://github.com/axios
> Add Axios icon

- src/technologies/m.json
https://cari-makan.vercel.app/places/bakso-rusuk-joss-pusat-bekasi/direction?longitude=107.02660933116783
https://mealpal.com/uk/
> Update Mapbox GL JS / maps

- src/technologies/v.json
Locally work , extensions don't want to work. Although there are all traces in the headers
btw add desc,pricing
https://vercel.com/pricing
https://www.andrewdragon.dev/
> Update Vercel / paas

- src/drivers/webextension/images/icons/DocuSign.svg
- https://brand.docusign.com/logo
> Update DocuSign icon

- src/drivers/webextension/images/icons/Bootstrap.svg
> Update Bootstrap icon

- src/technologies/s.json
https://www.google.com/search?q=sxa_site&oq=sxa_site&aqs=chrome..69i57.503j0j7&sourceid=chrome&ie=UTF-8
https://www.cerner.com/
https://www.swk.de/
https://adpolice.gov.ae/
https://www.uchicago.edu/
> Update Sitecore / cms

- src/technologies/a.json
https://support.atlassian.com/statuspage/docs/configure-your-dns/
> Add Atlassian Statuspage DNS TXT Record Detection

- src/technologies/o.json
https://www.onetrust.com/
- https://loom.com: https://dns.google/query?name=loom.com&rr_type=TXT
- https://reddit.com: https://dns.google/query?name=reddit.com&rr_type=TXT
- https://yelp.com: https://dns.google/query?name=yelp.com&rr_type=TXT
> Add OneTrust DNS TXT Record detection

- src/technologies/n.json
https://nextra.vercel.app/
- https://nextra.vercel.app/
- https://swr.vercel.app/
> Add Nextra Detection

- src/technologies/v.json
- ysm.dev: https://dns.google/query?name=ysm.dev&rr_type=SOA
- paco.me: https://dns.google/query?name=paco.me&rr_type=SOA
- vercel.com: https://dns.google/query?name=vercel.com&rr_type=SOA
> Add Vercel DNS SOA Detection

- src/technologies/e.json
https://www.artacademybrand.it/en/
https://aldamstreetart.it/
https://medthai.com/
https://kaunas.kasvyksta.lt/
https://www.infocert.it/
https://setare.com/
https://www.minuto30.com/
https://plos.org/
> Update Elementor / page-builder, wp-plugin #6966

- src/drivers/webextension/images/icons/Stitches.svg
> Update Stitches icon

- src/technologies/a.json
- https://apple.com/icloud
- https://support.apple.com/guide/icloud/set-up-a-custom-email-domain-mm0e4339d289/icloud#:~:text=Go%20to%20Settings%20%3E%20%5Byour%20name,then%20follow%20the%20onscreen%20instructions.
Examples
- https://ysm.dev -> https://dns.google/query?name=ysm.dev&rr_type=MX, https://dns.google/query?name=ysm.dev&rr_type=TXT
- https://paco.me -> https://dns.google/query?name=paco.me&rr_type=MX, https://dns.google/query?name=paco.me&rr_type=TXT
- https://daun.io -> https://dns.google/query?name=daun.io&rr_type=MX, https://dns.google/query?name=daun.io&rr_type=TXT
- https://cretu.dev -> https://dns.google/query?name=cretu.dev&rr_type=MX, https://dns.google/query?name=cretu.dev&rr_type=TXT
- https://rauno.me -> https://dns.google/query?name=rauno.me&rr_type=MX, …
> Add Apple iCloud Detection

- src/technologies/a.json
I have added the HTML DOM Element to detect the AOS which is used & installed using NPM instead of CDN Files.
> AOS Detection using HTML DOM

- src/technologies/z.json
- Zone.js dependent on Angular
> Add Zone.js icon

- src/technologies/h.json
https://dns.google/query?name=salesforce.com&rr_type=TXT&ecs=
https://dns.google/query?name=coda.io&rr_type=TXT&ecs=
> Update HubSpot dns TXT detection

- src/technologies/c.json
https://github.com/ninenines/cowboy
https://github.com/heroku/cowboyku
https://github.com/heroku/vegur
https://devcenter.heroku.com/articles/ruby-default-web-server
https://speakerdeck.com/
https://arsenalwebsystems.com/
> Update Cowboy / web-server

- src/technologies/h.json
https://zapier.com
- https://dns.google/query?name=zapier.com&rr_type=TXT&ecs=
> Add HubSpot TXT Record

- src/technologies/c.json
- https://scale.com: https://dns.google/query?name=scale.com&rr_type=NS&ecs=
> Add Cloudflare DNS record detection

- src/drivers/webextension/images/icons/Proton Mail.svg
- src/technologies/p.json
https://proton.me/mail
examples
- https://proton.me: https://dns.google/query?name=proton.me&rr_type=ALL&ecs=
- https://minds.com: https://dns.google/query?name=minds.com&rr_type=MX&ecs=
- https://bbguimaraes.com: https://dns.google/query?name=bbguimaraes.com&rr_type=MX&ecs=
> Add Proton Mail Detection

- src/drivers/webextension/images/icons/WhatsApp.svg
> Update WhatsApp icon

- src/drivers/webextension/images/icons/TrustArc.svg
https://trustarc.com/
use their favicon
> Update TrustArc icon

- src/technologies/s.json
https://www.sendinblue.com/
https://automait.it/blog/setting-up-sendinblue/
ex
- https://dns.google/query?name=anir0y.in&rr_type=TXT&ecs=
- https://dns.google/query?name=sudouest.fr&rr_type=TXT&ecs=
> Add Sendinblue DNS Detection

- src/drivers/webextension/images/icons/Mailjet.svg
> Update Mailjet icon

- src/technologies/m.json
> Update MyBB / forums #7179

- src/technologies/o.json
https://world.optimizely.com/documentation/Items/Developers-Guide/EPiServer-Find/9/REST-API/
https://www.regionstockholm.se/
https://www.politiet.no/
https://www.bi.no/
> Update Optimizely Content Management / cms

- src/technologies/c.json
Add new detection examples:
http://grapp.ir/
https://www.vashdosug.ru/
https://portal.ciee.org.br/
https://kvf.fo/
http://www.designindaba.com/
remove false-positive example:
https://www.aeyesec.jp/
> Update Choices / js-lib #7129

- src/technologies/h.json
Server: hcdn
Platform: hostinger
Signed-off-by: Donatas Abraitis <donatas@hostinger.com>
> technologies: Detect Hostinger when using HTTP headers

- src/technologies/k.json
https://vkcom.github.io/kphp
https://vk.com
> Add KPHP / programming-languages

- src/technologies/p.json
https://pixijs.io/examples/#/demos-basic/container.js
http://icekings.ru/
Probably such a recursive dom is not parsed correctly
> Update PIXIjs / js-graphics

- src/technologies/p.json
https://www.picketandrail.com/products/kuka-2537-fabric-sofa-2-seater-color-c-1075?variant=16921021972550
> Trace Rely BNPL

- src/drivers/webextension/images/icons/skilljar.svg
- src/technologies/s.json
Skilljar is one of the more prominent B2B LMS platforms.
> Add Skilljar (LMS)

- src/drivers/webextension/images/icons/paysafe.svg
- src/technologies/p.json
**Examples:**
All examples are using `script` tag, and `paysafe` js object.
**using `paysafe.checkout`:**
https://beyond.mohegansun.com/msct/
https://beyond.mohegansunpocono.com/
https://www.acdq.qc.ca/en/
**using `paysafe.fields`:**
https://app.emma.ca/en/terms-and-conditions
https://app.airix.ca/fr/login
**using `paysafe.threedsecure`:**
https://webtrader.dev05.aaatrade.com/dashboard
> PaySafe Trace Added

- src/technologies/g.json
https://generatepress.com/pricing/
https://efe.com/
> Update GeneratePress / wp-theme

- src/technologies/v.json
https://www.ocn.ne.jp/
https://koala.com/en-au
> Update VWO / ab-test, analytics

- src/technologies/w.json
https://webflow.com/ecommerce
https://webflow.com/pricing
https://www.spaceposters.co/
https://www.lintendance.co/
https://www.twigspaper.com/
> Add Webflow Ecommerce / ecom, Update Webflow / page-builders

- src/technologies/t.json
> Fix: Unbalanced brackets in Tally pattern

- src/technologies/p.json
Detect partytown usage by checking if `script[type*='text/partytown']` is in the dom.
https://partytown.builder.io/partytown-scripts
> Detect partytown using script tag dom check

- src/technologies/p.json
Fixing this issue:
https://github.com/wappalyzer/wappalyzer/issues/7301
> Fixed JSON missing comma

- src/technologies/a.json
> Update Apollo / js-lib

- src/technologies/d.json
https://www.getpaint.net/
https://kidzone.ws/
http://disfrutalasmatematicas.com/
https://dltk-holidays.com/
> Update DreamWeaver / editors

- src/drivers/webextension/images/icons/Microsoft Visual Studio.svg
- src/technologies/m.json
https://visualstudio.microsoft.com/
https://mgm.gov.tr/
http://dhsekerala.gov.in/
https://neelwafurat.com/
https://logon.travelers.com/travelerslogin.asp?ru=https%3A%2F%2Flogon.travelers.com%2F
https://www.aladin.co.kr/home/welcome.aspx
> Add Microsoft Visual Studio / development

- src/technologies/a.json
- src/technologies/n.json
https://github.com/webserver-llc/angie
https://angie.software/en/
https://simatix.ru/
> Add Angie / web-server #7321

- src/technologies/s.json
https://www.comptia.org/
https://www.cmich.edu/
> Update Sitefinity / cms

- src/technologies/a.json
> Add amplitude js detection

- src/technologies/v.json
https://vitepress.vuejs.org/
- https://vitejs.dev/
- https://vitepress.vuejs.org/
- https://vueuse.org/
- https://vuejs.org/
> Add VitePress Detection

- src/technologies/a.json
https://antibot.cloud/#pricing
http://biofile.ru/
https://usamodelkina.ru/
https://sbankami.ru/
> Add AntiBot.Cloud / security #7285

- src/technologies/d.json
- src/technologies/s.json
https://bestexperiencelisbon.com/
https://www.mines.edu/
https://www.paybox.com/
https://www.managebac.com/
> Update Divi,Slider Revolution / versions

- src/technologies/h.json
We have two products, let's split into separate categories.
Signed-off-by: Donatas Abraitis <donatas.abraitis@hostinger.com>
> technologies: Split Hostinger hosting from Hostinger CDN

- src/drivers/webextension/_locales/nl/messages.json
This commit fixes the "Page Builder" translation for Dutch.
> Fix wrong translation

- src/technologies/k.json
Updated the Kentico CMS detection
> Updated Kentico detection

- src/technologies/v.json
> Add Vercel Analytics scriptSrc

- src/technologies/v.json
https://github.com/vitejs/vite/blob/main/packages/plugin-legacy/src/index.ts#L113
> Add vite dom,js detection

- src/drivers/webextension/images/icons/renderbetter.svg
- src/technologies/r.json
> RenderBetter Trace Added

- src/technologies/a.json
https://developer.apple.com/maps/web/
https://www.apple.com/
https://www.kcrw.com/
https://gps-coordinates.org/
https://www.gps-coordinates.net/
https://overview-ip.tadmin.de/178.13.102.66/1
> Add Apple MapKit JS / maps

- src/technologies/c.json
> Cloudflare Stream Detection added

- src/technologies/a.json
#7352 
Angie trace detection improved if the Version is not there then Angie is not detected - resolved
> Angie Detection Improved

- src/technologies/d.json
- src/technologies/u.json
https://www.sqlfather.com/
https://ketrade.com.vn/FO_AM_LI
> Update UmiJs, Depict

- src/technologies/d.json
> Update Docusaurus / documentation, ssg

- src/technologies/a.json
- src/technologies/n.json
> Update Nginx, Antibot.Cloud /  #7285, #7361

- src/technologies/m.json
https://korzh.com/metroui
https://github.com/olton/Metro-UI-CSS
http://fantazm.net/
https://sqlitestudio.pl/
https://prepasoficiales.net/
> Add MetroUI / ui-frameworks

- src/drivers/webextension/images/icons/AlumnIQ.svg
- src/technologies/a.json
https://www.alumniq.com/platform/
https://wp.stolaf.edu/giving/
https://stolaf.alumniq.com/giving/to/default
https://bluehens.com/
https://ud.alumniq.com/giving/to/bluehens
> Add AlumnIQ / fundraising-donations

- src/technologies/d.json
https://americansforprosperityfoundation.org/
> Update Divi / page-builders

- src/technologies/a.json
> Update Astro / js-framework #7411

- src/technologies/c.json
> Update CodeMirror / editors #7388

- src/technologies/a.json
add a version number to afosto detection
> afosto version number

- src/technologies/c.json
- src/technologies/g.json
> Update Contentful, GraphQL

- src/technologies/e.json
issue: #7422 
Website: https://www.oclc.org/en/ezproxy.html
Examples : 
- https://eressources.imist.ma
- https://eressources.um6p.ma
- https://login.proxy1.lib.uwo.ca
- https://login.ezproxy.eth.mpg.de
- https://ezproxy.usj.edu.lb
- https://ezproxy.yu.edu.jo
- https://login.proxy.library.mfu.ac.th
- https://ezproxy.jnu.ac.in
- https://ezproxy.ump.edu.my
- https://ezproxy.usim.edu.my/login
> Add EZproxy / web server 

- src/technologies/s.json
https://github.com/spatie/laravel-cookie-consent
https://www.gfmreview.com/
https://hypeddit.com/
traces implies Laravel  here https://www.lazarusdev.com/
> Add Spatie Laravel Cookie Consent / cookie-compliance

- src/technologies/s.json
https://www.raleigh.co.uk/gb/en/
https://www.aftership.com/
> Update Storyblok / cms

- src/technologies/a.json
> Update Autoptimize / wp-plugin

- src/drivers/webextension/images/icons/Splide.svg
- src/technologies/s.json
https://splidejs.com
https://github.com/Splidejs/splide
https://www.uniqlo.com/
https://www.noip.com/
https://dana.ir
https://mthai.com/
https://www.fandango.com/
> Add Splide / js-lib

- src/technologies/r.json
example: https://www.mysuedvers.de/, https://www.suedwissen.de/
Rank Math is a popular SEO plugin for WordPress that offers a wide range of features to optimize a website for search engines. While Rank Math includes some basic analytics functionality, it does not directly integrate with Google Analytics.
However, Rank Math does offer support for adding Google Analytics tracking codes to a website. This allows users to track website traffic and gain insights into user behavior, such as pageviews, bounce rates, and time spent on site. By integrating with Google Analytics, users can track the effectiveness of their SEO efforts and gain a better understanding of how visitors are interacting with their website.
It's important to note that while Rank Math and Google Analytics are both valuable …
> Update RankMath SEO / wp-plugin

- src/technologies/o.json
https://www.oracle.com/java/weblogic/
https://www.siriusxm.com/
https://www.jio.com/
https://www.mysynchrony.com/
https://login.oracle.com/mysso/signon.jsp
> Add Oracle WebLogic Server / webserver

- src/technologies/k.json
https://www.kadencewp.com/pricing/
https://windwardpro.com/
https://skirose.com/
> Add Kadence WP Blocks / wp-plugin

- src/drivers/webextension/images/icons/Frames.svg
- src/technologies/f.json
https://getframes.io/
https://automaticcss.com/
> Add Frames / wp-plugin

- src/technologies/s.json
https://www.visitsanantonio.com/
https://www.mind2bodyfit.com/
https://www.gambit.ph/
> Update Stackable / wp-plugin

- src/technologies/b.json
https://creativethemes.com/blocksy/pricing/
https://ashraafi.com/
https://supplyframe.com/
https://madisoft.it/
https://laughingsquid.com/
http://newsweb.pl/
> Add Blocksy Companion / wp-plugin

- src/technologies/r.json
> ReadAloud Trace added

- src/drivers/webextension/images/icons/Tinybird.svg
- src/technologies/t.json
https://www.tinybird.co
ex)
- https://www.tinybird.co
- https://localstack.cloud
> add Tinybird Detection

- src/technologies/s.json
https://spritespin.ginie.eu/
https://github.com/giniedp/spritespin
https://www.specialized.com/gb/en
https://www.starline.ru/
https://www.kopfhoerer.de/
https://vossenwheels.com/
https://www.perodua.com.my/
> Add SpriteSpin / js-lib

- src/technologies/m.json
https://mavo.io/
https://lea.verou.me/
https://portswigger-labs.net/mavo/?inj=%5B4%2b4%5D
> Add Mavo / js-lib

- src/technologies/m.json
Basic understanding of Python is required to use MkDocs effectively. MkDocs is a static site generator that is built using the Python programming language, and it uses Python to execute many of its core functions.
In order to create and customize a documentation website using MkDocs, you will need to be able to create and edit Markdown files, which is a simple markup language used for formatting text. Additionally, you may need to modify the configuration file and use Python to add custom plugins or functionality to your site.
While some parts of MkDocs can be managed through a user interface or configuration files, understanding Python basics can be beneficial when working with more complex customizations or troubleshooting issues.
https://developers.engineerforce.io/
> Update MkDocs / documentation

- src/technologies/w.json
https://salamateman.com/
https://high-five.ir/
https://www.its.ac.id/
> Update WP-Statistics / wp-plugin, analytics

- src/technologies/n.json
https://docs.netlify.com/forms/setup/#html-forms
> Add Netlify Forms detection

- src/technologies/a.json
- https://vapor.laravel.com/login
> Improve AWS ELB detection

- src/technologies/f.json
https://bulma.io/
https://uzone.id/
https://www.woxikon.de/
> Update Font Awesome / font scripts

- src/technologies/n.json
https://demoisellemm.fr/galerie-oeuvres-d-art-vente-en-ligne-demoisellemm
> Update NextGEN Gallery / wp-plugin

- src/technologies/a.json
https://www.alibabacloud.com/product/object-storage-service
https://albertoroura.com/
https://nordkappcampers.com/
http://doyoudo.com/
http://wtoip.com/
> Add Alibaba Cloud Object Storage Service / iaas

- src/drivers/webextension/images/icons/Zyro.svg
- src/technologies/h.json
- src/technologies/z.json
Changes in technology name, icon, and detection meta tag.
**Website:** 
https://www.hostinger.com/website-builder
**Examples:**
https://www.klausuciualus.lt/
https://acottonphoto.com/
https://www.brahmleen.com/
> Update technology Zyro to Hostinger Website Builder

- src/drivers/webextension/images/icons/retype.svg
- src/technologies/r.json
> Retype Trace Added

- src/technologies/s.json
> Update Sylius / ecommerce

- src/technologies/e.json
Couldn't fix the detection issue here. Just added a description
https://opsb.co.uk/
> Update Elm, Elm-ui / pl

- src/technologies/m.json
https://mdbgo.com/docs/projects/wordpress/
https://alcde.pythonanywhere.com/
https://www.cim.be/nl
> Add MDBootstrap WP theme / wp-theme

- src/technologies/e.json
https://blog.montazer.ir/examining-the-concept-of-fasting-and-its-wide-domain/
> Update Elementor / page-builder, wp-plugin

- src/technologies/s.json
Example:
- https://alexatallah.com/
> Improve "Super Builder" detection

- src/technologies/n.json
https://ancientnutrition.com/
https://www.bollandbranch.com/
https://www.somethingnavy.com/
https://mylola.com/collections/periods
https://ensorings.com/
> Update Nacelle / ecommerce

- src/technologies/s.json
> Update Stencil / web-components

- src/technologies/q.json
**Examples of `link[href]`**:
https://my.iccsafe.org/login
https://games.steelseries.com/home
**Example of `div` class**:
https://zenoamaro.github.io/react-quill/
> Quilljs Rich Text Editor Trace Improved

- src/technologies/a.json
https://sndigitalhub.com/
https://slenterprises.co.in/
https://sureenterprise.com/
https://melavaamruttulya.in/
https://spconsultancy.online/
https://allensiapharmaceuticals.com/
https://shreepathlab.sndigitalhub.com/
https://cateringservicepuneannapurna.co.in/
https://rpsdc.org.in/
https://memtgroup.co.in/
https://cnchomecleaningservices.com/
https://shrishyamsinghar.in/
https://planeasygroup.com/
https://planeasygroup.com/
https://shrishyamsinghar.in/
> Add Arya CMS / cms

- src/technologies/a.json
Analyzee was missing scriptSrc property
> Update Analyzee scriptSrc

- src/technologies/s.json
> Slider Captcha trace added

- src/drivers/webextension/images/icons/Kosmos.svg
- src/technologies/k.json
https://www.ksup.org
https://www.ulb.be
https://www.univ-nantes.fr
https://www.campus-condorcet.fr
https://www.ec-nantes.fr
https://www.cyu.fr
https://www.ens-rennes.fr
https://www.icp.fr
https://www.nd-grandchamp.fr
https://univ-cotedazur.fr
https://www.u-pec.fr
https://www.univ-tlse2.fr
https://www.uca.fr
https://www.sciencespo-toulouse.fr
> Add K-Sup / cms

- src/technologies/m.json
https://mailchi.mp/preferredbynature/newsletter-dec22
> Update MailChimp / email marketing

- src/technologies/u.json
https://umijs.org/
https://dview.dlink.com/
> Update UmiJs / js framweorks

- src/technologies/s.json
> SwaggerUI Detection using JS added

- src/technologies/c.json
**`Example:`**
https://www.envato.com/
https://mixkit.co/
> Cookiebot Version Detection using js

- src/technologies/v.json
**`Example:`**
https://www.upwork.com/nx/find-work/most-recent
https://electricbikereview.com/
https://meteofrance.com/
https://neizmennovkusno.edimdoma.ru/#/
> Vuex Detection Added

- src/drivers/webextension/images/icons/ipbase.svg
- src/technologies/i.json
https://ipbase.com/pricing/
https://www.tbo.com/
https://www.tender247.com/
https://tender247.net/
> Add ipbase / geolocation

- src/technologies/l.json
using `js: {}` object, detecting the Version of LottieFiles
> LottieFile Version Detection with JS Object

- src/technologies/_.json
- src/technologies/a.json
- src/technologies/b.json
- src/technologies/c.json
- src/technologies/d.json
- src/technologies/e.json
- src/technologies/f.json
- src/technologies/g.json
- src/technologies/h.json
- src/technologies/i.json
- src/technologies/j.json
- src/technologies/k.json
- src/technologies/l.json
- src/technologies/m.json
- src/technologies/n.json
- src/technologies/o.json
- src/technologies/p.json
- src/technologies/q.json
- src/technologies/r.json
- src/technologies/s.json
- src/technologies/t.json
- src/technologies/u.json
- src/technologies/v.json
- src/technologies/w.json
- src/technologies/x.json
- src/technologies/y.json
- src/technologies/z.json
Change http protocol to HTTPS in website links, eg. http://akamai.com to https://akamai.com
> fix: http protocol in websites should be https

- src/technologies/c.json
- src/technologies/s.json
> Update Stackbit, Cloudinary

- src/technologies/e.json
https://texteditoronline.pages.dev/
https://element.eleme.cn/
> Update Element UI / ui-frameworks #7652

- src/technologies/m.json
https://azure.microsoft.com/en-us/products/azure-maps/
https://github.com/
> Add Microsoft Azure Maps / geolocation,maps

- src/technologies/g.json
https://www.polargear.com/premium-medium-family-cool-bag.html
> Update Google Maps / maps

- src/technologies/p.json
https://www.pingdom.com/real-user-monitoring/
https://www.pingdom.com/product/uptime-monitoring/
https://www.pingdom.com/pricing/
https://status.zerossl.com/
https://status.zerossl.com/
> Add Pingdom Uptime Monitoring / issue-tracker, Update Pingdom RUM/ rum #7689

- src/technologies/a.json
**`Examples:`**
**for version Detection using:  __algolia.algoliasearch.version**:
- https://stripe.com/docs/api
- https://api.jquery.com/
- https://classic.yarnpkg.com/lang/en/
**using a[href]:**
- https://fontawesome.com/search
> Algolia Detection Improved & Version Detection added

- src/drivers/webextension/images/icons/Sirge.svg
- src/technologies/s.json
https://www.sirge.com/
https://www.gymsox.co/
https://www.greatnessthebook.com/
https://oakandeden.com/
> Add Sirge / analytics, shopify-apps

- src/technologies/l.json
> Update LogRocket / analytics

- src/technologies/y.json
https://restaurants.fiveguys.co.uk/scotland/12-frederick-st
https://locations.fazolis.com/search.html?q=
https://stores.madewell.com/
https://stores.anntaylor.com/
> Update Yext / search-engine,miscellaneous

- src/technologies/a.json
https://learn.microsoft.com/en-us/azure/cdn/cdn-overview
https://bethematch.org/ Not showing Ektron CMS (no traces, couldn't fix)
https://www.leroymerlin.es/
https://www.yaklass.ru/
https://www.wenxuecity.com/
Azure CDN and Azure Edge Network I'm not sure how  can set the category correctly
> Add Azure Edge Network / miscellaneous

- src/technologies/b.json
https://buywithprime.amazon.com/
https://bestketonetest.com/
https://www.shopchimney.com/
https://mapleholistics.com/collections/shampoo
https://www.magazinecafestore.com/collections/most-popular/products/house-and-garden-uk-magazine#
> Add Buy with Prime / miscellaneous

- src/technologies/y.json
https://www.outdoorvoices.com/
> Update Yotpo / loyalty, reviews

- src/technologies/w.json
https://www.webwizforums.com/
http://hanifdostlar.net/
http://rsvr.net/
https://demo.webwizforums.com/
https://pixeljoint.com/forum/
https://fromthelane.co.uk/
> Add Web Wiz Forums / message-boards

- src/technologies/p.json
https://www.bayer04.de/de-de/shop/product/handtuch-loewe/6102543
> Update Pimcore / cms,ecomm

- src/drivers/webextension/images/icons/Unas.svg
- src/technologies/u.json
https://unas.hu/webaruhaz-arak
https://www.onlinemarkaboltok.hu/
https://bioszallito.hu/
https://egumotors.hu/
https://elefani.eu/
https://www.emonamall.com/
https://tapetaposzter.hu/
https://lumenet.hu/
https://www.220volt.hu/
https://topjatekbolt.hu/
> Add Unas / ecommerce

- src/technologies/c.json
https://www.vitaminexpress.org/en/ultra-b-complex-vitamin-b-capsules
> Update commercetools / ecommerce

- src/technologies/w.json
https://china.nba.cn/
https://misakanetwork.top/#/login
> Update WebAssembly / pl

- src/technologies/u.json
https://www.ubbcentral.com/purchase.php
https://ubbdev.com/forums/ubbthreads.php/forum_summary.html
https://board.moparts.org/ubbthreads/ubbthreads.php
https://clubsi.com/
> Add Ultimate Bulletin Board / message-boards

- src/technologies/t.json
made changes in Taboola detection
> taboola json changes

- src/drivers/webextension/images/icons/Apache APISIX.svg
- src/technologies/a.json
https://apisix.apache.org/
http://www.rongcloud.cn/
https://www.bl.com/
http://aicdn.com/
http://www.xbyx.cn
https://www.shein.com.hk/
https://my.shein.com/
https://jp.shein.com/
> Add Apache APISIX / web-servers

- src/technologies/f.json
https://elpais.com/
https://www.ceneo.pl
https://regalo.club/
> Update Firebase / development

- src/technologies/a.json
https://website999.org/
https://shiftingpackersandmovers.in/
https://ksassociatesandresearchers.co.in/
https://hellopro.ae/
https://clickfirst.in/
https://rgtutorial.in/
https://arabtalk.in/
https://peiultrasonic.co.in/
https://pasplindia.co.in/
https://phoenix-infotech.in/
> Add AbhiCMS / cms

- src/technologies/m.json
> Update Mantine / ui-frameworks #7756 

- src/technologies/c.json
"ClickOnce is a deployment technology that enables you to create self-updating Windows-based applications that can be installed and run with minimal user interaction." (source: https://learn.microsoft.com/en-us/visualstudio/deployment/clickonce-security-and-deployment?view=vs-2022)
Google dork: `"Publisher" "Version" "ClickOnce and .NET Framework Resources"`
> Added technology: Microsoft .NET ClickOnce

- src/drivers/webextension/images/icons/Moat.svg
- src/technologies/m.json
- src/technologies/o.json
Moat is still alive, but was acquired by Oracle long ago
> Moat update

- src/technologies/o.json
https://omeka.org/
`footer > p > a[href*='//omeka.org']`
https://digital.nlb.by/
`link[rel*='stylesheet'][href*='/omeka/plugins/'],`
http://scarc.library.oregonstate.edu/omeka/exhibits/show/fighters
`link[rel*='stylesheet'][href*='css/myomeka.css'],`
http://gothicpast.com/
https://crtlibrary.cbt.org/
https://claude-dityvon.fr/
> Update Omeka / cms

- src/technologies/i.json
- Add x-cdn header
- Add CDN category
- Add product description
> Update Imperva detection

- src/drivers/webextension/images/icons/Beehiiv.svg
- src/technologies/b.json
https://www.beehiiv.com
blog
https://www.tuganapollo.com/
rss feed
https://www.neowin.net/
https://milkroad.com/ethereum/
https://www.highinterestsavings.ca/
https://unraid.net/
> Add Beehiiv / blogs, Beehiiv RSS / feed-readers

- src/technologies/r.json
https://github.com/WebTales/rubedo
https://www.lanouvellerepublique.fr/
> Add Rubedo / cms

- src/technologies/l.json
https://loox.app/
https://www.gracehealthscrubs.com/
Not true
> Update Loox / reviews(remove implies Shopify)

- src/drivers/webextension/images/icons/Forethought Solve.svg
- src/technologies/f.json
https://forethought.ai/platform/solve/
https://cosori.com/
> Add Forethought Solve / widget

- src/technologies/p.json
Example site
* https://www.immigration.govt.nz
> More detections for Plone.

- src/technologies/u.json
Example site
* https://www.boprc.govt.nz
> More detections for Umbraco.

- src/technologies/k.json
- src/technologies/m.json
I noticed all my PRs were failing. This is to get the green tick back. Problem introduced in https://github.com/wappalyzer/wappalyzer/commit/424717c115b094a73d6abc4150aa1dc1ffc712b9
All other PRs will need to be rebased with this commit, after this is merged.
> Move Monetate to the M technology section, in the hopes of passing CI.

- src/technologies/e.json
- src/technologies/i.json
Merged Ez Platform and  Ibexa DXP
https://ezplatform.com/ - > https://www.ibexa.co
leave eZ Publish has a link to the github and apparently differs from the platform
> Update Ibexa / cms

- src/technologies/g.json
https://glassix.co.il/
https://www.harel-group.co.il/
https://freetv.tv/
https://myexponet.com/
> Add Glassix / live-chat #7819

- src/technologies/i.json
- src/technologies/t.json
https://www.inforu.co.il/
https://www.creditguard.co.il/
https://www.marvihim.co.il/chatbot/taxrefund
> Add InforUMobile / live-chat #7858

- src/technologies/m.json
> Update Mautic / marketing-automation

- src/technologies/s.json
bug fixed with incorrect detection
https://v2.nuxt.com/
bug with version, removed version detection, excludes Shopify 
https://7mesh.com/
replace html  to dom 
replace html  to dom , update desc to neutral
> Update Swell, SweetAlert, SweetAlert2

- src/technologies/a.json
https://blogengine.ru/
https://bolknote.ru/
https://ilyabirman.ru/
https://otaku.ru/
http://antushin.ru/
> Update Aegea / blogs

- src/drivers/webextension/images/icons/Hashtag Labs.svg
- src/technologies/h.json
https://hashtag-labs.com/
https://www.mercurynews.com/
https://www.thewrap.com/
https://gothamist.com/
https://www.atlasobscura.com/
> Add Hashtag Labs / advertising

- src/technologies/c.json
https://www.iheartwunderwerkz.com/about
> Update Contentful / cms

- src/technologies/r.json
https://www.radix-ui.com/
https://ui.shadcn.com/
> Fix Radix UI detection

- src/technologies/i.json
https://github.com/posativ/isso/
https://neverpanic.de/blog/2014/03/19/downloading-google-web-fonts-for-local-hosting/
> Add Isso / comment-systems

- src/drivers/webextension/images/icons/Visual Portfolio.svg
- src/technologies/v.json
just picked up more popular than requested
https://visualportfolio.co/pricing/
https://almasalah.com/
https://sinop.edu.tr/
https://millonarios.com.co/
http://anadona.com.br/
> Add Visual Portfolio / wp-plugin

- src/technologies/j.json
- src/technologies/s.json
https://huangxuan.me/
https://www.gerritcodereview.com/
https://wiki.lineageos.org/
> Update Jekyll / ssg

- src/drivers/webextension/images/icons/Assertive Yield.svg
- src/technologies/a.json
https://www.assertiveyield.com/pricing/
https://www.loansocieties.com/
https://www.dailybreak.co/
https://www.soo-healthy.com/
https://www.soolide.com/
> Add Assertive Yield / advertising

- src/technologies/s.json
https://www.solohub.net/
https://www.penpow.dev/
> Update SvelteKit / ui-frameworks

- src/technologies/h.json
Balance the single quotes in the pattern
> Fix htlbid entry

- src/technologies/n.json
I've added pricing information for Netlify according to their pricing page at: [https://www.netlify.com/pricing/](https://www.netlify.com/pricing/)
> Add pricing information for Netlify

- src/technologies/s.json
ex)
https://turingapple.com
(This site using Swiper but not detected)
> Improve Swiper Detection
