wappalyzer/wappalyzer

share/apps.json

Detected 9 additional websites in a list top 25 [websites using bootstrap](http://expo.getbootstrap.com/).

Improved detection for Bootstrap

---

.gitignore
drivers/npm/.gitignore
drivers/npm/README.md
drivers/npm/check.js
drivers/npm/index.js
drivers/npm/package.json
drivers/npm/test/test.js
links.cmd
links.sh

https://www.npmjs.org/package/wappalyzer

added wappalyzer npm module

---

share/apps.json

See the discussion here: https://github.com/ElbertF/Wappalyzer/pull/781#issuecomment-72619339

Lower RxJS env pattern confidence

---

share/apps.json

Detect Google PageSpeed on Nginx

---

src/apps.json

Fix escape errors

---

src/drivers/phantomjs/driver.js

Sometimes 9000 ms isn't enough

Add --resource-timeout argument

---

src/apps.json

These regexes are not compatible with PCRE based libraries

Fix regex compatibility issues with PCRE

---

src/drivers/npm/index.js
src/drivers/npm/package.json
src/drivers/npm/test/sample.headers.json
src/drivers/npm/test/sample.html
src/drivers/npm/test/test.js

First off, awesome lib ! Wanted to call this directly from one of our NodeJS workers but we already have the request data so wanted a way to just pass that data in. Then saw the #detectFromHTML method that was still stubbed, so added in logic for the method and kept the names.
Also tried to clean up a little bit and make it all happen through one function.
Checked tests and added in a test to check the new method. Using HTML and headers I got from the site that is currently configured to be used for testing - http://codelanka.github.io/Presentation-Engines
Let me know if I missed something.

NPM driver detect from html

---

src/apps.json

Changed with this commit: https://github.com/getgrav/grav/commit/b2cd4db3955871715ca759f288a885ed44d57b2e

Update Grav generator

---

src/apps.json

wrong detect here http://lenyo.com.ua/weddings/vasil-ta-karina
by `<script src="http://lenyo.com.ua/wp-content/themes/lenyo/js/lenyo.js"></script>`
@AliasIO review plz

fix Enyo (js framework)

---

bin/wappalyzer-validate-regex

Surprised you weren't doing this already. I will also do a pull request for the error I've found.

Check if patterns are valid regular expressions by creating a new RegExp object for each of them

---

src/apps.json

Fixed RainLoop regular expression

---

src/apps.json

Fixes false positive identifying Livefyre due to generic LF env variable.

Fixes #690

---

src/apps.json
src/icons/Captch Me.svg

Added Captch Me

---

src/apps.json
src/icons/Shoptet.svg

Add Shoptet

---

src/apps.json

Updated regex and headers strings for Arastta

---

src/apps.json

Updated Thelia specification

---

src/apps.json

Next try of the pinguin-broken PR https://github.com/AliasIO/Wappalyzer/pull/1002

Add HTTP/2 and distinguish it from SPDY

---

src/apps.json

"anchorCache": {
"cats": [
23
],
"headers": {
"X-anchor-Cache": ""
},
"icon": "anchorCache.png",
"implies": "PHP",
"website": "anchorcache.eu"
},

anchorCache

---

src/apps.json
src/icons/Angular.svg

[Angular Material](https://material.angularjs.org/) provides a set of reusable, well-tested, and accessible UI components based on Material Design.
_Note: Reusing the 'icon/AngularJS.png' since there is no specific icon for Angular Material._

Adding 'Angular Material' to app.json

---

src/apps.json

Update swfobject Website

---

src/apps.json

Previous url is broken. Now i fixed with new url

Fix ubuntu server url

---

src/apps.json

Fix RxJS URL

---

src/apps.json
src/icons/ExagonConcept.svg

Hi,
This is an adding for "Exagon Concept" website builder : [www.exagon-concept.com](https://www.exagon-concept.com/)
Best regards,

Added Exagon Concept service

---

README.md

The verb ("is") is missing in the sentence.

Added a missing verb

---

src/apps.json

Prestashop detection without meta generator or "powered by"

Prestashop detection

---

src/apps.json
src/icons/pimcore.svg

Detection for http://pimcore.org

Added support for Pimcore

---

src/apps.json

Hello,
My previous pull-request was accepted, but the commit was skipped after, so it's the same functionality in a new commit. The icon already exists.

Add Strapdown.js

---

src/apps.json

#1165 dissapeared for some reason in commit https://github.com/AliasIO/Wappalyzer/commit/3a26550dbb23f885f70d6b7518b547f12f350592

Brought back pull request #1165

---

src/apps.json
src/icons/infusionsoft.svg

First time committing an app, so let me know if I did it correctly. If not happy to make edits!

add app: infusionsoft

---

src/apps.json
src/icons/kibana.svg

This can be tested on the [demo](http://demo.elastic.co/packetbeat) page of Kibana

Add detection of Kibana

---

src/apps.json

Especially given how precise the matching rules are.

Confidence of 99% or 90% can be considered as sure.

---

src/apps.json

Damn, Github closed my original PR #1344 after my changes. Here is it again.

Improved Nette Framework detection

---

src/apps.json

- the "description" meta is now used
- some html too
- some script src

Improve a bit Synology detection

---

src/apps.json

This can be tested on [this](http://gitlist-khornberg.rhcloud.com/) website.

Add gitlist detection

---

src/apps.json

This commit can be tested on [this](http://git.kali.org/gitweb/?p=packages/cisco-auditing-tool.git;a=summary) website.

Improve gitweb detection

---

src/apps.json

This can be tested on [this](http://fle.groupe-esa.com/login/index.php)
website

Improve a bit Moodle detection

---

src/apps.json

- Some implies were used as array, with a single member, then are now
strings
- Add some missing implies

Simplification and improvements of various "implies".

---

src/apps.json

This can be tested on [this](http://source.gitphp.org/) website.

Add GitPHP detection

---

src/apps.json
src/icons/Comandia.svg

Test URLs: 
- [demo.mycomandia.com](http://demo.mycomandia.com/)
- [www.comandia.com](https://www.comandia.com/)

Added Comandia detection

---

src/apps.json

Adding the new tag version for AT Internet tracking (SmartTag)

AT Internet last tag detection

---

src/apps.json

This can be tested on [this repo](https://0xacab.org/mat/).

Improve gitlab detection

---

src/apps.json
src/icons/gerrit.svg

This can be tested [here](http://gerrit.rockbox.org)

Add gerrit detection

---

src/apps.json

This can be tested [here](https://android.googlesource.com/platform/packages/apps/PackageInstaller)

Add detection for Gitiles

---

src/apps.json

This can be tested [here](https://git.drk.sc/dijit/interview_questions#-network-questions)

Improve a bit gitlab detection

---

src/apps.json

This can be tested [here](https://downloads.haskell.org/~ghc/latest/docs/html/libraries/) or [here](https://hackage.haskell.org/package/lens-4.15.1/docs/Control-Lens-Operators.html)

Add haddock detection

---

src/apps.json

Testable here
https://ticketsgb.ripleys.com/gatlinburg/
https://tickets.ripleys.com/branson/ItemShow.aspx

Improve env detection for Google Tag Manager

---

src/apps.json

This can be tested [here](https://tails.boum.org/ikiwiki.cgi?P=slides)

Improve a bit ikiwiki detection

---

src/drivers/bookmarklet/driver.js
src/drivers/chrome/js/i18n.js
src/drivers/chrome/js/inject.js
src/drivers/chrome/js/popup.js
src/drivers/firefox/data/js/panel.js
src/drivers/firefox/data/js/tab.js
src/drivers/phantomjs/driver.js

From the static analysis, fixed some of the variables that were not properly declared.
https://scrutinizer-ci.com/g/jvoisin/Wappalyzer/issues/master?selectedLabels%5B0%5D=9&selectedSeverities%5B0%5D=10&orderField=path&order=asc&honorSelectedPaths=0

Fix declaration of some variables

---

src/apps.json

This can be tested [here](http://Dellasboutiquehotel.com), [there](http://andian.ru/), [therein](http://madlab.ca), [there](http://andian.ru).
[Hundreds](https://publicwww.com/websites/%22generator%5C%22+content%3D%5C%22MODx%22/) of them.

Improve MODX detection by parsing meta generator

---

src/apps.json

Fix category of PNP-Nuke

---

src/drivers/chrome/js/driver.js
src/drivers/chrome/js/options.js
src/drivers/firefox/data/js/tab.js
src/drivers/webextension/js/driver.js
src/drivers/webextension/js/iframe.js
src/wappalyzer.js

- Some functions didn't return anything
- Some `for…in` related variables weren't declared
- Some variables were unused
This is related to #1425.

Fix various warnings found by scrutinity

---

src/apps.json

Add detection method via Header

Improve detection for Dotclear

---

src/apps.json

Add another pattern to detect Tealium based on feedback from @tibu 
https://github.com/AliasIO/Wappalyzer/commit/9daeb2642cddc031575b333dda739bb009669bbf

Add another pattern to detect Tealium

---

src/apps.json

This can best tested [here]( http://gerrit.rockbox.org/r/#/q/status:open )

Add gerrit version fingerprinting

---

src/apps.json

Lower false-positives ford3js

---

src/apps.json

This can be tested on [this](https://www.kaviari.fr/fr/) website.

Improve a bit the detection of prestashop

---

src/apps.json

Fix false positive script detection of Reveal.js

---

src/drivers/phantomjs/driver.js

it hangs if not apps detected or can't detects apps.
e.g. for youtube.com

Fix not answering any response if no apps detected

---

bin/wappalyzer-validate-icons
schema.json
src/apps.json
src/drivers/bookmarklet/driver.js
src/drivers/phantomjs/driver.js
src/drivers/webextension/js/driver.js
src/drivers/webextension/js/popup.js

Icon defaults to `default.svg` as requested in #1361. This means icon is optional in `apps.json`.

Default icon

---

src/apps.json

Delete \b in enyo\\.js

---

src/apps.json

adding shapecss, for detail, please check https://shapecss.com

adding shapecss

---

src/apps.json

updating shapecss

---

src/apps.json

Related to https://github.com/AliasIO/Wappalyzer/pull/1535

Add "excludes": "SweetAlert" to SweetAlert2 configuration

---

src/apps.json

added Virtuoso detection, as requested in #1516

added Virtuoso detection

---

src/apps.json

added RDF/SPARQL languages, for capturing dependencies in sites exposing SPARQL endpoints or JSON-LD API

added RDF/SPARQL languages

---

src/apps.json
src/icons/Luigisbox.svg

Hello maintainer,
This PR is adding Luigi's Box into the pool of applications detectable by Wappalyzer. 
Luigi’s Box is an analytical too revealing all important information about search & navigation on a site equipped with site-search feature. It is mostly useful for e-merchants.
Its website is: https://www.luigisbox.com/
Websites to test for Luigi's Box presence: www.muziker.sk, www.o2.sk, www.zlavadna.sk
Thank your for taking care of Wappalyzer!
BR,
Michal Barla

Add Luigi’s Box application.

---

src/apps.json

Many frameworks use that pattern for their grid system.
https://github.com/AliasIO/Wappalyzer/issues/1589

Fix false positive in Twitter Bootstrap

---

src/apps.json

Adds `uk-container` and `uk-section` to detection.
_Also update website link to https_

add class detection to UIkit

---

src/apps.json
src/icons/uCoz.svg

Sites to test:
- [1](http://torrent-games.net)
- [2](http://n-torrents.ru/)

Add uCoz detection

---

src/apps.json

Use array of strings for "cats" for uCoz

Use array of strings for "cats"

---

src/apps.json

1. Added Generator Meta
2. Added two cookies (.Nop.Customer and Nop.customer)

Improvement for detecting nopCommerce

---

src/drivers/bookmarklet/driver.js

This will close https://github.com/AliasIO/Wappalyzer/issues/1650

Fix bookmarklet driver

---

src/apps.json

This will close https://github.com/AliasIO/Wappalyzer/issues/1715

Fix Wix detection

---

src/apps.json

Library for browser fingerprinting.
Gave it the category "JavaScript frameworks", but maybe "Miscellaneous" would be better.

Add Fingerprintjs

---

src/apps.json

This can be tested [here](https://forum.pfsense.org/) or [here](https://forums.planetvampire.com/bloodlines-tech-support/).

Implement version detection for SMF

---

src/apps.json

Sites to test:
- https://www.lua.org/
- http://www.ccqha.org/

Improve Cherokee detection

---

src/apps.json

This can be verified on the official website: impresscms.org

Fix a typo on ImpressCMS matching

---

src/apps.json

Sorry, I don't have a publicly exposed version to provide a showcase,
but here is the relevant snippet:
```html
/></span></span><a href="/projects/IN" title="CLIENT" data-project-id="1">CLIENT</a></span><span class="repository-name"><a href="/projects/IN/repos/testjenk/browse" data-repository-id="2">testJenk</a></span></td></tr></tbody></table></section></div></div></section><footer id="footer" role="contentinfo"><section class="notifications"></section><section class="footer-body"><ul><li data-key="footer.license.free.eval">Git repository management powered by a free <a href="http://www.atlassian.com/software/bitbucket/">Atlassian Bitbucket</a> evaluation license</li></ul><ul><li>Atlassian Bitbucket <span title="9d5666b3b525f078f32c5b9a9c9a75f382c5269c" id="product-version" …
```

Add a way to fingerprint bitbucket version.

---

src/apps.json

Fix Now false positves

---

src/apps.json

- Prepend `^` when possible
- Append `$` when possible
Those changes have been tested on official websites of changed
technologies.

Improve a bit some regexp

---

src/drivers/bookmarklet/driver.js
src/drivers/npm/driver.js
src/drivers/webextension/js/content.js
src/drivers/webextension/js/driver.js
src/wappalyzer.js

Enable multiple headers with the same name & Get scripts via DOM

---

src/apps.json

apps.json got broken in 8a166daa9

Fix invalid JSON

---

src/apps.json

This can be tested [here](view-source:https://www.undiz.com/en/home)

Improve a bit the demandware detection

---

src/apps.json

This can be tested [here](https://charliehebdo.fr/)

Add a way to get woocommerce version

---

src/apps.json

As you can see in the TravisCI output, I did not escape a few periods because I wasn't sure if they were intentional or not. (And for a couple of patterns, I was sure the period was meant not to be escaped.)

Escape periods in various regexes

---

src/apps.json

Fixes the incorrect formatting to a consistent formatting.

Fix inconsistent formatting

---

src/apps.json

This can be checked [here](http://www.sxcurity.pro/2017/11/27/tricky-CORS/)

Improve fastly detection

---

src/apps.json

- Factorize a bit the regexp
- Add a new pattern that can be tested [here](https://www.iittala.com/se/sv/home)
- Change the url to https

Improve a bit hybris detection

---

src/apps.json

This can be tested [here](https://www.mutac.com/)

Improve a bit ezPublish detection via cookies

---

src/apps.json

This can bes tested [here](http://www.sphinx-doc.org/en/stable/) and [here](https://clang.llvm.org/docs/AddressSanitizer.html)

Add a way to get Sphinx' version

---

src/apps.json

Sample : ``` <link href="bootstrap.min.css" rel="stylesheet"> ```

Fix bootstrap detection

---

src/apps.json

This can be tested [here](https://about.mattermost.com/blog/)

Add a way to get Yoast SEO version

---

src/apps.json

This can be tested on [cryptonator](https://www.cryptonator.com/rates/XMR-EUR)

Add a way to fingerprint raphael.js

---

src/apps.json

This can be tested [here](https://www.blackhoodie.re/archive/),
and on any Jekyll blog that you might encounter

Add a way to detect Jekyll via html

---

src/drivers/webextension/_locales/tr/messages.json

-fix typo on `categoryName23`
-added `categoryName55` localization

update turkish locale

---

src/apps.json

This can be tested [here](https://paranoidbeavers.ca)

Add a way to get modernizr version

---

src/apps.json

change to ENV check with unique variable because javascript script is included via async ways and not recognized

Update recognition with simplified script and env

---

src/apps.json

Fix broken Sphinx version detection

---

src/apps.json

This can be tested [here](japaneseruleof7.com/poverty-in-japan/).
A lot of people are using this script because they are too lazy to update to the latest version of jquery.

Add detection for jquery-migrate

---

src/apps.json

This can be tested [here](https://www.winamax.fr/cgu-paris-sportifs)

Add version detection for requirejs

---

src/apps.json
src/icons/docsify.svg

Hi there,
I am a creator of [docsify](//github.com/qingwei-li/docsify), It is a document generation tool like Gitbook. Currently many open source projects are using docsify to develop document site, here are some [examples](https://github.com/QingWei-Li/docsify#showcase).
I want to add it to Wappalyzer.
Thanks

Add docsify detection

---

src/apps.json

This can be verified [here](https://docs.angr.io/HACKING.html)

Tighten a bit the regexp for gitbook's detection

---

src/drivers/webextension/html/options.html

Also formatted the code with VS Code, that's why the diff looks so weird.

Fixed not working URLs in the webextension options

---

src/apps.json

This can be tested here : http://www.vaynahi.com/ and here : http://sharedthis.com/

Improve coinhave detection

---

src/apps.json

Webite cloudcoins.co is down and i didn't find the icon :/

Add Cloudcoins detection

---

src/drivers/webextension/js/driver.js
src/drivers/webextension/js/popup.js

Remove the last pieces of edge code. (I hope so at least)

Remove edge code

---

src/apps.json

This can be tested [here](https://blog.hboeck.de)

Add an other way to get Serendipity's version

---

src/apps.json

Can be tested here : http://www.dvd-covers.org/
#1972

Fix Gallery regex to avoid FP

---

src/apps.json

If these `\`s aren’t escaped property, they will be discarded when the JSON is decoded.

Escaped a bunch of \'s

---

schema.json
src/apps.json

With this PR auto completion in the apps.json is possible, when the editor supports it:

added editor schema.json inline support e.g. VS Code, Atom etc.

---

src/apps.json

What do you think about those changes ?
Are some priorities too high or too low ?
#1984

Change priorities

---

src/apps.json

This can be tested [here](store.steampowered.com/sale/devolverdonequick/)

Improve a bit the detection of scriptaculous

---

src/apps.json

This can be tested [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1419581)

Vastly improve Bugzilla detection

---

src/apps.json

Improve a bit hybris detection

Improve hybris detection

---

src/apps.json

Added watcher for data-v in html elements, now successfully detects Vue.js even if bundled with webpack

Improve Vue.js detection

---

src/apps.json

This can be tested here : https://www.redmineup.com/ and here : https://www.b2brouter.net/fr/

Add an other way to identify redmine

---

src/apps.json

Normalize a bit the implies

---

src/drivers/webextension/_locales/ro/messages.json

fix categoryPin Romanian translation

categoryPin Romanian translation

---

src/apps.json
src/icons/Kajabi.svg

Adds the detection of [Kajabi](https://newkajabi.com/).
https://twitter.com/kajabi
https://www.facebook.com/kajabi
For testing:  
https://www.3dfordesigners.com

Add Kajabi.

---

src/apps.json

Adds the html detection for Squarespace

Squarespace: Adds html detection (fix #2026)

---

src/apps.json

This can be verified [here](https://www.spip.net/en_rubrique25.html)

Add a way to get modernizr version via "js"

---

src/apps.json

This can be tested [here](https://hackmd.io/EwQwDARmBmDGCcBaAjAU1sxAWA7Ox880wiOAJgMyw4ywXSpZA===)

Add a way to get lodash's version

---

src/apps.json

This can be tested [here](https://hackmd.io/EwQwDARmBmDGCcBaAjAU1sxAWA7Ox880wiOAJgMyw4ywXSpZA===)

Add a way to get raphael's version

---

src/apps.json

This can be tested [here](https://vuejs.org/v2/guide/)

Add a way to get vue.js version

---

src/apps.json

This can be verified [here](https://revolt.group/)

Add a way to get Prototype's version

---

src/apps.json

This can be verified [here](https://revolt.group/)

Add a way to get scriptaculous version

---

src/apps.json

This can be tested [here](http://linuxmao.org/open%20stage%20control)

Add a way to get jqueryui version

---

src/apps.json

This can be tested [here](https://www.grsecurity.net/support.php)

Add Flickity

---

src/apps.json

This can be tested [here](https://bugs.launchpad.net/ubuntu/+source/unbound/+bug/1732150)

Add a way to get YUI version

---

src/apps.json

This can be tested [here](https://readthedocs.org/)

Add a way to get typekit's version

---

src/apps.json

This can be tested [here](http://159.89.252.33/torrents.php) and [here](https://empornium.sx)
This should close #2047

Add a way to detect Gazelle

---

src/apps.json

Change webpack's category

---

src/wappalyzer.js

in analyzeMeta function the r const is declared but never used and in next if is the same code.

fix analyzeMeta duplicate line

---

src/apps.json

Add a category for static site generators

---

src/apps.json

This can be tested [here](https://www.youtube.com/watch?v=-8cOWt7lvUQ)

Add a way to get polymer's version

---

src/apps.json

This can be tested [here](http://shamelessmag.com/blog/entry/adversary-making-a-statement-in-the-industrial-mu/)

Tighten a bit the ExpressionEngine regexp

---

src/apps.json

This can be tested [here](https://leaverou.github.io/awesomplete/) or [here](https://links.imirhil.fr/)
The library is [pretty popular](https://github.com/LeaVerou/awesomplete), with almost 6000 stars

Add awesomplete

---

src/apps.json

This can be tested [here](https://rougie.fr/)

Add a way to get requirejs version

---

src/apps.json

This can be tested [here](https://www.kravmagaparis12.com/)

Add a way to get tweenmax's version

---

src/apps.json

Example sites which are using React:
- Slack
- Dropbox
- Imgur
On all it works fine with PascalCase "React".

React: Fixed version detection

---

issue_template.md

Helps users to format their bug reports/features request/...
Based on an idea of @Yoginth.

Add guidelines when opening an issue

---

src/apps.json

This can be checked [here](http://pwning.fun/) and [here](https://vincentgarreau.com/particles.js/).
It has ~14.000 stars in github, and is used on a metric fuckton of websites
who want a fancy background. Unfortunately, it doesn't have an icon yet.

Add particles.js detection

---

src/apps.json

- Add a `script` pattern
- Add a way to get the major version
This can be tested [here](https://www.mediapart.fr/journal/france/080318/mandelieu-un-promoteur-vendeur-d-armes-en-affaire-avec-la-famille-du-maire)

Improve a bit tinymce detection

---

src/apps.json

This can be tested [here](https://git.libskia.so)

Improve a bit clipboards.js detection

---

src/apps.json

- Simplify the regexps
- Add a way to detect the version
- Remove the `ui` pattern, since it was triggering a lot of false-positives
- http -> https
This can be checked [here](https://git.libskia.so/)

Improve semantic-ui detection

---

src/apps.json

This is based on [its documentation](https://www.coinimp.com/documentation/reference#Client.Anonymous )

Improve a bit the coinimp detection

---

src/apps.json

Based on [this article](https://badpackets.net/how-to-find-cryptojacking-malware/)

Improve a bit the cryptoloot detection

---

src/apps.json

- Improve the `script` thingy
- http -> https

Improve a bit firebase detection

---

src/apps.json

This can be tested [here](https://google.github.io/xi-editor/gsoc.html)

Improve Material Lite detection

---

src/apps.json
src/drivers/webextension/js/content.js

Fix #2140, see the issue to have a detailed explanation.
- Remove dangerous scripts patterns
- Avoid to match against plain JavaScript in the js field

Fix performance issue

---

src/apps.json

- Fix 2 scripts pattern
- Convert the last "env" pattern to the js format

Fix typos apps.json

---

src/apps.json

This can be tested on gitlab's website

Improve a bit the gitlab detection

---

src/apps.json

This can be tested [here](https://boutique.orange.fr/internet/offres-fibre/resultat-eligibilite)

Add a way to get Wink's version

---

src/apps.json

This can be tested [here](http://umap.openstreetmap.fr/en/)

Add a way to get leaflet's version

---

src/apps.json

This can be tested [here](http://www.slate.com/articles/news_and_politics/crime/2013/12/gun_ownership_causes_higher_suicide_rates_study_shows.html)

Improve a bit quantserve detection

---

src/apps.json

This can be tested [here](blog.lekkertech.net/blog/2018/03/07/iota-signatures/)

Improve a bit octopress detection

---

src/apps.json

This can be tested [here](blog.lekkertech.net/blog/2018/03/07/iota-signatures/).
This scheme is used on a lot of blogs.

Improve a bit disqus detection

---

src/apps.json

Example site where you can test: [superkorb.com](superkorb.com)

Fingerprint.js: added version detection

---

src/apps.json

This can be checked [here](http://www.lentrepot.fr/)

Improve the way we get SPIP version

---

src/apps.json

This can be tested [here](http://spacemacs.org/).
No icons :/

Implement Slick detection

---

src/apps.json

They were doing a lot of noise with the extension on a lot of websites.
+ Improve Select2 detection

Remove low confidence pattern js

---

src/apps.json

This can be tested [here](http://tengine.taobao.org/)

Fix a typo in ParticlesJS detection

---

src/apps.json

Title says everything :)
Example site on which you can test: https://www.amazon.com/M-Audio-AV32-1-Professional-Multimedia-Audio-Monitor/dp/B017340ZVE

added underscore.js version detection

---

src/apps.json

This can be tested [here](https://en.wikipedia.org/wiki/Erlk%C3%B6nig_(Goethe))

Apparently, some sites are exposing their varnish version

---

src/apps.json

This can be verified [here](https://stackoverflow.com)

Fastly can be present in "Vary" header

---

src/apps.json

Causing false positives cf #2190

Remove Gitlab description pattern

---

src/apps.json

This can be checked [here](http://www.haka-security.org/)

Add a way to get zurb foundation version

---

src/apps.json

Example site on which you can test it: https://www.wappalyzer.com/technologies/webpack

Snap.svg: added version detection

---

src/apps.json

This can be tested [here](https://forum.wiwiland.net/index.php?/topic/50403-openmw/page__pid__748659__st__350#entry748659)

Detect IPB via cookies

---

src/apps.json

Fix MotoCMS pattern

---

src/apps.json

Yandex metrika alternative CDN 
https://w6p.ru/ZGZlNT.png

add Yandex Metrika alternate CDN

---

src/apps.json

This can be checked [here](http://blog.ralch.com/tutorial/golang-embedded-resources/)

Improve a bit Hugo detection

---

src/apps.json

Remove a Magento false-positive

---

src/apps.json

It's possible to get the version of jquery mobile with `jQuery.mobile.version`.

add version for jQuery Mobile

---

src/apps.json

[Sources](https://stackshare.io/medium/medium-com)

Medium is written in nodejs

---

src/apps.json

Improve a bit Wix detection

---

src/apps.json

Change Twemoji cat from JS Graphics to misc

---

src/apps.json

Those were tested on the top10 of every detection

Tighten a bit some `Server` regexp

---

src/apps.json

Contentful is using a new domain for asset hosting (`ctfassets.net`).

Add ctfassets.net to Contentful detection

---

src/apps.json

This can be tested [here](https://thebot.net/threads/python-3-function-annotations.363444/)

Improve XenForo detection

---

src/apps.json

This can be tested [here](https://jira.ez.no/browse/EZP-26582)

Fix Jira detection by unescaping a dot

---

src/apps.json

This can be tested [here](http://ci.rada.re/job/radare2/)

Improve jenkins detection

---

src/apps.json

Move PrestaShop from "excludes" to "implies"

Fix conflict by PrestaShop

---

src/apps.json

This can be tested [here](https://bugzilla.xfce.org/)

Add a way to get bugzilla's version

---

src/apps.json

As documented on [its website]( https://codex.wordpress.org/Using_Alternative_Databases )

Wordpress implies MySQL

---

src/apps.json

https://wordpress.org/plugins/post-and-page-builder/

Add BoldGrid Post and Page Builder

---

src/apps.json

This can be tested [here]( https://shoprabbindesbois.com/ )

Add a way to detect Laravel presence via js

---

src/apps.json

This can be verified in the [IOC published by Malwarebyte]( https://blog.malwarebytes.com/threat-analysis/2018/05/look-drupalgeddon-client-side-attacks/ ).

Improve coinhive detection

---

src/apps.json

This can be tested [here](https://ideas.lego.com/dashboard),
and can be found in the documentation of ckeditor.

Improve ckeditor detection via js

---

src/apps.json

This is a first batch, I might do more in the future

We're in 2018, websites should be in https

---

src/apps.json

This can be verified [here](https://snips.gitbook.io/)

Improve a bit gitbook.io detection

---

src/apps.json

This can be verified [here](http://ingest.tips/2015/07/19/tips-for-improving-performance-of-kafka-producer/)

Detect old version of yoast seo plugin

---

src/apps.json

This can be checked [here](https://www.fbi.gov/)

Improve a bit cloudflare detection

---

src/apps.json

This can be checked [here](https://blog.ghost.org/)

Improve a bit phusion passenger detection

---

src/apps.json

[source](https://en.wikipedia.org/wiki/Blogger_(service))

Blogger is written in Python

---

src/apps.json

[source](https://xenforo.com/xf2-docs/manual/install-upgrade/)

Xenforo implies MySQL and PHP

---

src/drivers/webextension/js/options.js

Bug report: #2325
The value was already correct in local storage but it was not change in <code>options</code> dictionnary in the driver.

Fix options page

---

src/apps.json

[source](http://doc.prestashop.com/display/PS17/What+you+need+to+get+started)

Prestashop only runs on MySQL

---

src/apps.json

This can be tested [here](https://ubuntuforums.org/archive/index.php/t-1813618.html)

Improve vbulletin detection via html

---

src/apps.json

Updated ByInti Recognition

---

src/apps.json

This can be verified [here](https://www.wappalyzer.com/datasets)
This should close #2399

Improve a bit recpatcha's detection

---

src/apps.json

- fix not match `<button type="button" class="ant-btn"`.
- add `drawer`

Update Ant Design detection regex

---

src/apps.json
src/icons/Brightspot.svg

https://www.aboutamazon.com/
https://corporate.walmart.com/
https://video.nationalgeographic.com/
https://www.sothebys.com/en/
https://www.specialolympics.org/
https://www.mybluprint.com/
https://www.sourcemedia.com/
https://www.jnj.com/
https://www.newellbrands.com/
http://www.hallmarkchannel.com/

Add Brightspot detection

---

src/apps.json

This can be tested [here]( https://www.hm.com/entrance.ahtml?orguri=%2F).

Fingerprint dynatrace via headers

---

src/apps.json

This can be checked [here](view-source:https://vue-hn.now.sh/top)

Improve a bit vue.js detection

---

src/apps.json

Minor Drupal improvements

---

src/apps.json

- the website is using https
- weebly is [written in php/mysql](https://www.quora.com/How-long-did-Weebly-take-to-build-and-what-languages-is-it-built-on)
- use some js object to detect it

Improve a bit weebly

---

src/apps.json

The free version of jimdo [uses subdomains](https://en.wikipedia.org/wiki/Jimdo#Service).

Detect jimdo via url

---

src/apps.json
src/icons/scrollreveal.svg

Repository: https://github.com/scrollreveal/scrollreveal

Add ScrollReveal

---

src/drivers/webextension/_locales/pt_BR/messages.json

Translated "categoryName58" and "categoryName59" new category entries.

[pt-BR] Translated new category entries.

---

src/apps.json

X-Fastcgi-Cache is [used by nginx](https://duckduckgo.com/?q=%22X-Fastcgi-Cache%22)

Improve a bit nginx detection

---

src/apps.json

Fix a typo

---

src/apps.json

This can be verified [here](https://bugs.documentfoundation.org/)

Improve bugzilla detection via cookies

---

src/apps.json

- Detect modernizr used/named like [this]( view-source:https://www.online.net/en/dedicated-cloud#scw-start )
- Factorize the two `script` regex

Improve modernizr detection

---

src/apps.json

This can be tested [here](https://thelion.ch/)

Improve a bit wordpress detection via headers

---

src/apps.json

This can be checked [here](https://hellfest.fr/)

Improve cloudflare detection

---

src/apps.json

This common pattern is present, for example [here](https://www.corben.io//advanced-cors-techniques/)

Detect font awesome version

---

src/apps.json

This can be verified [here](https://www.teeworlds.com/forum/viewtopic.php?id=12547)

PUNBB can now be detected via javascript

---

src/apps.json

It's a [fairly popular](https://github.com/defunkt/jquery-pjax) library, used by github.com

Add jquery-pjax detection

---

src/apps.json

This is a [pretty popular](https://github.com/ankane/ahoy)
analytics for RoR, used by [instacart](https://www.instacart.com) for example
Unfortunately, it doesn't have a logo :/

Add ahoy detection

---

src/apps.json

According to the [documentation](https://docs.bugsnag.com/platforms/browsers/v3/)

Improve a bit bugsnag detection

---

src/apps.json

Accordingly to the [documentation]( https://www.chartjs.org/docs/latest/charts/doughnut.html )

Improve Chartjs detection

---

src/apps.json

- There is no need to escape . or - outside of a []
- (?:-|.) can be replaced with [.-]
- Simplify some convoluted regexp

Remove some superfluous escaping

---

src/apps.json

For example:
https://reactjs.org/

Improve gatsby fingerprinting

---

src/apps.json

for example we can find : `<script src="/Scripts/tiny_mce/tiny_mce.js"></script>`

Improve tiny mce detection

---

src/apps.json

This can be checked here : view-source:https://wiki.php.net/todo/php73

Improve a bit dokuwiki detection

---

src/apps.json

This should give some performance boost, along
with a cleaner code.

Replace the .* pattern with something else when possible

---

src/wappalyzer.js

Currently we run the same regex on the html multiple times to extract meta fields. Let's extract the metas once, and run the extra, app specific regexes multiple times

Less meta regex

---

src/apps.json

This can be checked [here](http://www.gertrudhof.ch/index.php?id=1)

Improve a bit typo3 detection

---

src/apps.json

- Split the regexp
- Simplify some parts

Improve a bit the regexp for phpbb

---

src/apps.json

Remove typo string from apps.json

---

src/apps.json

Hi,
I want to add version to our CMS detection. Please check it.
Thank you so much!

Add Botble CMS version detection

---

src/apps.json

Better detection of Tealium. See https://regex101.com/r/3T16wo/1

Better detection of Tealium

---

src/apps.json

This can be tested [here](https://demo.cpanel.net:2083/)

Add cpanel detection via cookies

---

src/apps.json
src/icons/clarity.svg

Project Clarity is an open source design system that brings together UX guidelines, an HTML/CSS framework, and Angular components. It's been started and supported by VMware, and is used in the majority of their products.
https://clarity.design/
https://github.com/vmware/clarity (4500+ Stars)
https://www.npmjs.com/package/@clr/angular (tens of thousands of weekly downloads)

Add Clarity

---

src/apps.json
src/icons/Gridsome.svg

Gridsome a Vue powered static site generator. 
- [gridsome.org](https://gridsome.org/)
- [github.com/gridsome/gridsome](https://github.com/gridsome/gridsome)
- [www.staticgen.com/gridsome](https://www.staticgen.com/gridsome)

Adding Gridsome

---

src/apps.json
src/icons/tessitura.svg

Tessitura is a widely used CRM and ticketing management platform for museums, performing arts, zoos, and other cultural and art based institutions around the world. TN Express Web (TNEW) is their companion CMS solution that utilizes the Tessitura API for backend management.
- https://www.tessituranetwork.com
- https://tickets.bclm.com
- https://www.thesmithcenter.com
- https://www.mountvernon.org
- https://www.coloradoballet.org
- https://my.hampsteadtheatre.com
- https://www.alleytheatre.org

Add Tessitura / TNEW

---

src/apps.json
src/icons/syncfusion.svg

Syncfusion provides a wide variety of products in all web frameworks that help to develop feature-rich applications - https://www.syncfusion.com/javascript-ui-controls.
Some of the examples are as follows.
https://ej2.syncfusion.com/showcase/typescript/healthtracker/
https://ej2.syncfusion.com/demos/#/material/grid/grid-overview.html 
https://ej2.syncfusion.com/aspnetmvc/DashboardLayout/SEOAnalytics#/material
https://ej2.syncfusion.com/angular/demos/#/material/chart/spline-area
https://ej2.syncfusion.com/vue/demos/#/material/schedule/timeline-resource.html
https://ej2.syncfusion.com/react/demos/#/material/document-editor/default
https://ej2.syncfusion.com/aspnet-core-blazor/Viewer/CustomToolbar
https://ej2.syncfusion.com/aspnetcore/StockChart/HiloOpenClose#/material …

Request to add Syncfusion

---

src/apps.json

VTEX is the biggest e-commerce player in LATAM and we're adding more ways to identify our platform.

Add more cookies to identify VTEX

---

patches/zombie-vm-timeout.patch

Fix patch file against Zombie 6.1.2

---

src/icons/Nuxt.js.svg

using https://nuxtjs.org/logos/nuxt-square.svg now :relaxed:

chore: update Nuxt logo

---

src/apps.json

Better identification for Wix sites

Improved Wix identification

---

src/apps.json

Changed from script mode to JS function because of LiveHelp changes

Increased script recognition - LiveHelp

---

src/apps.json

Add detection for OpenBSD's httpd

---

src/apps.json

Check the [documentation](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4) for details.
This should close #2685

Improve fontawesome detection

---

src/apps.json

src https://github.com/getsentry/sentry-javascript/blob/8e08b297d3d28563ad80d9c2a671e59e2f78404f/packages/utils/src/logger.ts#L61

add npm @sentry/browser

---

src/drivers/webextension/css/popup.css

Add theme support for dark mode

---

src/apps.json
src/icons/Siteglide.svg

Hi! 👋
This PR is for our product of [Siteglide](https://www.siteglide.com)
Site examples:
- [Belgas](https://www.belgasfm.com/) 
- [CONXTD](https://www.conxtd.com)
- [FCIA](https://www.fcia.org.au/)
- [Life At Faith](https://www.lifeatfaith.tv)
- [Franklin County](https://www.franklincountytx.com/)
- [Future Pro Logistics](https://www.futureprologistics.com/)
- [Go Trego](https://www.gotrego.com/)
- [Green Park](https://www.green-park-martinique.fr/)
- [Haeger Engineering](https://www.haegerengineering.com/)
- [Harless & Associates](https://www.harlessandassociates.com/)
Some more examples in our [showcase](https://www.siteglide.com/showcase)
Thanks!

Add Siteglide

---

src/apps.json

Various ways to detect Symfony when it's running in debug mode

Improve Symfony detection

---

src/apps.json

Fixes https://github.com/AliasIO/Wappalyzer/issues/2841
(more may need to be done?)

Fix Backdrop CMS detected as both Drupal and Backdrop

---

src/apps.json

- Also fixed Netlify’s category, these are technically PaaS services.
- fixes #1909

Fix Github Pages Category

---

src/apps.json

https://github.com/shopware/platform/search?q=symfony&type=Commits

Shopware implies Symfony

---

src/apps.json

* FIX the first level domine of spreecommerce website

FIX spreecommerce domain

---

src/apps.json
src/icons/OrderOnline.svg

Currently [OrderOnline.id](https://orderonline.id) has more than 3500 users
Websites that using OrderOnline:
1. [https://hiradigital.com](https://hiradigital.com)
2. [https://rovanalfarry.orderonline.id/product-1](https://rovanalfarry.orderonline.id/product-1)
3. [http://olerashop.com/4-in-1-crayon](http://olerashop.com/4-in-1-crayon)
4. [https://priakeren.id/sepatu-slipon-sport/](https://priakeren.id/sepatu-slipon-sport/)
5. [https://crt.orderonline.id/BicyclePhoneHolder](https://crt.orderonline.id/BicyclePhoneHolder)
6. [https://maulanikma.orderonline.id/the-grammar-ebook](https://maulanikma.orderonline.id/the-grammar-ebook)
7. [https://perlengkapanbayi.orderonline.id/korset-postpartum-2](https://perlengkapanbayi.orderonline.id/korset-postpartum-2)
8. …

Add OrderOnline App

---

src/apps.json

Can be tested at https://demo.phpmyadmin.net/master-config/

Add version detection to phpMyAdmin

---

src/apps.json

Next.js has an official website

---

src/apps.json

Added CPEs for these apps:
* Ruby
* Ruby on Rails
* Wordpress
* jQuery
* jQuery UI
These were missed in commit 5dc6578b7f5b63772867218fb0e8b964ac1e2c39.

Add more CPEs

---

src/apps.json

Add a stable way to recognize Duda sites

Add a stable HTML identifier for Duda

---

src/apps.json

correct phpCMS

---

src/apps.json

Test sites: 
- https://www.shoeboxstore.com.br/
- https://www.vegalli.com.br/
- https://www.charlottelook.com.br/
- https://www.crizzapi.com.br/
- https://www.fabricadoouro.com.br/
- https://www.celulacompany.com/
- https://www.equivoco.com.br/
- https://www.lefah.com.br/
- https://www.baraoalpha.com.br/
- https://www.colaquiadesivos.com.br/

added Irroba

---

src/apps.json

The zone.js repo has been moved to angular mono repo.

Update zone.js website

---

src/apps.json

This updates the product name as displayed upon detection, as well as the generator name used as one of the detection methods.

Update Proximis product names and meta

---

src/apps.json

Having empty elements just results in unnecessary parsing or incorrect matching.
NivCMS was added in:
https://github.com/AliasIO/wappalyzer/pull/2995/files
Perhaps this is something that could be considered further to https://github.com/AliasIO/wappalyzer/issues/2896 (which mentions linting or unittesting version syntax, however, linting for json format either consistently including all elements or not including empty elements might be a good move too.)

NivCMS remove empty elements

---

src/apps.json

Fix for https://github.com/AliasIO/wappalyzer/issues/3012

Netlify new app domain adoption

---

src/apps.json

improved October CMS detection based on meta data

improved October CMS detection

---

src/apps.json

More recent versions of EPages add custom headers.

Add headers check for EPages

---

src/drivers/webextension/js/driver.js

Fix for first party isolation in Firefox

---

src/apps.json

Add Sotel platform as ac Software as a Service on the cloud for businesses.

Update apps.json - add sotel platform

---

src/apps.json
src/icons/nepso.svg

add nepso cms support , thanks

add nepso support

---

src/apps.json

Per recent CI runs, ex: https://travis-ci.org/github/AliasIO/wappalyzer/builds/692417278#L264-L320
There were two in this group that I didn't tackle:
```text
Suspicious period (".") in pattern. Should this have been escaped?
App: GeneXus
Pattern: script: .*/static/gxgral.js
Suspicious period (".") in pattern. Should this have been escaped?
App: GeneXus
Pattern: script: .*/static/gxtimezone.js
```
They appear to be valid periods, however is it really necessary to start a pattern with wildcard (`.*`)? If it isn't necessary I'd be glad to adjust them as well.
Edit: The GeneXus patterns were also fixed in the end, per additional comments.
When using the patterns in Java the following "illegal repetition" issues occur, because of unmatched curly braces. According to regex101.com escaping these …

Pattern tweaks

---

src/apps.json
src/drivers/webextension/images/icons/Pushnami.svg

Powering more than 20,000 global sites, Pushnami is the #1 push platform for marketers. With Pushnami’s browser-based push notifications, you can deliver your message through desktop and mobile browsers with ease.
**Used By**
- [https://trends.builtwith.com/widgets/Pushnami/United-States](https://trends.builtwith.com/widgets/Pushnami/United-States)

Adds Pushnami

---

src/drivers/webextension/js/content.js
src/drivers/webextension/js/driver.js
src/drivers/webextension/js/lib/iframe.js
src/drivers/webextension/js/options.js
src/drivers/webextension/js/popup.js
src/drivers/webextension/js/utils.js
src/wappalyzer.js

While looking into another issue, I found it difficult to parse functions and understand their purpose. One step in the right direction would be add JSDoc blocks to all functions and Object methods to help onboard new contributing developers improve overall readability.
- Focused on Wappalyzer and web extension
- iframe.js hasn’t been cleaned / formatted in awhile, so it looks like a lot of changes, but is just JSDoc blocks and formatting.

Add JSDoc blocks to all functions

---

src/apps.json

fec8087c056d67e6a80f378ba26b6a66663fa715 Update Sphinx website (fix #3189) and improve detection of version

Improve Sphinx Detection

---

src/apps.json

A few narrowed down versions of detection regexes.

Small regex fixes

---

src/apps.json

Add detection for https://github.com/sulu/web-js / https://www.npmjs.com/package/@sulu/web
Example website:
- https://sulu.rocks

Add detection for @sulu/web-js library

---

src/apps.json
src/drivers/webextension/images/icons/ForoshGostar.svg

Foroshgostar is an e-commerce platform here are some websites built with it:
maralcover.com
polishi.com
rasisco.com
shimashoes.com
forevershop.ir
forevergreen.ir
mpn101.com
arsina.net
sana3d.com
and this a link to Alexa rank page to have an estimation for its user base
https://www.alexa.com/siteinfo/foroshgostar.com

Added new application - Foroshgostar

---

src/drivers/webextension/images/icons/Pushnami.svg

Fixes Pushnami SVG icon so that it's able to be converted png without being cropped.

Fix Pushnami icon

---

src/apps.json

Reference: #2241 #2249
I added *Twemoji* to the *font scripts* category as I found *Font Awesome* there.

Add twemoji to font scripts

---

src/apps.json

Reference: https://github.com/AliasIO/wappalyzer/pull/3203#discussion_r459093442

Improve jsDelivr detection

---

src/apps.json

[**Semantic UI**](https://semantic-ui.com/)

Update Semantic UI name & implies

---

src/apps.json
src/drivers/webextension/images/icons/Jibres.svg

Integrated Ecommerce Platform Software
Online Store Website & Mobile Online Store & Social Marketing & POS Software
Accept Credit Cards. Fully Hosted. SEO Optimized. SSL Certificate. Fully API

Add Jibres Detection

---

src/apps.json

Optimizations for AppDynamics detection.

AppD Detection Optimizations

---

src/apps.json

- Added "x-styx-req-id" as additional header detection for Pantheon sites.

Update Pantheon header detection

---

src/apps.json

Add detection of Adobe Experience Platform ID Service, Adobe Analytics (fka SiteCatalyst), and Adobe Target

Add more Adobe Experience Platform technologies

---

src/apps.json

Improve 8a2383e47d74d8068ba82ab20c219ff4f6f7c5c3 of #3041

Improve CNZZ detection

---

src/technologies.json

Improve Sentry Detection

---

src/technologies.json

- fixes #3329
adding a new script detection for urls like `cdn.mxpnl.com/libs/mixpanel-'version'.min.js`

Add Mixpanel version detection

---

src/technologies.json

Improving Yandex.Metrika detection

---

src/drivers/npm/driver.js

https://github.com/AliasIO/wappalyzer/issues/3345

#3345: Close a timer after resolving/erroring the `Promise.race()`

---

src/technologies.json

Add jQuery DevBridge Autocomplete

---

src/technologies.json

Google Pay and Shop Pay Detection

---

src/technologies.json

The most appropriate category for Tealium is Tag managers because although its technology helps to integrate marketing solutions, it does not only integrate advertiser services but also analytics, cookie compliance, data management... In short, everything a tag manager does.

Update category ID for Tealium

---

src/technologies.json

Improving Google Analytics detection

---

src/technologies.json

Improving Firebase detection

---

src/technologies.json

Improving Facebook detection

---

src/technologies.json

Requested #3382
Adding detection for css files:
- tailwindcss@version/dist/tailwind.min.css
- tailwindcss/version/base.css
- tailwindcss/version/components.css
- tailwindcss/version/utilities.css
Example site:
- https://tailwindtoolbox.github.io/Minimalist-Blog/

Improving tailwindcss Detection

---

src/technologies.json

Examplesite: 
- https://iworkedon.com/
Script:
- googletagmanager.com/gtag/js

Improving Google Tag Manager Detection

---

src/technologies.json

Examplesite: 
- www.doordash.com/en-US
Detection Script:
- maps.google.com/maps/api/js

Improving gmaps detection

---

src/technologies.json

Apologies with this typo and add! Much thanks for you time

Edit to Commerce.js scripts

---

src/technologies.json

- Updated wrong headers
With many apologies for this update again! 🙏

Update wrong header's props in Commerce.js

---

src/technologies.json

Default embed code
https://helpx.adobe.com/fonts/user-guide.html/fonts/using/embed-codes.ug.html
example website 
https://aplas.com/public

Fixed Typekit emded link

---

src/technologies.json

Modified PixiJS version

---

src/technologies.json

Duplicate technology PIXIjs deleted

---

src/technologies.json

Add Linkedin CDN Detection

---

src/technologies.json

It seems like someone is creating duplicate entries or not changing the object key when adding new technologies
This pull request will remove the duplicate entries, and rename the object key where it was already existing, but the values did not seem to be a duplicate.
Is it worth thinking about adding automated tests when creating a commit to prevent this from happening?﻿

fix(technologies): resolve duplicate entries

---

src/drivers/webextension/images/icons/plataforma_neo.svg
src/technologies.json

Website:
https://www.jetecommerce.com.br/
Example Websites:
https://frameworkneo-v2.plataformaneo.com.br/
https://www.bynv.com.br/
https://brooksdonna.com.br/

Update JET NEO detection

---

src/technologies.json

Website:
https://www.squarespace.com/ecommerce-website
Example websites: 
https://www.ageorge.nl/
https://www.12vues.fr/
https://wooterapparel.com
https://www.identitags.com

Add Squarespace Commerce/ Ecommerce

---

src/drivers/webextension/images/icons/TurfJS.svg
src/technologies.json

As requested in #3508
5.6k stars https://github.com/Turfjs/turf﻿

Add TurfJS

---

src/technologies.json

Improve BuySellAds detection

---

src/technologies.json

Fix AdonisJS detection

---

src/technologies.json

Adding Cloudflare Insight

---

src/technologies.json

Hey mate . Fixed some problems in .json file
#3562 and other pr

Fixed tech.json problems

---

src/technologies.json

Categories: 
- JavaScript frameworks
- Web frameworks
- Web servers
- Static site generator

Update Nuxt categories and description

---

src/technologies.json

Website:
https://mailchimp.com/pricing/
Example websites:
https://whiskeyriff.com **WordPress**
https://dev.skorecandle.com/shop-2 **WooCommerce**
**Shopify** problematic as usual cant see **async** scripts
https://store.djtechtools.com/
https://shop.rmg.co.uk/

Update MailChimp/Email,Marketing automation

---

src/technologies.json

Hey mate just update technologies.json . Also #3636 issue request 
Also updated SweetAlert according  Slack general chat request

Update tech.json duplicate,comma,colon problems / Update sweetalert

---

src/drivers/webextension/images/icons/Searchspring.svg
src/technologies.json

Website:
https://searchspring.com/price-quote-request/
Example websites:
https://www.victorianplumbing.co.uk/
https://www.emmabridgewater.co.uk/
https://shop.pbs.org/
https://provusion.pearsonvue.com/

Add Searchspring/Ecommerce search engine

---

src/technologies.json

Website:
https://fontawesome.com/changelog/latest
https://fontawesome.com/plans
example website:
https://miestro.com/

Update FontAwesome/ version

---

src/technologies.json

Website:
http://akamai.com
**Akamai mPulse:**
https://www.siriusxm.com/
https://jcrew.com
**Akamai Web Application Protector**
https://www.avis.com
https://www.eonline.com/
Hey mate , this file is loaded once at the initial opening of the site page
Read on forums

Update\Add Akamai products

---

src/technologies.json

Hey mate . Just updated Amazon ,Apple , Paypal , Visa payment processors according this website
https://www.avis.com
https://www.avis.com/en/reservation#/review-and-book
I'm not sure if these are local variables or something else. But as keywords, some percentage should probably be well defined. I'll leave it to your discretion

Update Payment processors

---

src/technologies.json

Hey mate . Just deleted unnecessary comma

Update FilePond/ trailing comma issue

---

src/technologies.json

Please, next time add a way to lint your JSON file (such as https://github.com/zaach/jsonlint) before commit it!

fix malformed JSON

---

src/technologies.json

Website:
https://www.oracle.com/cx/marketing/digital-intelligence/
Example :
https://www.maurices.com/

Add Oracle Infinity / Analytics

---

src/technologies.json

Improve Katex Detection

---

src/technologies.json

Update tech:
Add AB testing category , saas , pricing

Update Adobe Target

---

src/drivers/webextension/images/icons/Bronto.svg
src/technologies.json

Website:
https://bronto.com/
Example:
https://www.parts-express.com/
https://www.gunpartscorp.com/
https://www.micromark.com/

Add Bronto/Email marketing automation

---

src/technologies.json

- Add Fastly origin header to detect via origin rewrites

Update Fastly detection

---

src/technologies.json

Website:
https://www.clicktale.com/
Example:
https://www.watchstation.com/en-us/
https://www.puritan.com/
http://pak-service.kz/
https://www.yoox.com/

Update ClickTale / Analytics

---

src/technologies.json

Combined two versions into one

Update MS Ads, delete duplicate key

---

src/technologies.json

"website": "http://drupalcommerce.org
example:
https://www.pmbswiss.ch/product/ohlins-knobs-ttx22m
https://www.desertessence.com/
https://www.olssongerthel.se/flos/sarfatti-2097-lampa-ljuskrona
https://uk.lush.com/
https://www.foreo.com/ru/luna-3
https://www.desertessence.com/all-products

Update Drupal Commerce

---

src/technologies.json

Website:
https://clarity.microsoft.com/
Examples:
https://yeshourun.com/
https://comfyplane.com/

Add MS Clarity / analytics

---

schema.json
src/drivers/schema.json
src/drivers/webextension/_locales/en/messages.json
src/drivers/webextension/_locales/ru/messages.json
src/technologies.json

Fix validation error

---

src/technologies.json

Website:
https://emarsys.com/
Examples: 
https://www.shopgoodwill.com/
https://www.511tactical.com/
https://www.surlatable.com/

Update Emarsys/marketing aut, personaliztaion

---

src/drivers/webextension/images/icons/Yieldify.svg
src/technologies.json

Website: https://www.yieldify.com/
Examples:
https://www.lovelywholesale.com/
https://teespring.com/
https://www.retailgazette.co.uk/
https://www.maybelline.com/
https://www.vibilagare.se/

Add Yieldify / Personalization 

---

src/technologies.json

Website: https://heap.io/pricing
Examples: 
https://naturebox.com/
https://www.teacherspayteachers.com/
https://slickdeals.net/
https://linktr.ee/ ( unsuccessful Contentful  CMS)

Update Heap / Analytics

---

src/technologies.json

Website: https://kibocommerce.com/personalization-software/
Examples: 
https://www.revzilla.com
https://www.springer.com

Update Kibo Personalization / Pers

---

src/technologies.json

Website: https://pay.amazon.com
Examples: 
**https://naturebox.com
https://naturebox.com/checkout/shipping** 
Hey mate . Can u take a look reason why not detected in naturebox.com .
https://www.gucci.com/

Update Amazon Pay

---

src/technologies.json

Hi, I have added the following headers that allows to detect AWS:
- x-amz-err-code
- x-amz-request-id
- x-amz-id-2
- x-amz-err-message
- x-amz-req-time-micros
- x-amz-version-id
- x-amz-delete-marker
- x-amz-rid
Examples:
- https://storage.flugaerger-app.de/minio/login
- https://s3gw02.waldwasser.store/

Aws headers

---

src/drivers/webextension/_locales/en/messages.json
src/drivers/webextension/_locales/ru/messages.json
src/technologies.json

Add Retargeting / category

---

src/technologies.json

Request: #3829 
Website: https://paypal.com
Example https://celticlife.com/ 
add: 
```
"link": {
"attributes": {
"href": "paypal-express-checkout"
}
}
```

Update Paypal / Payment proc #3829 

---

src/technologies.json

#3830 
Changing the category to mark react as a library.

udating the category of react to 59 from 12

---

src/drivers/npm/driver.js
src/drivers/webextension/images/icons/Apptus.svg
src/technologies.json

Website: https://www.apptus.com/
Examples:
https://www.carlgoetz.de/
https://www.fortnumandmason.com/
https://www.bohus.no/
https://www.jula.no/
https://coop.no/
https://www.kataloska-prodaja.si/

Add Apptus / Personalization

---

src/technologies.json

Updated the Snowplow Analytics listing in the technologies.json file.

Updated Snowplow Analytics listing in technologies

---

src/technologies.json

Website: http://crosspixel.net/
Examples: 
https://rpp.pe/?ref=rpp
https://www.apkmirror.com/
https://www.bradsdeals.com/

Update Cross Pixel / Retargeting

---

src/technologies.json

websites: https://www.linkedin.com/developers
examples:
https://fitae.fr/
http://www.forumparlamento.it/
https://friday.se/
http://getujobs.com/

update Linkedin, Facebook Login / Social logins

---

src/technologies.json

Website: https://advertising.amazon.com/
Examples: 
https://journalstar.com/
https://pinchofyum.com/
https://www.seattlepi.com/

Add Amazon Advertising/ Advertising

---

src/technologies.json

website: https://affiliate-program.amazon.com/
Example: https://www.seattlepi.com/

Update Amazon Associates/ affiliate-programs

---

src/technologies.json

website: https://www.fastly.com/
Example https://www.wwe.com/

Update Fastly / CDN

---

src/drivers/webextension/images/icons/Ad Lightning.svg
src/technologies.json

website: 
https://www.adlightning.com
examples:
https://madison.com/
https://scnow.com/
https://www.vibe.com/
https://journaltimes.com/
https://sofrep.com/

Add Ad Lightning / Advertising monitoring  service

---

src/technologies.json

Website: https://ads.pinterest.com
https://www.sk-ii.com/
https://www.t-mobile.com/
https://www.healthline.com/

Add Pinterest Ads / Advertising, Update Retargeting category

---

src/technologies.json

some problems :
also return back website link:
Apparently replacing everything did not work correctly in this moment and was applied not only for the description

Updated technology.json file / coms, duplicate key problems

---

src/technologies.json

Hey there , just fixed `dom` identifier

Update ATSHOP / Ecommerce

---

src/technologies.json

website: http://www.pubmatic.com/
example: https://pinchofyum.com/
add **dom, xhr**

Update PubMatic / advertising

---

src/technologies.json

Proposal for adding detection for the official WordPress Site Kit plugin by Google ([website](https://sitekit.withgoogle.com/), [plugin page](https://wordpress.org/plugins/google-site-kit/)).

Add official WordPress Site Kit plugin detection

---

src/technologies.json

website: https://newrelic.com/pricing
example: https://www.elo7.com.br/

Update New Relic / analytics

---

src/technologies.json

website: https://www.hubspot.com/products/crm/live-chat
examples:
https://www.gupy.io/
https://www.revcontent.com/

Add HubSpot Chat / live chat

---

src/technologies.json

Website: https://www.spotx.tv/
Examples:
https://jamaicans.com/
https://www.selection.ca/
https://va.org/
Website:  https://www.amp.dev
Examples: https://inews.co.uk/

Update AMP, SpotX

---

src/technologies.json

👋
Hi again @AliasIO
This PR introduces:
- Typo fix in the technologie name
ps: I mistakenly dropped that commit while rebasing the PR last time 🙇‍♂️.
Thank you!

Bump technologie detection

---

src/drivers/webextension/images/icons/Reservio.svg
src/technologies.json

website: https://www.reservio.com/
examples: 
http://www.dermaline.nl/
https://de-garage.com/
https://www.die-kraftreise.de/
https://doctoraurbano.com.ve/
https://domovbozice.cz/

Add Reservio / Appointment scheduling

---

src/technologies.json

Hey mate .
https://github.com/AliasIO/wappalyzer/pull/3952/commits/c853123bd51fe09bc5a55b114cff1ec9c53ac423 updated this one

Update Reservio / scheduling

---

src/technologies.json

Added CPEs for AngularJS, Backbone.js, ExtJS, Handlebars, Moment.js, Prototype, TinyMCE, YUI.

Add CPE for some JavaScript-based techologies

---

src/technologies.json

request #3962 website:  https://kit.svelte.dev 
examples: 
https://www.gitpod.io/
https://rust-jungle.vercel.app/

Add SvelteKit , update Svelte / UI Framework

---

src/technologies.json

Hi, 
in my previous PR (https://github.com/AliasIO/wappalyzer/pull/3947) I missed with JS detection - this detection is too wide.
Please merge this PR too and sorry about inconvenience

fix Weblium site builder detection

---

src/drivers/webextension/images/icons/Inertia.svg
src/technologies.json

website: https://inertiajs.com
example: 
https://reel.so/

Add Inertia / JS framework

---

src/technologies.json

website: http://shopify.com"
examples: 
https://www.wearfigs.com/ request #3983 
https://store.wikileaf.com

Update Shopify / ecommerce

---

src/technologies.json

GSAP 2: `TweenLite.version` or `TweenMax.version`
GSAP 3: `gsap.version`

Add GSAP version detection

---

src/drivers/webextension/images/icons/Leadinfo.svg
src/technologies.json

website:  https://www.leadinfo.com/en/pricing/
examples:
https://pageking.nl/
https://schmuhl.nl/
https://baaibreda.nl/

Add Leadinfo / analytics

---

src/drivers/webextension/_locales/ca/messages.json
src/drivers/webextension/_locales/de/messages.json
src/drivers/webextension/_locales/el/messages.json
src/drivers/webextension/_locales/en/messages.json
src/drivers/webextension/_locales/es/messages.json
src/drivers/webextension/_locales/fa/messages.json
src/drivers/webextension/_locales/fr/messages.json
src/drivers/webextension/_locales/gl_ES/messages.json
src/drivers/webextension/_locales/gr/messages.json
src/drivers/webextension/_locales/id/messages.json
src/drivers/webextension/_locales/it/messages.json
src/drivers/webextension/_locales/ja/messages.json
src/drivers/webextension/_locales/ko/messages.json
src/drivers/webextension/_locales/pl/messages.json
src/drivers/webextension/_locales/pt/messages.json
src/drivers/webextension/_locales/pt_BR/messages.json
src/drivers/webextension/_locales/ro/messages.json
src/drivers/webextension/_locales/ru/messages.json
src/drivers/webextension/_locales/sk/messages.json
src/drivers/webextension/_locales/tr/messages.json
src/drivers/webextension/_locales/uk/messages.json
src/drivers/webextension/_locales/uz/messages.json
src/drivers/webextension/_locales/zh_CN/messages.json
src/drivers/webextension/_locales/zh_TW/messages.json
src/technologies.json

Add Geolocation , Themes categories

---

src/drivers/webextension/images/icons/visualcomposer.svg
src/technologies.json

* Adds the Visual Composer page builder
* Improves detection of Divi page builder

Add Visual Composer & improve Divi detection

---

src/drivers/webextension/images/icons/Pendo.svg
src/technologies.json

website: https://www.pendo.io/pricing/
examples:
https://www.machinerypete.com/
https://www.amway.com/
https://connect.aei.org/

Add Pendo / user on-boarding

---

src/technologies.json

request: #4066 
website:  https://www.oracle.com/uk/cx/marketing/personalization-testing
examples:
https://www.publicdesire.com/
https://www.ferguson.com/
https://www.prudential.com
https://www.matalan.co.uk/

Add Oracle Maxymiser / AB test , personalisation

---

src/technologies.json

request #4062
website: https://www.salecycle.com"
examples: 
https://www.boohoo.com/
https://www.lelo.com/ru
https://www.zipcar.com/

Update SaleCycle / Ecommerce personalisation

---

src/technologies.json

Apply correct regex per https://github.com/AliasIO/wappalyzer/pull/4053#issuecomment-868276095

Fix FingerprintJS regex

---

src/technologies.json

request #4068
website: https://www.salesforce.com/products/marketing-cloud/customer-interaction/
examples:
https://www.joyjewelers.com/
https://www.matalan.co.uk/
https://invictastores.com/
https://www.sundancecatalog.com/

Add Salesforce Interaction Studio(Evergage) / personalisation

---

src/technologies.json

Pproperly match square brackets.
Introduced in: https://github.com/AliasIO/wappalyzer/pull/4001/

fix: imbalanced 'localised' dom pattern

---

src/technologies.json

request #4084
example: https://www.houseoffraser.co.uk/brand/ann-summers

Update Dynamic Yield / Personalisation

---

src/technologies.json

request #4094 
examples: 
https://www.skiphop.com/?id=skiphop&updateCountry=true 
https://grizly.com/

Update Quantcast / analytics , cookie compliance

---

src/technologies.json

request: #4117 
website: https://knowledge.hubspot.com/reports/what-cookies-does-hubspot-set-in-a-visitor-s-browser
examples:
https://www.durangoboots.com/
https://www.mobivity.com/
https://help.anedot.com/

Add HubSpot Cookie / Cookie Compliance

---

src/technologies.json

request: #4119 
website: https://segment.com/blog/how-to-build-consent-management-into-your-site-in-less-than-a-week
Example site - https://wisepops.com/
could not find  additional  examples

Add Segment Consent Manager / cookie compliance

---

src/technologies.json

original #4096
request #4069 to change category

update RapidSpike/ issue-tracker , RUM

---

src/technologies.json

As seen on this site: https://www.eneba.com/
And it's documented in the docs: https://www.apollographql.com/docs/react/performance/server-side-rendering/#executing-queries-with-getdatafromtree

Improve Apollo by detecting script with state

---

src/technologies.json

Website: https://www.sqreen.com/
Examples:
- https://www.lemonde.fr/
- https://www.malt.fr/

Add Sqreen to Security category

---

src/technologies.json

website: https://www.ebis.ne.jp/plan/
examples:
https://granbluefantasy.jp/
https://gashapon.jp/
https://www.princehotels.co.jp/
https://p-bandai.jp/contents/global/

Update Ad Ebis / advertising, marketing automation

---

src/technologies.json

request: #4159  
website: https://salesfloor.net/
examples:
https://www.chicos.com/
https://dev.labaie.com/
https://www.soma.com 
https://1r.dkfjeoifjpejwpf099.ml/

Update Salesfloor / ecommerce , widgets

---

src/technologies.json

request: #4169 
example: https://www.jabra.ru/
PS.  all correct but couldn't check locally

Update UpSellit / ecommerce , personalisation

---

src/technologies.json

request: #4166 
example: https://www.jabra.ru/

Update DigitalRiver / ecommerce , payments

---

src/technologies.json

request: #4165 
website: https://www.klarna.com/us/business/pricing/
examples:
https://www.yumi.co.uk/
https://www.shopjustice.com/
https://www.ilovedooney.com/

Update Klarna Checkout / ecommerce , payment processor

---

src/technologies.json

request #4167 
website: https://www.adroll.com/features/consent-management
examples: 
https://us.upsellit.com/
https://www.eargo.com/

Add AdRoll CMP System / cookie compliance

---

src/drivers/webextension/images/icons/Qualtrics.svg
src/technologies.json

request #4168 
website: https://www.qualtrics.com/
examples:
https://www.gmc.com/
https://www.pilotonline.com/
https://www.reebok.co.uk/ex-o-fit-hi/3478.html?pr=home_rr&slot=3&rec=ctn

Add Qualtrics / surveys

---

src/drivers/webextension/_locales/ca/messages.json
src/drivers/webextension/_locales/de/messages.json
src/drivers/webextension/_locales/el/messages.json
src/drivers/webextension/_locales/en/messages.json
src/drivers/webextension/_locales/es/messages.json
src/drivers/webextension/_locales/fa/messages.json
src/drivers/webextension/_locales/fr/messages.json
src/drivers/webextension/_locales/gl_ES/messages.json
src/drivers/webextension/_locales/gr/messages.json
src/drivers/webextension/_locales/id/messages.json
src/drivers/webextension/_locales/it/messages.json
src/drivers/webextension/_locales/ja/messages.json
src/drivers/webextension/_locales/ko/messages.json
src/drivers/webextension/_locales/pl/messages.json
src/drivers/webextension/_locales/pt/messages.json
src/drivers/webextension/_locales/pt_BR/messages.json
src/drivers/webextension/_locales/ro/messages.json
src/drivers/webextension/_locales/ru/messages.json
src/drivers/webextension/_locales/sk/messages.json
src/drivers/webextension/_locales/tr/messages.json
src/drivers/webextension/_locales/uk/messages.json
src/drivers/webextension/_locales/uz/messages.json
src/drivers/webextension/_locales/zh_CN/messages.json
src/drivers/webextension/_locales/zh_TW/messages.json
src/technologies.json

Add Loyalty category

---

src/technologies.json

- Removed arbitrary HTML (causing false positives)
- Removed vague JS object
- Added Duda specific library detection
- Added Duda description
- Changed category to landing page builder (Duda is not a CMS)
- Change GoDaddy Website Builder category to page builder as well (it's not a CMS)

Fix Duda detection

---

src/technologies.json

request #4186 
website : https://www.optimizely.com
examples:
https://global.direct.asda.com/george/clothing/10,default,sc.html
https://www.factoryauthorizedoutlet.com/

Update Optimizely / AB testing

---

src/technologies.json

request #4192 
website: https://www.osano.com
example: https://www.hobbycraft.co.uk/

Update Osano / Cookie Compliance

---

src/technologies.json

request #4197
website: https://www.quadpay.com
examples: 
https://www.gamestop.com/
https://www.goldstarhoneybees.com/

Update Quadpay / payment processors

---

src/technologies.json

Update ContentSquare / analytics, ab testing

---

src/technologies.json

request #4234 
example: https://www.go-parts.com/

Update Bolt Payments / Payment processors

---

src/drivers/webextension/_locales/ca/messages.json
src/drivers/webextension/_locales/de/messages.json
src/drivers/webextension/_locales/el/messages.json
src/drivers/webextension/_locales/en/messages.json
src/drivers/webextension/_locales/es/messages.json
src/drivers/webextension/_locales/gl_ES/messages.json
src/drivers/webextension/_locales/gr/messages.json
src/drivers/webextension/_locales/id/messages.json
src/drivers/webextension/_locales/it/messages.json
src/drivers/webextension/_locales/ja/messages.json
src/drivers/webextension/_locales/ko/messages.json
src/drivers/webextension/_locales/nl/messages.json
src/drivers/webextension/_locales/pl/messages.json
src/drivers/webextension/_locales/pt/messages.json
src/drivers/webextension/_locales/pt_BR/messages.json
src/drivers/webextension/_locales/ro/messages.json
src/drivers/webextension/_locales/sk/messages.json
src/drivers/webextension/_locales/tr/messages.json
src/drivers/webextension/_locales/uk/messages.json
src/drivers/webextension/_locales/uz/messages.json
src/drivers/webextension/_locales/zh_CN/messages.json
src/drivers/webextension/_locales/zh_TW/messages.json
src/technologies.json

As described in this feature request:
[Add Wordpress Theme Category #4291](https://github.com/AliasIO/wappalyzer/issues/4291)
This pull request:
- adds the new category
- updates the locale files to match new cat
- adds new cat to all WP plugins already listed in technologies.json
- changes `implies` to `requires` where relevant

Add Wordpress Theme Category

---

src/drivers/webextension/_locales/ca/messages.json
src/drivers/webextension/_locales/de/messages.json
src/drivers/webextension/_locales/el/messages.json
src/drivers/webextension/_locales/en/messages.json
src/drivers/webextension/_locales/es/messages.json
src/drivers/webextension/_locales/fa/messages.json
src/drivers/webextension/_locales/fr/messages.json
src/drivers/webextension/_locales/gl_ES/messages.json
src/drivers/webextension/_locales/gr/messages.json
src/drivers/webextension/_locales/id/messages.json
src/drivers/webextension/_locales/it/messages.json
src/drivers/webextension/_locales/ja/messages.json
src/drivers/webextension/_locales/ko/messages.json
src/drivers/webextension/_locales/nl/messages.json
src/drivers/webextension/_locales/pl/messages.json
src/drivers/webextension/_locales/pt/messages.json
src/drivers/webextension/_locales/pt_BR/messages.json
src/drivers/webextension/_locales/ro/messages.json
src/drivers/webextension/_locales/sk/messages.json
src/drivers/webextension/_locales/tr/messages.json
src/drivers/webextension/_locales/uk/messages.json
src/drivers/webextension/_locales/uz/messages.json
src/drivers/webextension/_locales/zh_CN/messages.json
src/drivers/webextension/_locales/zh_TW/messages.json
src/technologies-all.json
src/technologies.json

As detailed in this FR:
Add Category For WordPress Hosting #4303

Add Category For WordPress Hosting & Update Exisiting Entries

---

src/technologies.json

CPE sourced from https://nvd.nist.gov/products/cpe/detail/847581?namingFormat=2.3&orderBy=CPEURI&status=FINAL  
OSS evidenced by https://datatables.net/license/mit

Add DataTables version, CPE, description, and license

---

src/technologies.json

`jQuery.fancybox.version` for when `$.fancybox` is undefined  
`Fancybox.version` for v4 detection

Improve FancyBox version detection

---

src/technologies.json

https://github.com/AliasIO/wappalyzer/issues/4379
https://github.com/AliasIO/wappalyzer/issues/4262
https://github.com/AliasIO/wappalyzer/issues/4301
https://github.com/AliasIO/wappalyzer/issues/4298

Improvement for 'ApplePay' / 'SAP Commerce Cloud' / 'Quantcast Choice' / 'Amazon Pay'

---

src/technologies.json

Updated to reflect more accurate categories

Updated categorisation for Loox / Tidio / Okendo

---

src/technologies.json

15.1k stars on GitHub: https://github.com/zloirock/core-js  
Example website: https://www.bbc.com/

Add core-js

---

src/drivers/webextension/images/icons/Razorpay.svg
src/drivers/webextension/images/icons/TRUENDO.svg
src/technologies.json

request #4411
website: https://truendo.com/en/cookie-manager/pricing/
examples:
https://www.checkmybus.es/
https://www.wearedevelopers.com/
https://www.fernbusse.de/
https://sportsdata.ag/

Add TRUENDO / Cookie compliance

---

src/technologies.json

These companies make claims, but do not achieve WCAG compliance or produce accessible sites.

Changes to include overlays

---

src/technologies/s.json

Typo fix in snigel AdConsent description

---

src/drivers/webextension/images/icons/Zyro.svg
src/technologies/z.json

website: https://zyro.com/pricing
examples:
https://3dwall.lt/
https://aaplus-innovations.com
https://aapnocarbazar.com
https://aaron2winsmith.com
https://aarongaita.com
https://agnesjewel.com/

Add Zyro / Page builder

---

src/drivers/webextension/images/icons/Mapplic.svg
src/technologies/m.json

request #2761 
website : https://mapplic.com/pricing
examples:
https://www.sykes.com/
https://www.ideas42.org/
https://wwoof.net/
https://pulkovoairport.ru/passengers/map/

Add Mapplic / map  #2761  

---

src/technologies/b.json

request #3170
website: 
https://www.blackbaud.com/products/blackbaud-luminate-online
examples:
https://community.getty.edu/
https://my.famu.edu/
https://giving.promedica.org/
https://giving.pratt.edu/

Update Blackbaud / CRM , payment processor, marketing automation #3170

---

src/technologies/b.json
src/technologies/f.json
src/technologies/g.json
src/technologies/h.json
src/technologies/r.json
src/technologies/t.json
src/technologies/y.json

Moved some technologies from **widget**  and **appointment scheduling** categories  to **reservation & delivery**

Update widgets / widgets,reservation & delivery

---

src/drivers/webextension/images/icons/RapidSec.svg
src/technologies/r.json

https://rapidsec.com/
- Security
- https://www.nascar.com/
- https://www.rei.com/
- https://www.handlestore.com/
- https://www.intezer.com/
- https://cleanmypc.co.uk/
- https://sacu-student.com/

Added RapidSec

---

src/categories.json
src/drivers/webextension/_locales/ca/messages.json
src/drivers/webextension/_locales/de/messages.json
src/drivers/webextension/_locales/el/messages.json
src/drivers/webextension/_locales/en/messages.json
src/drivers/webextension/_locales/es/messages.json
src/drivers/webextension/_locales/fa/messages.json
src/drivers/webextension/_locales/fr/messages.json
src/drivers/webextension/_locales/gl_ES/messages.json
src/drivers/webextension/_locales/gr/messages.json
src/drivers/webextension/_locales/id/messages.json
src/drivers/webextension/_locales/it/messages.json
src/drivers/webextension/_locales/ja/messages.json
src/drivers/webextension/_locales/ko/messages.json
src/drivers/webextension/_locales/nl/messages.json
src/drivers/webextension/_locales/pl/messages.json
src/drivers/webextension/_locales/pt/messages.json
src/drivers/webextension/_locales/pt_BR/messages.json
src/drivers/webextension/_locales/ro/messages.json
src/drivers/webextension/_locales/ru/messages.json
src/drivers/webextension/_locales/sk/messages.json
src/drivers/webextension/_locales/tr/messages.json
src/drivers/webextension/_locales/uk/messages.json
src/drivers/webextension/_locales/uz/messages.json
src/drivers/webextension/_locales/zh_CN/messages.json
src/drivers/webextension/_locales/zh_TW/messages.json

Add Digital asset management / category

---

src/technologies/o.json

[OpenBSD httpd] Exclude Apache from detection

---

src/drivers/webextension/images/icons/Fing.svg
src/technologies/f.json
src/technologies/t.json

[https://fing.ir](https://fing.ir)
[https://fing.ir](https://fing.ir)
[https://docs.fing.ir](https://docs.fing.ir)

Add Fing / PaaS

---

src/technologies/g.json

https://nesn.com/
https://www.strava.com/
https://infox.sg/
https://ru.xhamsterlive.com/

Update Google Sign-in / Authentication #4307

---

src/technologies/f.json

**examples:**
http://seleck.cc/
https://leboutique.com/
**description about facebook pixel**
https://developers.facebook.com/docs/facebook-pixel/advanced/
Request #4284 
**examples:**
https://www.letrunkshop.com/
https://expertnavlasy.sk/account/login
https://dev-facebook-chat.myshopify.com/pages/document-facebook-chat
We have such an abstract widget with an abstract description. Probably, after a lot of detail, this code is no longer needed?
```
"Facebook": {
"cats": [
5
],
"description": "Facebook is an online social media and social networking service.",
"icon": "Facebook.svg",
"scripts": "//connect\\.facebook\\.([a-z]+)/[^/]*/[a-z]*\\.js",
"website": "http://facebook.com"
},
```
https://www.techopedia.com/definition/4827/facebook-connect

Update Facebook products , Add Facebook Chat Plugin #4284

---

src/technologies/a.json

https://mamaearth.in/
https://untuckit.co.uk/
The update duplicates the identifier in the **meta** section. The identifier itself for this site only works through the **dom**

Update Amazon Advertising, Pay #4278

---

src/technologies/j.json

Some example of detections at [publicwww.com](https://publicwww.com/websites/%3Cinput+type%3D%22hidden%22+name%3D%22javax.faces.ViewState%22/)

improve jsf detection

---

src/drivers/webextension/images/icons/Stitches.svg
src/technologies/s.json

in this pr i added Stitches.js detection 
it is a new css-in-js lib that is framework agnostic and support SSR and other cool features  
[stitches repo](https://github.com/modulz/stitches)
it is used in 
https://ped.ro/
https://vercel.com/dashboard
https://uiw.tf/

Adding Stitches.js detection

---

src/technologies/s.json

Kept the one that seemed to be more complete.

Remove duplicate "stitches" entry

---

src/technologies/a.json

Forgot to add a description when adding the detection. Also noticed that their website redirects to a different URL, so updated that as well.

added a description and changed the URL for Addi

---

src/technologies/a.json

https://athemes.com/theme/astrid/
http://travelers-door.com/
http://www.cineaqui.com/
https://luisrojasmarcos.com/
https://itmattersgames.com/
https://snudifo94.fr/

Add aThemes Astrid / WordPress theme

---

src/technologies/w.json

https://wordpress.org/themes/default/
https://showme.co.za/
https://www.zhangxinxu.com/
http://v-androide.com/
http://small-projects.org/
http://bezprovodoff.com/
http://www.cool-auction.net/

Add WordPress Default / WordPress theme

---

src/technologies/e.json

Adding js object based detection. I believe this is more efficient than scriptsrc. Keeping scriptsrc as a fallback.

added js object based detection for expertrec

---

src/technologies/e.json

https://wordpress.org/themes/enigma/
http://stpecad.com.br/
http://paytakhthefaz.com/
https://essaycube.com/
http://gulfegy-service.com/
https://www.tax.gov.sd/

Add Enigma / WordPress theme

---

src/technologies/a.json

https://andersnoren.se/teman/hitchcock-wordpress-theme/
https://wetlookhd.com/
https://beiahlberg.de/
https://www.ringfuchs.de/
http://spamm.fr/
https://snrclan.com/
http://escapeauthority.com/
http://beunfolded.com/
http://kahi.cz/

Add AndersNoren Hitchcock / Wordpress theme

---

src/drivers/webextension/images/icons/The Theme Foundry.svg
src/technologies/t.json

https://thethemefoundry.com/wordpress-themes/make/
https://www.stevehoffman.tv/
https://firebrandtech.com/
https://littleredtarot.com/
https://arongranberg.com/
https://www.alcoholproblemsandsolutions.org/
https://firebrandtech.com/
https://www.atlanticballet.ca/en/home/
https://impulse.net.br/
http://www.mundofantasma.com/

Add The Theme Foundry Make / WordPres theme

---

src/technologies/s.json

https://squareup.com/us/en/online-store/plans
https://www.deruorderonline.com/
https://glasserienyc.square.site/

Add Square Online / ecommerce

---

src/technologies/c.json

https://www.cryoutcreations.eu/wordpress-themes/parabola
http://14textures.com/
http://www.ug.edu.ec/
https://www.cipfpcanastell.com/
http://www.hledejsi.eu/
https://ceeakmalaga.com/

Add Cryout Creations Parabola / WP theme

---

src/technologies/t.json

https://themezee.com/themes/poseidon/
https://svet-vokrug.ru/
https://theitbros.com/
https://www.techcrises.com/
https://www.hcchristianchurch.org/
http://futsaleuro2018.si/
https://pravoslavie.fm/

Add ThemeZee Poseidon / WP theme

---

src/technologies/c.json

https://www.cryoutcreations.eu/wordpress-themes/bravada
http://heartlandfoodcorp.com/
https://arquilog.com.br/
https://www.abraxia.it/
https://www.inramstechnology.com/

Add Cryout Creations Bravada / WP theme

---

src/technologies/s.json

https://siteorigin.com/page-builder/
https://www.bastillepost.com/hongkong/
https://www.sch.gr/
https://eldesmarque.com/actualidad/
http://mido-rin.com/
http://traffim.com/
https://www.divx.com/
http://www.midi-madagasikara.mg/

Add SiteOrigin Page Builder / WP plugin

---

src/technologies/h.json

https://www.hotjar.com/product/incoming-feedback/
https://www.scoutshop.org/
https://spiceology.com/
https://www.hotjar.com/product/incoming-feedback/

Add Hotjar Incoming Feedback / widget #4324

---

src/technologies/t.json

https://www.firstclasswatches.co.uk/

Update Timify / appointment-scheduling #4323

---

src/technologies/s.json

https://sharethis.com/
https://www.asics.com/gb/en-gb/
https://www.firstclasswatches.co.uk/

Update ShareThis / widget #4322

---

src/technologies/p.json

https://polyfill.io/
https://www.biggreenegg.co.uk/
https://www.globo.com/
https://weather.com/en-GB/?Goto=Redirected

Update Polyfill / JS lib #4329

---

src/technologies/k.json

Update Keap / CRM #4333

---

src/technologies/m.json

https://www.swooneditions.com/
https://www.lentesplus.com/ar/
https://www.jomashop.com/
https://www.shoebacca.com/
https://www.superatv.com/

Update Magento / ecommerce #4372

---

src/technologies/l.json

#website:
https://liveramp.com/data-plus-math/
https://www.hondacertified.com/
https://www.onepeloton.com/

Add LiveRamp DPM / advertising #4354

---

src/drivers/webextension/images/icons/WP-PageNavi.svg
src/technologies/w.json

https://github.com/lesterchan/wp-pagenavi
http://manga-zip.net/
http://www.ghafla.com/
http://javpop.com/
https://www.insightsonindia.com/
https://cgpersia.com/
https://www23.estrenosdoramas.net/
http://bajalogratis.com/

Add WP-PageNavi / WP plugin

---

src/technologies/u.json

Addresses: https://github.com/AliasIO/wappalyzer/issues/4869

Improve Usercentrics

---

src/technologies/c.json

https://cookieinformation.com/
https://coloursleep.fr/
https://www.dmi.dk/
https://emu.dk/
https://ing.dk/
https://www.ug.dk/
https://www.edc.dk/

Fix Cookie Information / Cookie compliance

---

src/technologies/a.json
src/technologies/c.json
src/technologies/m.json
src/technologies/o.json
src/technologies/p.json
src/technologies/q.json
src/technologies/t.json

AdRoll
AppNexus
Criteo
Microsoft Advertising
OpenX
PubMatic
Quantcast Measure
Treasure Data
https://tenki.jp/

Fixes and updates

---

src/drivers/webextension/images/icons/Sublime.svg
src/technologies/s.json

https://www.sublime.xyz/en
https://www.marmiton.org/
https://www.aufeminin.com/
https://www.enfemenino.com/
https://www.maxifoot.fr/
https://www.topito.com/
https://www.paroles.net/

Add Sublime / Advertising

---

src/technologies/_.json

https://www.emuparadise.me/
http://www.garant.ru/
https://www.pagenews.gr/
https://ohnotheydidnt.livejournal.com/
https://www.indgovtjobs.in/
http://www.differencebetween.net/
http://www.qmaths.in/

Update 33across / advertising

---

src/technologies/v.json

https://portal.vidible.tv/o2/signin
https://www.kidsgen.com/
https://sbcodez.com/
https://www.stijlmeisje.com/

Update Verizon Media / advertising

---

src/technologies/a.json

https://www.netreviews.com/fr/
https://www.saint-maclou.com/
https://www.dorcelstore.com/fr/
https://www.princessetamtam.com/
https://www.kusmitea.com/fr/home/
https://www.brico-phone.com/
https://www.laboutiqueducoiffeur.com/
https://juniane.fr/
https://www.editions-legislatives.fr/
https://www.cowlingandwilcox.com/

Update Avis Verifies / Reviews

---

src/technologies/z.json

https://www.zoho.com/pagesense/pricing.html
https://www.manageengine.com/
https://isha.sadhguru.org/uk/en
https://smallbiztrends.com/
https://www.site24x7.com/
https://www.zoho.com.cn/
https://www.maestroqa.com/

Add Zoho PageSense / A/B test, Personalisation

---

src/technologies/c.json

add description , pricing model , link to roxr soft for gosm

Update Clicky / Analytics

---

src/drivers/webextension/images/icons/Inventrue.svg
src/technologies/i.json

https://www.inventrue.com/
https://www.goplayrv.com/
https://www.mcgaughrv.com/
https://www.greenewayrv.com/

Add Inventrue / ecommerce

---

src/technologies/i.json

fix desc #5211

---

src/drivers/webextension/images/icons/Flutter.svg
src/technologies/f.json

https://flutter.dev/
https://connect.mosbybuildingarts.com/#/
https://live.aut.ac.nz/#/home
https://dashboard.mediacurrent.com/#/

Add Flutter / UI frameworks

---

src/technologies/b.json

fix category #5187

---

src/drivers/webextension/images/icons/Kakao.svg
src/technologies/k.json

https://developers.kakao.com/
https://m.mt.co.kr/renew/
https://m.edaily.co.kr/
http://stoo.asiae.co.kr/
http://www.ohmynews.com/
https://story.kakao.com/ch/ohmystar
hanatour.com

Add Kakao / Miscellaneous

---

src/drivers/webextension/images/icons/Twitch.svg
src/technologies/t.json

https://dev.twitch.tv/docs/embed/video-and-clips/
https://www.shacknews.com/
https://www.playgwent.com/en/
https://www.vitonica.com/

Add Twitch Player / Video player

---

src/technologies/o.json

https://optinmonster.com/
https://www.winzip.com/en/product/winzip/windows/vista/
https://www.collegeconfidential.com/
https://www.fattureincloud.it/

Add OptinMonster / marketing automation

---

src/technologies/l.json

https://www.liveperson.com
https://www.gmpartsdirect.com/
https://www.allentate.com/
https://www.carbase.co.uk/
https://www.bigmotoringworld.co.uk/
https://www.toyotaofbellevue.com/

Update LivePerson / Live chat

---

src/technologies/c.json

Update Crisp / Live chat

---

src/technologies/c.json

https://covet.pics/#features
https://culturehustle.com/
https://www.the5th.co/
https://kysermusical.com/
https://store.warlordgames.com/
https://beautifuldestinations.com/
https://www.pixeleyewear.com/

Update Covet.pics / widget

---

src/technologies/j.json

https://code.jquery.com/
https://www.ask.com/
https://www.nih.gov/
https://www.abs-cbn.com/
https://uzone.id/
https://www.ieee.org/
https://www.dw.com/ru

Add jQuery CDN / CDN

---

src/drivers/webextension/images/icons/EthicalAds.svg
src/technologies/e.json

https://ethicalads.io
https://graphemica.com/
https://w3techs.com/
https://dane.engineering/
https://uptime.is/
https://devhumor.com/
and many more: https://github.com/search?l=HTML&q=media.ethicalads.io&type=Code

Add EthicalAds / Advertising
