wappalyzer/wappalyzer

- share/apps.json
In: `Trac` app is two property with the same name `html` one is string and one is array of strings:
"html": "<a id=\"tracpowered",
"html": [ "<a id=\"tracpowered", "Powered by <a href=\"[^\"]*\"><strong>Trac(?:[ /]([\\d.]+))?\\;version:\\1" ],
> fix duplicate `html` property in `Trac` app

- share/apps.json
In: `Trac` app is two property with the same name `html` one is string and one is array of strings:
"html": "<a id=\"tracpowered",
"html": [ "<a id=\"tracpowered", "Powered by <a href=\"[^\"]*\"><strong>Trac(?:[ /]([\\d.]+))?\\;version:\\1" ],
> again fix duplicate `html` property in `Trac` app

- .gitignore
- .travis.yml
- README.md
What this does:
- Running `npm test` (like Travis CI does) will check for validation on `apps.json` and `schema.json`.
- I am using Grunt (an NPM package) to test it.
- More tests can be added; this is just a basic one to catch the most common errors. Most pull requests are to `apps.json`.
- Grunt can also be used for automated building, etc.
- All pull requests will automatically be tested and their pass/fail will be shown in the pull request,
What will need to be done if this is merged:
- This repo will need to be registered on Travis CI (free). I already have added the `.travis.yml` file, so it should start working immediately.
- A badge should be added to the top of the README. The badge won't work until Wappalyzer is registered on Travis CI. It is the passing/failing badge: …
> Add simple JSON validator Travis CI Test

- src/drivers/phantomjs/Dockerfile
By default phantoms JS use SSLv3 only:
`  --ssl-protocol=<val>                 Sets the SSL protocol (supported protocols: 'SSLv3' (default), 'SSLv2', 'TLSv1', 'any')`
For this reason it doesn't work with non ssl3 sites like https://mail.ru.
> Fix phantomjs problem with non ssl3 sites

- src/apps.json
Moogo is discontinued. The CMS continues it's life under Kotisivukone brand
> Fix for outdated brand

- src/apps.json
As of Craft 2.4, Craft will send this header by default.
> Check for `X-Powered-By: Craft CMS` header

- src/drivers/npm/index.js
Saw that I forgot to actually check for the environment variable. "testing" is only set when testing and makes the tests check 2 folders up rather than in the same folder for the module as it would be when packaged on npm.
What is the process on pushing new versions to NPM ? Would love to start using it and 2 packages for the same project would just confuse people.
> Updated to use the correct environment variable

- bin/wappalyzer-build
Added "NPM" to the build list. But all I'm doing is ``cp -R $WAPPALYZER_ROOT/src/drivers/npm/* $WAPPALYZER_ROOT/build/wappalyzer_npm/``. 
Once built you can publish with https://docs.npmjs.com/cli/publish
> Added 2 lines to make a "wappalyzer_npm" build folder 

- src/apps.json
Neos has separated from the TYPO3 completely and now has it's own URL, funding, and more. **Make sure that the newly released Neos 2.0 is still being pickup up by your scripts.**
- https://typo3.org/news/article/typo3-project-focuses-on-typo3-cms-neos-to-start-its-own-community/
- https://typo3.org/news/article/this-week-in-typo3-2015-week-25/
> [TASK] Update Neos URL after split from TYPO3

- src/apps.json
The domain name must be prefixed with "www.".
> Fixed Doxygen URL

- src/apps.json
The [old](http://documentcloud.github.com/backbone) website link of Backbone.js is dead. Changed to new URL: backbonejs.org
> Fixed dead link Backbone.js

- src/drivers/php/Wappalyzer.php
The server can not follow the RFC and use \n as separator instead \r\n
> Optimize headers parsing

- src/apps.json
Updated website URL WP-Super-Cache. ocaoimh.ie/wp-super-cache/ is redirecting to new URL z9.io/wp-super-cache/, changed it just in case they remove their old domain.
> Updated website URL WP-Super-Cache

- bin/wappalyzer-links
- src/drivers/bookmarklet/.gitignore
- src/drivers/bookmarklet/js/driver.js
- src/drivers/chrome/.gitignore
- src/drivers/chrome/js/driver.js
- src/drivers/chrome/js/popup.js
- src/drivers/firefox/.gitignore
- src/drivers/firefox/data/js/panel.js
- src/drivers/firefox/driver.js
- src/drivers/html/.gitignore
- src/drivers/html/js/driver.js
This adds support for svg icons in following drivers:
* Mozilla Firefox
* Google Chrome
* Bookmarklet
* HTML
Works in address bar and popups.
> Add support for svg icons in drivers

- src/apps.json
The patterns for basket.js are quite generic and match at a lot of sites that aren't using this script. The confidence should be lower.
> Lower confidence for all basket.js patterns

- src/apps.json
Version information in the headers was removed in version 1.2.1, but not
all websites are using this version. Additionally, an empty "X-Arastta"
header implies Arastta 1.2.1+ so detection was added for this as well.
> Re-add version detection for Arastta

- src/drivers/chrome/js/driver.js
Local Storage saves everything as strings: `"0"` is not falsey, `0` is.
Until now Chrome always opened a tab when Wappalizer updated, regardless of that option.
> Respect "Show upgrade message" option in Chrome

- src/apps.json
IPB (now IPS Suite) version 4 doesn't use the global "IPBoard" object.
> Update IP.Board/IPS Suite detection

- src/apps.json
Fix [old](http://documentcloud.github.com/underscore) dead link to the [new](http://underscorejs.org/) one.
As seen on documentcloud.org/opensource.
> Fix Underscore.js URL

- src/apps.json
Hippo CMS rexex extra space caused to miss out on CMS detection if the space is missing before the html tag.
> Minor fix on Hippo CMS detection

- src/apps.json
It always shows "Arastta 1.2.1+", after this change, it shows only "Arastta" if Arastta version is greater than 1.2.1
> Remove version number from Arastta e-Commerce

- src/apps.json
Hi, I just added 2 regexes to support Magento 2.
The first one is in the html node and looks for `<script type="text/x-magento-init">` the regex seems broken so would appreciate if anyone could take a look at it . This would then be the leading check for Magento 2 ( It's unique.. what's more to say ;-) ) 
The second checks for `static/_requirejs` in script tags, which is kind of unique to Magento 2 (haven't seen it before) but I don't think it should be the leading check. So I added it at 50% confidence.
We could create a third check which looks for `static/frontend` but I find that way too generic. So we might add it at 20% or lower.
> Added magento2 support

- src/apps.json
If I am understanding this correctly, this will match cookies named `*pyrocms*` which is how v2.* signals itself.
> Detect PyroCMS v2.*

- src/drivers/npm/index.js
Using the actual header-data allows to detect nginx, apache, etc. correctly now.
> Use headers instead of whole response (npm driver)

- src/wappalyzer.js
Wappalyzer is currently unable to properly inspect cookies inside the ```Set-Cookie``` header.
According to my tests, this issue manifests itself on the chrome and nodejs drivers. The Firefox and phantomjs drivers seem to be working as expected.
The following in an example output from the nodejs driver.
Example ```response.headers```:
```javascript
{ server: 'nginx/1.10.0 (Ubuntu)',
date: 'Wed, 07 Dec 2016 13:34:05 GMT',
'content-type': 'text/html; charset=UTF-8',
'transfer-encoding': 'chunked',
connection: 'close',
vary: 'Accept-Encoding',
'set-cookie': [ 'PHPSESSID=i6v6oqfmvj90h4st7bb0442b21; path=/' ],
expires: 'Thu, 19 Nov 1981 08:52:00 GMT',
'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
pragma: 'no-cache' }
```
The PHPSESSID cookie should match …
> Ensure regexes are applied to multi-value headers.

- src/apps.json
Remove the "env" property that could incorrectly match a function in the global scope. Removed the trailing 'v' from the "script" and "html" entries that looks for the BigCommerce CDN paths since they can begin with letters other than 'v' like 's' in the to examples below.
Check against the following URLs :
https://shopmonarch.averydennison.com/
http://shop.panthers.com/
> Fix #1325 - BigCommerce is wrongly detected

- src/drivers/chrome/js/driver.js
Convert string `'0'` to number `0`, see https://github.com/AliasIO/Wappalyzer/pull/1050
> Fix anonymous reports option in Chrome

- src/apps.json
- Speed up a regexp by adding `^`
- Add a header
This can be tested [here](http://www.lequipe.fr/)
> Improve a bit maxCDN detection

- src/apps.json
Added another parsing method for Roadiz CMS which can be recognized with `generator` tag and/or headers.
> Added Roadiz CMS X-Powered-By header.

- src/apps.json
Since those devices are printers that shouldn't be exposed on the
internet, I don't think that I should link webpages to test those rules
;)
Please find [attached](https://github.com/AliasIO/Wappalyzer/files/766757/brother.html.zip) a `curl -i $HOSTNAME` of a valid printer.
> Improve detection for Brother devices

- src/apps.json
This PR improves upon bootstrap detection by including an edge case.
The earlier regex was unable to detect bootstrap if the `<div` was followed by a tab. This PR fixes this issue.
> Improve Bootstrap detection

- src/wappalyzer.js
Currently, only `name` is considered as a valid key for <meta>,
but more and more website, trying to be mobile-friendly,
are using <meta> tags without `name`, but with a `property`
instead. This commit changes this behaviour.
This idea emerged from [this MR](https://github.com/AliasIO/Wappalyzer/pull/1321).
> Use `property` as `meta` key too

- src/apps.json
This triggered false positive  on the [Google Play
store](https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms&hl=en)
> Remove the matching on `Owa` in env for OWA

- src/apps.json
Fixed: false discovery of EdgeCast CDN on Node's servers using github.com/jfhbrook/node-ecstatic middleware
> Fixed false EdgeCast CDN discovery

- src/apps.json
I am not quite sure how `implies` works as far as inheritance.  CraftCMS is built off of the Yii framework.  The Yii framework is built off off PHP.
> Add additional implies for Craft CMS

- src/apps.json
Elm detection was based on the `Elm` pattern in `env`, leading to false
positives, as described [in the documentation](https://github.com/AliasIO/Wappalyzer/wiki/Specification#too-generic-patterns).
> Remove the Elm language detection

- src/drivers/phantomjs/index.js
When I install via NPM and run this as a library as described in the readme, I get an error saying that driver.js cannot be found.  This patch fixes the error by calculating an absolute path and passing that to phantomjs.
> use absolute path to driver.js

- src/drivers/webextension/js/driver.js
Chrome driver always sends response to foreground page to avoid foreground exception.
See #1487
This fixes #1487 and fixes #1489
> Chrome driver always sends response to foreground page

- docker/Dockerfile
This change will make the docker image lighter(smaller) and also make the build process faster!
- curl is builtin in phusion/baseimage, so there is no need to install it before nodesource
- nodesource script will do apt-get update, so there is no need to do it manually
- change security.ubuntu.com to use mirror site since it's very slow
- separate apt package dependencies into different line so they can be easily traced by git
- apt-get update cache clean up show be in the same layer of Docker image, or it'll not really work
> Refactor Dockerfile

- src/apps.json
- src/icons/Bootstrap Table.svg
Bootstrap Table is a JavaScript Library for extendended tables in Bootstrap. It has about 5,600 stars on [GitHub](https://github.com/wenzhixin/bootstrap-table) and can be loaded from [cdnjs](https://cdnjs.com/libraries/bootstrap-table).
> Add Bootstrap Table

- .travis.yml
As GCC v4.8 is already installed, there is no need to use ubuntu-toolchain-r-test ppa for it, then we can speed up every CI round!
> Move Travis CI to Ubuntu Trusty

- src/apps.json
OWL Carousel's site is now https://owlcarousel2.github.io/OwlCarousel2/
was http://owlgraphic.com/owlcarousel (reff: https://github.com/OwlCarousel2/OwlCarousel2/issues/1706 )
> Updated OWL Carousel's site

- src/apps.json
Meteor does not imply jQuery if you use `static-html` package instead of `blaze-html-templates` package in case you are using `React` for [example](https://guide.meteor.com/react.html#using-with-meteor).
> Fix Meteor implies

- src/apps.json
was discovered because one of our build tests started failing
> fixed missing quotes on Category for uCoz

- src/apps.json
- src/icons/Phenomic.svg
- src/wappalyzer.js
While working on https://github.com/AliasIO/Wappalyzer/pull/1652 I noticed I started having some issues testing the extension locally with Mozilla Firefox 55, namely that I could not see the extension icon anywhere. I was able to see it again after I fixed some syntax issues introduced in f61697c9f4a87574dd5ef4f462fe2d38b3c9237e in the wappalyzer.js file.
> Fix syntax issues in wappalyzer.js

- src/apps.json
Typecho has a global variable `TypechoComment` and it has a meta tag like WordPress.
> Update Typecho Checking

- src/apps.json
- src/icons/zeit.svg
Implements the detection of [now](https://zeit.co/now) and [Next.js](https://zeit.co/next).
> Add Zeit's now & next.js.

- src/apps.json
As discussed in #1680 and #1706, html rule is too broad. The other two rules should cover the detection sufficiently.
> Remove too broad rule for Next.js

- src/apps.json
The RaphaelJS website http://raphaeljs.com/ is dead, now the address is http://dmitrybaranovskiy.github.io/raphael/
> Fix RaphaelJS website

- src/apps.json
Magento is using `<script type=\"text/x-magento-init\">` to do fancy
javascript stuff, à la angular.
> Add yet another way to detect magento

- src/apps.json
As noted in https://github.com/AliasIO/Wappalyzer/issues/1432#issuecomment-287586126
Newer Sails.js versions send the header
x-powered-by: Sails <sailsjs.org>
instead of
x-powered-by: Sails
I tried to write a pattern that is hopefully more future-proof without generating too many false positives.
> Detect newer versions of Sails.js

- src/apps.json
This can be verified [here](http://blog.spang.cc/posts/hledger_rocks_my_world/). Apparently
people may put ikiwiki in the good ol' `/cgi-bin` folder instead of the root of their website. This makes sense, since ikiwiki is a big pile of Perl.
> Improve a bit ikiwiki detection

- src/apps.json
These can be automatically generated by the Google Closure Compiler (which will, if configured, replace global variables with auto-generated ones such as `aa`, `ab`, `ac` et cetera.) Hence, they are a less reliable
indication that a library which would also set said variable is present.
> Low confidence for 2-character environment variables

- src/drivers/npm/driver.js
If you run npm driver with --userAgent specified, it's not used and on request to the server used the default value of "Mozilla/5.0 Chrome/10.0.613.0 Safari/534.15 Zombie.js/5.0.7"
Moved userAgent init to the line of Browser() instance creation instead of require
> Fixed userAgent param doing nothing for npm driver

- src/apps.json
This can be tested [here](https://about.mattermost.com/blog/)
> Add a way to get gravityform's version

- src/apps.json
This syntax is used by wordpress, and can be tested [here](https://about.mattermost.com/blog/)
> Add an other way to get jquery's version

- src/apps.json
This can be tested [here](https://www.aviwell.fr)
> Add a way to get underscore's version, on Wordpress

- src/apps.json
This can be tested [here](http://www.barnivore.com/beer?vfilter=All).
There is no such thing as Ruby 5.X
> When phusion passenger gives a version number, it's not for Ruby

- src/apps.json
- HHVM implies PHP
- Mattermost can run on Postgre or Mysql, there is no point in showing them both at 50%, we don't do this for anything else
- If something is powered by ASP.NET, it's running ASP.NET
- If there is "Python" in a "Server" header, it's powered by Python
- RiteCMS is running on SQLite by default, it's the whole point of running this CMS instead of something more heavy
- JQuery is a mandatory dependency of typeahead
> Remove some useless "confidence" stuff

- src/apps.json
The original regexp was already suboptimal, but apparently, this is how everyone uses this javascript library. This can be tested [here](https://forum.openmw.org/)
> Add a way to get highlight.js version

- src/apps.json
The versions of mediawiki can be a bit strange,
especially on [wikipedia](https://en.wikipedia.org/wiki/United_Arab_Emirates),
since apparently the WMF has special ones. I've also seen `-beta`
sometimes (altough I don't have a website handy to prove it, sorry :/ )
> Improve mediawiki version detection

- src/apps.json
This can be tested [here](https://apnews.com/7f9e63cb14a54dfa9148b6430d89e873).
This url form is used on a lot of CDN.
> Add a way to get Font-awesome's version

- src/apps.json
Fix detecting of `sweetalert2.all.js` and `sweetalert2.all.min.js` which were introduced recently.
> Update SweetAlert2 to detect .all.js

- src/apps.json
- The website is now in https
- Tighten a bit the original regexp by prefixing it with a `/`
- Add a regexp to get the version, this can be tested [here](https://turtlapp.com/docs/)
> Add a way to get mootool's version

- src/apps.json
This can be tested [here](https://clang.llvm.org/docs/ControlFlowIntegrity.html)
> Add an other way to get mathjax' version

- src/drivers/webextension/js/driver.js
This pull request enables to use Wappalyzer in Firefox for Android, before the extension was not showing up because of this bug and I could not spot any error in the console.
However : 
- it is not possible to change the icon in the URL bar (cf https://bugzilla.mozilla.org/show_bug.cgi?id=1331746)
- the popup needs a bit of work to be clean in Firefox for Android
> Enable the use of W in Firefox for Android

- src/apps.json
This one is popular amongst CDN, and can be tested [here](https://www.ripstech.com/php-security-calendar-2017/)
> Add yet another way to detect bootstrap's version

- src/apps.json
I think that "database manager" must have higher priority than others categories like "misc", "operating system" ...
> Change database manager priority

- src/apps.json
This plugins is used a lot by lazy dev who don't want to upgrade.
This commit can be tested [here](https://www.tinyclues.com/)
I also updated two jquery-related links to https.
> Add jquery-migrate detection

- src/apps.json
The detection of the The Yoast SEO plugin implies the underlying site is powered by WordPress.
https://yoast.com/wordpress/plugins/seo/
> Yoast SEO implies WordPress

- src/apps.json
Craft’s `X-Powered-By` header could start including other details besides the product name, so all we should care about is that “Craft CMS” is in there somewhere.
> Update Craft CMS detection

- src/apps.json
Adding `jQuery.migrateVersion` for version detection via JavaScript: 
https://github.com/jquery/jquery-migrate/blob/180a4531d6efb0c28cbdcef32f0a9033506eac10/README.md#migrate-plugin-api
Example sites on which you can test:
- https://www.tsv-rannungen.de/
> Fix: jQuery Migrate detection

- src/apps.json
We can detect vbulletin version from the meta generator. A few example I have tested:
http://mydothelp.com/
http://www.mac-forums.com/macos-operating-system/336814-site-reached.html
https://vbulletin.web.tr/
http://www.forumefsanesi.com/
http://phillysportsforums.com/
> Detect Vbulletin version

- src/drivers/npm/driver.js
- src/drivers/webextension/js/inject.js
Fix bug spotted in #2031 :
When the matched element is a number it just returns "True" and not the number.
> Fix problem in version detection via js variables

- src/apps.json
According to [Angular branding guideline](https://angular.io/presskit#brand-names), AngularJS is referred to 1.x versions and Angular is referred to 2+ versions.
This reverts parts of #2037
> Angular and AngularJS is not the same

- src/apps.json
[Craft Commerce](https://craftcommerce.com/) is an e-commerce platform for Craft CMS websites. Its next release will start identifying itself via the `X-Powered-By` header, so it can be detected by Wappalyzer.
It’s currently running on a bit over 500 sites. Here are a few of them:
- https://fieldnotesbrand.com/
- https://barefootcontessa.com/
- https://cheerfullygiven.com/
- https://begladtraining.com/
- https://transformcorp.com/
- https://unitedslings.com/
- https://yveslegare.com/
- https://coldpresscoffee.com/
- https://www.jacketconcept.com/
- https://cunliffeandwaters.com.au/
- https://cfj.com.au/
- https://brink.uk/
- https://www.thirskracecourse.net/
- https://www.typemates.com/
- https://vfmk.org/
- https://www.weightcare.nl/
- https://www.uk-tefl.com/
- …
> Added Craft Commerce detection

- src/apps.json
OK, this may look familiar, since I sent a PR like this myself. (#2042)  But before it got merged an hour ago, @AliasIO merge `master` into my branch so that the line I intended to remove reappears. (https://github.com/AliasIO/Wappalyzer/pull/2042/commits/f79a6dd315924719b41bbf167f149cbfffaf33e9)
This fixes merge messed up in #2042.
Please be careful before merging.
> Remove `ng-version` detection from AngularJS

- src/apps.json
Mediawiki versions can contain a lot of different letters, like [`1.31.0-wmf.17`](view-source:https://en.wikipedia.org/wiki/Token_bucket), so there is no need to check for numbers specifically.
> Simplify mediawiki version detection

- src/apps.json
This can be tested [here](http://storm-country.com/blog/evo-deco), based on [this method](https://github.com/twbs/bootstrap/issues/16264)
> Add a new way to get bootstrap's version

- src/apps.json
This can be tested [here](https://blog.heroku.com/ruby-2-4-features-hashes-integers-rounding#better-hashes).
Please note that `algoliasearch` and `AlgoliaSearch` are both present on
the webpage
> Add a way to get algolia's version

- src/apps.json
This can be tested [here](https://cloud.scaleway.com/#/)
> Add a way to get socket.io's version

- src/apps.json
This can be tested [here]( http://guides.rubyonrails.org/security.html#regular-expressions )
> Add a way to get XRegExp's version

- src/apps.json
- Better version detection (the `ab` thingy looks like a bug to me)
- Tighten the regexp for the generator
- Tighten the `script` thingy
- The website is using https
This can be tested [here]( http://www.nextprivacy.ch/fr/solutions/outils/ )
> Improve Concerte5 handling

- src/drivers/npm/driver.js
This code iterates a list of links 5 times -- 1 to `from`, 3 to `filter`, and then 1 to `map`. This can be simplified into one `reduce` which iterates the list once.
> Using `reduce` to remove extra iterations

- src/apps.json
This can be tested [here](https://stripe.com/atlas/guides/business-of-saas)
> Add a way to get Stripe's version

- src/apps.json
- Add a `js`-based detection
- Simplify the `script` pattern
- The `script` can now get the version
> Improve a bit highligthjs detection

- src/apps.json
This can be tested [here](http://docs.python-requests.org/en/master/)
- remove the `rc` thingy, since no other patter using it, and I haven't seen a
single website actually using it.
- jquery-migrate is valid too
- Remove `.*` in favour of of an optional `.min`
> Improve jquery migrate and jquery mobile detection

- src/apps.json
The rationale for this commit is that when you're putting content on github
pages, the underlying blog engine is Jekyll, or anything else that you might
use to generate static html. Github pages are only the things that is serving
your pages, aka a content delivery network.
> Github pages are now only a CDN, and not a blog

- src/apps.json
This PR adds the detection for the bootstrap.js javascript framework for bootstrap.
Source: https://getbootstrap.com/docs/3.3/javascript/#js-version-nums
> bootstrap: added version detection

- src/apps.json
> Fix a critical typo in `particules.js` detection.

- src/apps.json
Adds the version detection for the Soundmanager.
Example URL: a slack workspace
Example version string to verify that the regexp works: `V2.97a.20150601 (HTML5-only mode)`
And yep, the version stored in `soundManager.version` not in the camel case one.
> SoundManager: added version detection

- src/apps.json
Those % characters are unnecessary and could break compatibility.
> Removed % characters in confidence number.

- src/apps.json
This can be checked [here]( https://www.amazon.com/M-Audio-AV32-1-Professional-Multimedia-Audio-Monitor/dp/B017340ZVE )
> Add an other header to fingerprint cloudfront

- src/apps.json
E.g. tag code as follows:
```
<script type="text/javascript">
var sc_project=12847410; 
var sc_invisible=1; 
var sc_security="cad283e9"; 
var sc_https=1; 
var scJsHost = (("https:" == document.location.protocol) ?
"https://secure." : "http://www.");
document.write("<sc"+"ript type='text/javascript' src='" +
scJsHost+
"statcounter.com/counter/counter.js'></"+"script>");
</script>
```
> Statcounter detection was missing cases where script tag was output via document.write

- src/apps.json
Medium is a [blog](https://en.wikipedia.org/wiki/Medium_(website)), but is in the CMS category with Wappalyzer. I corrected that.
> Fix bad category for medium.com

- src/wappalyzer.js
The content variable being in the function-level-namespace led to it being changed before the  asyncForEach with pattern.regex.test(content[2]) was called, leading the wrong results.
> fix meta detection

- src/apps.json
Regex for script detection on YII Framework section prupose to much false positive, as prupose on https://github.com/AliasIO/Wappalyzer/pull/2246 is better to just delete it.
> remove regex for YII Framework

- src/apps.json
- The x-powered-by header is trustworthy for ASP
- The `server` header for IIS always starts with `IIS`
> Tighten a bit asp and iis detection

- src/apps.json
This can be tested [here]( https://whotracks.me/blog/generating_adblocker_filters.html )
> Add a way to get plotly version

- src/drivers/bookmarklet/driver.js
Use the same code than in the WebExtension driver to extract HTML
> Fix for #2271

- src/drivers/npm/driver.js
fix npm driver boolean arguments - Boolean("false") or Boolean("0") is still true, arguments were always true if they were included in the cli independent of values
to test
node index.js http://github.com --debug=0 - debug output
node index.js http://github.com --debug=1 - debug output
node index.js http://github.com - no debug output
same with recursive.
> fix npm driver boolean CLI arguments

- src/wappalyzer.js
Running the Wappalyzer js in the context of a page fails when Array has been extended.  Granted, all bets are off and you're a lot better off running in a sandbox like the extension but this adds some resilience for cases I have found.
The indexof > -1 (instead of !== -1) change fixes running in http://drmehrabian.com/ where indexof was returning undefined when not found instead of -1.
The cases where typeof is checked to make sure it is not a function when enumerating array keys fixes cases where Array has been extended and the new prototype overrides return as part of the object keys.  Specifically, http://www.tonybuzan.com/ which uses [Prototype.js](http://prototypejs.org/).
These changes will help when running in the bookmarklet case (as well as WebPageTest which runs the check within …
> Add resilience for cases where Array has been extended

- src/drivers/npm/driver.js
Before the fix, it was gathering all the urls from facebook twitter etc and crawling them
fixing #2316
> npm driver fix url filter in recursive mode. allow only urls from the same host

- src/apps.json
Since lodash and underscorejs are both using `_`,
the presence of `_.VERSION` shouldn't be used
as anything else but a provider of version number
> Complete a0cc689e1dff9a96baf3d0488433b89d320fb062

- src/drivers/npm/index.js
- src/drivers/npm/package.json
Wappalyzer can be executed as "wappalyzer <url>" instead of "node index.js <url>".
> Add "wappalyzer" command (bin)

- src/apps.json
This can be validated [here](https://wiki.gnome.org/Initiatives/DevelopmentInfrastructure<Paste>)
> Detect moinmoin wiki via its cookies

- src/apps.json
PR #2252 removed the script detection because it erroneously matched `https://static.xx.fbcdn.net/rsrc.php/v3/yD/r/vt21ayiiNKR.js`
I have updated the detection so it won't match that but will match the following
```
<script src="/assets/74f24751/yii.js"></script>
<script src="/assets/74f24751/yii.validation.js"></script>
<script src="/assets/74f24751/yii.activeForm.js"></script>
```
Edits and recommendations to the Regex are welcome.
> Update script detection for Yii framework

- src/apps.json
Because you can't really find out what "UA" means if you google it.
> Write "Universal Analytics" in full

- src/wappalyzer.js
The confidence of a pattern is parsed as a string.
For example:
If two matching patterns have the confidence of 10, the confidenceTotal will be calculated by `'10' + '10'`, which will return `'1010'` and Wappalyzer will show it as 100% confidence and not the expected 20%.
> Fix confidenceTotal

- src/apps.json
The reason is that now.sh started using 'cloudflare' header but also have own and wappalyzer can recognize them.
> add more now.sh detectors

- src/apps.json
This can be verified [here](https://doar-e.github.io/blog/2018/07/14/cve-2017-2446-or-jscjsglobalobjectishavingabadtime/)
> Add a pattern for old-school pelican setups

- src/apps.json
Phusion passenger is used for Ruby, nodejs, Python
as well as other exotic things, there isn't a 50% chance of Ruby being
used when it's detected.
On the other hand, if `mod_rails` or `mod_rack` is present,
we can be certain that there is indeed Ruby on Rails behind
the website.
> Tighten a bit RoR detection

- src/drivers/npm/npm-shrinkwrap.json
- src/drivers/npm/package.json
**What is the issue?**
zombie@5.0.8 uses lodash@3.10.1 which has a vulnerability issue
- https://nvd.nist.gov/vuln/detail/CVE-2018-3721
- https://github.com/Woorank/wappalyzer-wrapper/network/dependencies
**What does the PR fix?**
Update zombie to latest that uses lodash@4.17.10 where vulnerability is fixed.
> Update zombie that uses lodash@4.17.10

- src/apps.json
Updating the link to ExtJS website (now Sencha), as well as updating the mechanism to detect older versions of the framework (specifically 2.x and 3.x)
> Updating ExtJS

- src/apps.json
- Detect legacy version of jquery version.
This can be tested [here](https://snuffleupagus.readthedocs.io/features.html)
- Fix the regexp in the `script` detection
> Improve the detection of jquery-migrate

- src/apps.json
Removed seemingly unnecessary capturing group and non-numeric version tag in Google Analytics pattern to prevent falsely reporting "analytics" or "Universal Analytics" as a version identifier.
I understand that there are `classic` (deprecated) and `universal` flavors offered (at some point) by Google so if you want this split into two different patterns let me know and I can tackle that too. However, with this not being what the majority in the IT industry would classify as a "version" identifier I figured this was a safe way to go.
Fixes AliasIO/Wappalyzer#2419
> Fix Issue 2419

- src/apps.json
Improved netlify detection #2434
All the netlify websites contains x-nf-request-id param on headers
> Netlify detection improved

- src/apps.json
This is documented [here](https://cookiepedia.co.uk/cookies/bbsessionhash) and [here](https://www.trafford.gov.uk/residents/Cookie-policy.aspx) and can be tested [here](https://www.mobileread.com/forums/showthread.php?t=284418).
> Improve the detection of vBulleting via cookies

- src/apps.json
- Plesk-related headers values are always starting with "Plesk"
- Plesk can run on Windows
- Plesk's website is using https
> Improve a bit Plesk-related things

- src/drivers/webextension/js/lib/iframe.js
Fix bug with unexpected coma after the last function parameter
Google Chrome console error:
``` iframe.js:143 Uncaught SyntaxError: Unexpected token ) ```
> Delete unexpected coma

- src/apps.json
- Generator always starts with "Silverstripe
- The website is in https
- Silverstripe is written in PHP
> Improve silverstripe a bit

- src/apps.json
This commit corrects the following for BoldGrid detection:
* Use the proper name of the CMS
* Add additional `link` as the schema may differ between old and modern versions
* ~Remove improper `script` detection~
> Improve BoldGrid detection

- src/apps.json
There might be some trailing text after "Apache-Coyote",
like on <https://espace-client.sfr.fr/services-web/>
Also, the 4.1+ thingy is useless, often confusing,
sometimes wrong, and is a bit irrelevant in 2018 since
Tomcat 4.1 was declared stable in 2002,
with its last release in 2009.
> Relax a bit tomcat detection

- src/apps.json
I don't know if it's new, but webserver return `Microsoft-IIS/8.5` in the `Server` header and not `IIS[0-9]+`. 
You can find an example here : https://login.live.com/
> Fix IIS regex

- src/wappalyzer.js
- src/wappalyzer.spec.js
Right now analyzeCookies can't handle cookies with uppercase cookie names, such as `AFRAME.version` for A-Frame (since it looks for the lowercase name in `patterns` on line 634). This is a quick fix for that.
> [bug fix] Allow analyzeCookies to check for cookies with Uppercase names

- src/wappalyzer.js
I'm not sure if this is an error or not, sorry if it isn't.
But js confidence calculation was different from cookie and headers and meta by not providing a key value, even though it has the same schema of a dict in apps.json as headers/cookies/meta
Maybe I'm not seeing something and you can't use string variable name here.
> Fix? js confidence calculation

- src/apps.json
Url can end is `.asp` and not only `.aspx`,
as on http://www.assemblee-nationale.fr/15/cr-cdef/17-18/c1718070.asp
> Improve a bit ASP detection

- src/apps.json
This can be verified [here](view-source:https://www.konbini.com/fr/entertainment-2/tommy-wiseau-rejoue-joker-cest-mauvais-the-room/amp/)
> Detect Google Analytics if AMP is used

- src/apps.json
This technology is not detected on all sites that use it. 
For example, it is detected on this site (https://draftjs.org/) but not on this one (https://docusaurus.io)
With this improvement, it is detected at more sites.
> improve detection docusaurus

- src/apps.json
- The server header always _start_ with Netlify
- Change the capitalization of the x-nf-request-id header
> Tighten a bit nelify detection

- src/apps.json
- Wappalyzer is now able to detect localized fluxbb forums, like [this one](http://www.hellfest-forum.fr/)
- use https for the website
> Improve FluxBB detection

- src/apps.json
This can be tested [here](https://www.computerworld.com/article/3288925/computer-hardware/as-bitcoin-values-slide-high-end-gpu-prices-drop-too.html)
> Add detection of apache coyote detection

- src/apps.json
This can be tested [here](https://www.computerworld.com/article/3288925/computer-hardware/as-bitcoin-values-slide-high-end-gpu-prices-drop-too.html)
> Improve fastly detection

- src/apps.json
RoR [usually](https://www.google.com/search?hl=en&q=_session_id%20cookie) sets a _session_id cookie
> Improve a bit RoR detection

- src/apps.json
This can be tested [here](view-source:https://www.konbini.com/fr/entertainment-2/tommy-wiseau-rejoue-joker-cest-mauvais-the-room/amp/)
> Detect wordpress sites, even if they're using amp

- src/drivers/npm/driver.js
The htmlMaxCols and htmlMaxRows related regex can take a lot of time, this PR implements a shortcut to ignore that functionality when htmlMaxRows and htmlMaxCols is set to 0. 
This one also solves the problem with #2530 as far as I can tell.
> Remove split / concat when htmlMaxRows and htmlMaxCols is 0

- src/apps.json
> This value overrides the default <style> tag attribute, data-styled (data-styled components in v3 and lower). 
It looks like the newer versions of styled-components use `data-styled` instead of `data-styled-components`:
Live example: https://kepinski.me (my site)
I think it would be a good idea to keep the old detection too, but I don't know how to use 2 HTML detections at once :cry:
> Update styled-components detection

- Dockerfile
`MAINTAINER` instructions is [deprecated](https://docs.docker.com/engine/reference/builder/#maintainer-deprecated), should use `LABEL` instead `MAINTAINER`.
> Change MAINTAINER to LABEL instruction

- src/apps.json
Hello.
Have a nice time
Please add Webzi to apps.json
300 websites are built using Webzi.
Webzi Logo: https://webzi.ir/logo.svg
Check dns lookup
http://reversens.domaintools.com/search/?q=webzidns.ir
Sample sites:
http://iefm.eu
http://nikaniroo.com
https://paverzz.com
http://pishrooabrpars.com
https://veggie-snack.com
http://deltatechnicalgroup.com
https://berenjonline.com
http://coopalbag.com
http://mehrakco.com
http://banesell.com
http://amoghnad.com
http://dekland.com
https://fardingraphic.ir
http://mohsena.ir
http://samashimi.ir
http://yasilyol.ir
> Add webzi site builder

- src/apps.json
> Fix Botble CMS's version detection

- src/apps.json
fixes #2655
Replace the Acquia.com URL (which is a web hosting company) with the WordPress plugin URL.
> Update All-in-One SEO url

- src/apps.json
If a server configuration is using the rocket-nginx configuration, we can use this as an alternative fingerprint detection.
https://github.com/maximejobin/rocket-nginx
fixes #2661
> WP Rocket - Add Rocket Nginx bypass header detection

- src/apps.json
- src/icons/platformsh.svg
Platform.sh is a cloud PaaS provider for application hosting (similar to Heroku, Now, Acquia, Pantheon, and others) who is currently the dedicated hosting partner for Magento Commerce Cloud (aka Magento Enterprise). Platform.sh utilizes AWS and Microsoft Azure as their infrastructure backbone, but it’s difficult to imply either since it seems to be based on region.
- https://platform.sh
- https://github.com/platformsh
- https://www.britishcouncil.us
- https://www.centarro.io
- https://commerceguys.com
- https://drupalcommerce.org
- https://www.rossignol.com/us
- https://egoshoes.com
- https://www.ospreylondon.com
Most sites running Magento Commerce Cloud will be running on Platform.sh.
https://magento.com/case-studies?product=magento-commerce-cloud
> Add Platform.sh

- src/apps.json
- Change category to PaaS
- Add Apache, Percona, and Amazon EC2 to implies based on their architecture page.
fixes #2670
> Update Acquia metadata

- src/apps.json
This replaces the loose HTML lookup (which just looks for a link with "OpenCart"), which is why it shows up in Google because it's in a search result.
Instead, we can use the OCSESSID cookie that's issued by OpenCart.
**Fixes Google search results**
**Works in OpenCart demos**
fixes #2650
> Fix OpenCart false positive

- src/apps.json
Because the previous hoster decided to disband itself, Doxygen moved to its own domain. Site linked on https://github.com/doxygen/doxygen
> Update Doxygen homepage

- src/apps.json
- src/drivers/npm/npm-shrinkwrap.json
Followup to email from @rviscomi about [Web Almanac](https://github.com/HTTPArchive/almanac.httparchive.org)
Updates Shopify detection with:
- Reduced confidence with file references to `cdn.shopify.com`
- Reduced confidence with declaration of `window.Shopify`
- Look for `x-shopid` and `x-shopify-stage` headers
- If origin is `myshopify.com`, then we know the website is built with Shopify.
This should also remove `shopify.com` websites (used for Shopify marketing) from detection -- does that make sense for Wappalyzer?
I ran `./run validate` but had several errors from other applications that I didn't touch? 🤷‍♂️
> Update detection for Shopify storefronts

- src/apps.json
Add detection for sites running the official AMP plugin for WordPress: https://amp-wp.org/
Not sure about the best categories, so right now it's just re-using the WordPress categories.
This PR also removes the `<div[^>]*class=[\"']amp-wp-` check from the WordPress detection, as it seems overly suspect to false positives.
> Add official AMP plugin for WordPress

- src/apps.json
The AMP detection causes false positives with sites that didn't have the amp attribute in the `<html>` tag, but loaded an AMP related script, as AMP's JS adds dynamic amp-* attributes to the `<html>`.
This also updates our name (now just AMP), and the website (now amp.dev).
> Make AMP detection slightly more robust

- src/drivers/npm/driver.js
- Also check in the case when results are undefined or not of array type
- Only logs error and skips. Throw Error/Catch returns no data
- fixes #2694
> Check for HTMLAnchorElement properties on links

- src/apps.json
- There’s no defining characteristic to determine whether Ant Design is React or Vue, so it’s best to check those on their own fingerprints and leave Ant by itself.
- fixes #2680
> Remove collision between Ant Design (React vs Vue)

- src/apps.json
Noticed styled hasn't been being registered on most of the projects I use it on.   On SSR projects, all of the generated hashed classes will have the following declaration:
Example:
`/* sc-component-id: sc-1v848in-0 */`
> Update styled-components identification on injected CSS

- src/apps.json
- src/icons/Arc-Publishing.svg
Here a number of sites that are powered by Arc:
Naturally: https://www.washingtonpost.com/
https://www.nzherald.co.nz/
https://www.inquirer.com/
https://www.rtl.de/
https://www.bostonglobe.com/
https://www.theglobeandmail.com/
https://www.chicagotribune.com/
https://www.sailingworld.com/
https://www.popsci.com/
https://www.wakeboardingmag.com/
> Adding Arc Publishing to Technologies

- src/apps.json
Correction to detect Crossbox via the "server" header.  The current HTML match doesn't work for the white-labeled instances.
> CrossBox fix

- src/apps.json
Hi @AliasIO ,
Finally, I could see the resultant detection from yesterday, but those results were listing out few wrong detection of technologies as well. Therefore, I have added the optimal html pattern now which will help me to detect the exact technologies. Can you please merge it to help me in retrieving the exact matching list of technologies. Thanks in advance for your help.
Modified pattern is to match the HTML elements with the exact class names including both the terms "e-control" and "e-lib" as mandatory. Previously mistook that the word boundary were not supported and therefore, now corrected it.
Ensured now using the puppeteer. Apologize for the inconveniences.
Regards,
C. Uma Maheswari
> Apps.json file modified due to wrong detection of technologies.

- src/apps.json
- src/icons/SimpleAnalytics.svg
1. [AppZapper](https://appzapper.com/)
1. [Pieter Levels](https://levels.io/)
1. [ReviewBot Blog](blog.reviewbot.io)
1. [Graphite Docs](https://www.graphitedocs.com/)
1. [MAKE: Bootstrapper's Handbook](https://makebook.io)
1. [Byrdseed](http://www.byrdseed.com)
1. [Work and Whistle](https://workandwhistle.co)
1. [Maker Weekly](https://makerweekly.co)
1. [Fable](https://www.fable.co)
1. [Curiosities and Puzzlements](https://puzzlements.co)
> Add Simple Analytics

- src/apps.json
- Added new headers that can be detected
There are a few new WP Engine specific headers that are exposed to use for additional detection.
`x-pass-why` is specific to a [cache control plugin](https://wordpress.org/plugins/wpe-advanced-cache-options/) used only for WP Engine, in addition to this loopback header.
> Update WP Engine detection

- src/apps.json
- src/drivers/webextension/manifest.json
Hello,
I noticed that, on some websites, the ClickFunnels detection wasn't working.
Example :
- https://go.iag-media.com/kaizencure
It's because of the fact that their scripts' src are not using clickfunnels domain but their one, therefore the detection of clickfunnels using those scripts isn't working.
Here is another fix that should work on every clickfunnels website.
> Better Click Funnels Detection

- src/apps.json
I am Enterprise Architect at Intershop Communications AG. We provide a digital commerce platform:
https://www.wappalyzer.com/technologies/intershop
We have recently updated our product and use now a progressive web app based on Angular.
However, with this technological change, Intershop is not recognized by Wappalyzer anymore.
Therefore I added the detection of the Intershop PWA based on the  “&lt;ish-root&gt;” element. ISH is the abbreviation for Intershop, the Xetra Stock symbol is ISH2.
Here an example of an Intershop client already using the Intershop PWA:
https://shop.zeiss.de/
Thanks
Nils
> Added support for the new Intershop progressive web app

- src/apps.json
Carbon Ads now uses *cdn.carbonads.com*, which isn't matched yet. This pattern will match all scripts loaded from carbonads.com and any subdomains. HTTP, HTTPS and protocol-relative URLs will match.
Not overly broad because the informational website is at carbonads**.net**
> Improve Carbon Ads script pattern

- src/apps.json
The variable `webtrekk` is only present on a few websites, it seems.
Adding a bunch of other Webtrekk variables to improve detection
> Improve webtrekk detection

- src/drivers/npm/README.md
capitalization fix -
while class Wappalyzer defines “this.browser = ZombieBrowser;” its constructor returns instance of Driver, that defines “this.Browser = Browser;”
> fix example in npm readme.md

- src/apps.json
I  don't think `__gwt_` actually exists as a variable (leaving it around just to be sure). Adding some JavaScript variables that *do* exist.
> Improve Google Web Toolkit detection

- src/apps.json
A non-capturing group was accidentally not marked as optional
Also make it a little more strict by ensuring there is a ` ` or other whitespace before the attribute
> Fix HTML pattern for Vue.js

- src/apps.json
- src/drivers/npm/npm-shrinkwrap.json
TYPO3 CMS is not properly recognized when the resources are loaded using absolute URIs.
In order to prevent this, an optional slash has been added to the checks for `link`, `img` and `script` tags.
Also an additional rule to check if the source code contains the famous "This website is powered by TYPO3" comment at the top.
The JavaScript function `decryptString` is used by TYPO3 CMS to decrypt encrypted `mailto:` urls in the page and is available at any time. I'm pretty confident that TYPO3 is the only CMS using this function with this name but I'll gladly be proven wrong if anybody knows something else. If that's the case, we could change the confidence to 50 or less (or remove this check completely).
> [TASK] Add some additional checks for TYPO3

- src/apps.json
As of version 1.0, jQuery is no longer a dependency of Materialize.
> Update Materialize implications

- src/apps.json
Websale AG doesn’t have "websale7" in URL anymore, instead we can use cookies. Can You please update the source code?
> Changes for Websale-Recognition

- src/apps.json
Changed	`(?:<other patttern>|<pattern with version detection>)`
To	`(?:<pattern with version detection>|<other pattern>)`
> Fix Symfony version detection

- src/apps.json
1. _PHPoole_ is no more supported
2. The next release of _Cecil_ will embed version number in the `generator` meta
> Catch Cecil version

- src/apps.json
A new version 6 of Shopware got released, this PR adds support for that (and updates the website link).
A demo shop: https://friendsofshopware2.shopwaredemo.store/
Sites using Shopware 6 are:
- https://www.click-six.de/
- https://www.clew.de/
> Add detection patterns for Shopware 6

- src/apps.json
- src/icons/datocms.svg
I'm suggesting to add DatoCMS to the list of recognised CMSs.
Here's a list of sites using Dato: https://www.datocms.com/use-cases/
The core of DatoCMS is closed source so I cannot reference anything there, but if you need more info please ask. I think in general is worth to add as we are currently counting more than 10k projects started and we are steadily growing with numbers.
Thank you!
> Add DatoCMS

- src/apps.json
In December 2019, WP Engine added the `X-Powered-By: WP Engine` response header and removed the `wpe-backend: *` header.
I left the old headers in but can remove them if preferred.
> Added X-Powered-By: WP Engine header

- src/apps.json
The `October CMS` detection was not working due to a `=` in the cookie name. Now fixed.
> October CMS detection fix

- src/apps.json
Ionic moved from Angular component to [Web Component](https://ionicframework.com/#agnostic),
so Ionic app can be build with Angular, React, [Stencil](https://stenciljs.com/) (Web Component compiler) and soon Vuejs.
> Remove Implies Angular for Ionic

- src/apps.json
The custom domain is no longer available, the homepage has been moved to the GitHub pages.
> Fix homepage link for `Catberry.js`

- src/apps.json
Remove the ^ token because somes site use full scheme
> Fix Hotjar script regex

- README.md
The current link (https://www.wappalyzer.com/docs) is no longer available. Shows a 404 not found.
This has been substituted with right link at https://docs.wappalyzer.com/
> Link to documentation in README.md fix

- src/apps.json
`./run validate` is throwing the error because of the icon name case:
```
Validating icons...
/opt/wappalyzer/bin/validate-icons:45
throw Error('Missing file for app "' + app + '": src/icons/' + iconPath);
^
Error: Missing file for app "phpCMS": src/icons/php.svg
```
> Fixed PHP.svg icon case for phpCMS

- src/apps.json
fix for https://github.com/AliasIO/wappalyzer/issues/2940#issuecomment-589302219
improved WHMCS detection based on js detection instead of cookies
> improved WHMCS detection

- src/apps.json
- src/icons/vercel.svg
- src/icons/zeit.svg
(The company name and the product name are now unified, which makes the "Now" naming obsolete too.)  
`x-now-trace` seems to be unchanged.  
The SVG is taken from [the official page](https://vercel.com/design/vercel) and the only difference seems to be the fact that the very subtle gradient was removed.
> ZEIT changed its name to Vercel

- src/apps.json
I've been analyzing React usage via HTTP Archive + Wappalyzer and noticed a lot of false positives (sites that don't actually use React but show up in results).
They all seem to have something in common, a Google Adsense script that fails one of the script regex checks:
<pre>
pagead2.googlesyndication.com/.../<b>react</b>ive_library_fy2019.js
</pre>
Interestingly enough, many of these sites only include this script on mobile and not desktop. The Wappalyzer chrome extension doesn't seem to pick this inconsistency up, but this PR should fix this and improve the check :)
> Improves React script check

- src/apps.json
Changes all `implies` arrays that only had one item to use string syntax instead. 
If you'd prefer to always use array, just let me know and I'll update the PR.
> Always use string for implies with only one item

- src/apps.json
- **ElementUI** was implying `Vue` instead of `Vue.js`.
- Vue's website link was not using `https`.
> Update Vue.js metadata

- src/apps.json
The regex pattern from PR #3056 would match `<div x-data>`, but it would also match `<div lightbox-data>` and gave a lot of false positives. 
This PR fixes that problem, lowers the confidence slightly for html match and adds additional methods of identification.
> Improve Alpine.js detection

- src/apps.json
In most cases, the `X-Powered-By` header contains the version of OTRS.
> Detect otrs version by X-Powered-By header

- src/apps.json
**Regex Expression**
`[^>]*class=\"[^\"]*(?:sm:|md:|lg:|xl:)`
The regex expression detects if there are any class names starting with either "sm:", "md:", "lg:", or "xl:" within the HTML. 
These class name prefixes are heavily used in websites using [Tailwind CSS](https://tailwindcss.com/), as they denote breakpoint styles.
> Add Tailwind CSS identifier

- src/drivers/webextension/_locales/en/messages.json
This pull requests corrects the `Developmentl` category name to `Development`.
> Fix "Developmentl" typo

- src/apps.json
- X-Pingback via xmlrpc.php is specific to wordpress
- the shareaholic plugin is also a nice way to detect it
> Improve a bit wordpress detection

- schema.json
Sorry I missed this in the[ previous PR](https://github.com/AliasIO/wappalyzer/pull/3095). Correct 'sting' should be 'string'
> Fix Schema Typo

- src/apps.json
RebelMouse, a WordPress-like CMS, uses specific caching headers for their service which can be detected.
> Add RebelMouse specific header detection

- src/apps.json
Was triggered on "rectangular[several KiB of minified script].js"
Now requires a word boundary before "angular" and allows max. 32
characters between that and ".js"
> Fix overly broad Angular detection

- package.json
- src/drivers/npm/driver.js
- src/drivers/webextension/js/content.js
- yarn.lock
@AliasIO
Fix #3204
- 04aa67964f9058305471d5fc8a3fac637f6ad6b5 **Yarn:** `yarn add languagedetect` (Fix `Error: Cannot find module 'languagedetect'`)
- 9a53d48f4155ada54d7838ad7800277bee85a93d **WebExtension:** Remove hash from url (Fix the bug of not showing popup when the url contains hash, such as [`https://github.com/AliasIO/wappalyzer#readme`](https://github.com/AliasIO/wappalyzer#readme))
- b132d3b3cf203a2a8d5c369b104b97b0b5685d35 **Node:** Remove hash from url (Fix `NO_RESPONSE` of `node src/drivers/npm/cli.js https://github.com/AliasIO/wappalyzer\#readme`)
> Fix the bug of not showing popup when the url contains hash

- src/apps.json
Fix the detection of older versions of MediaWiki (`wg`), such as <https://wiki.mbalib.com>.
```json
"js": {
"mw": "",
"wgTitle": "",
"wgVersion": "^(.+)$\\;version:\\1"
}
```
> Improve MediaWiki Detection

- src/apps.json
Wordpress will often have its version exposed through a script tag such as the following:
 
```
<script type='text/javascript' src='https://.../wp-includes/js/wp-embed.min.js?ver=5.4.2'></script>
```
> Add wordpress version detection from scripts

- src/wappalyzer.js
Fixed an issue with the slugify method. 
Currently if you input `"-some string-"` you get `"some-string-"` when you expect to get `"some-string"`.
This PR fixes this issue by adding a global flag on the last replace regex in the slugify method.
> Fixed regex in slugify method.

- src/technologies.json
Removing version detect for the `Apache-Coyote` Header because its producing false version numbers.
- fixes #3305
> Tomcat version bug

- src/technologies.json
This PR does the following:
- Refines the detection of GOV.UK Frontend as we were getting lots of false positives off copy / pasted cookie banners
- Adds the detection of GOV.UK Frontend's version number if a service team is using the `dist` version of the CSS or JS
- Adds detection of three other GOV.UK Products: GOV.UK Template, GOV.UK Elements, GOV.UK Toolkit
- All products are now use the 'UI Frameworks' category, rather than doubling up in 'Miscellaneous'
> Add support for other GOV.UK products and refine detection of Frontend

- src/technologies.json
CherryPy appeared twice in the file, and CloudFront seemed to have two description elements.
There's probably a way to validate this vs the schema but I haven't had time to look into it.
> Remove Duplicates

- src/technologies.json
Detecting googletagmanger with url `googletagmanager.com/gtm.js`
- fixes #3355
> Improving Google Tag Manager Detection

- src/technologies.json
Hi guys, 
while trying to load your latest version with python's json module, I got the following error: "JSONDecodeError: Expecting value: line 7193 column 7".
If you remove only this one trailing comma, it works like a charm. 
Hope this change will be okay for you. 
Thanks in advance & greetings
> Remove trailing comma (invalid JSON)

- src/technologies.json
Google Fonts uses Angular, but Angular is not detected. However, Zone.js is, which is a part of Angular.
> Zone.js implies Angular

- src/technologies.json
Version number detected but only returns `a` because of typo copied from example in docs.
Apologies for this minor update, I'm frustrated I didn't spot it sooner.
> Fix typo in GOV.UK Frontend version number

- src/drivers/npm/driver.js
https://github.com/AliasIO/wappalyzer/issues/3445
> #3445: Close timers after resolving/erroring the `dns.*` promises

- src/drivers/webextension/images/icons/AOS.svg
- src/technologies.json
Add AOS detection as requested by honjes in #3350 
AOS has 14k stars, https://github.com/michalsnik/aos, so should meet notability requirements 
Works on all of the sites here https://trends.builtwith.com/websitelist/AOS 
Added the confidence for "js" as AOS is kinda short and may have conflicts with minified code, but should be rather safe if all 3 of the methods are there﻿
> feat(AOS): add AOS (#3350)

- src/technologies.json
Fix following error:
```
$ yarn run validate
yarn run v1.22.10
$ yarn run lint && jsonlint -qV ./schema.json ./src/technologies.json && node ./bin/validate.js
$ eslint --fix src/**/*.js
File: src/technologies.json
Parse error on line 11266, column 16:
...  },    "Rakuten": {      "cats": [  ...
----------------------^
/technologies/Rakuten should NOT have additional properties; see #/properties/technologies/additionalProperties/additionalProperties
```
Rakuten had a duplicate entry﻿
> fix(Rakuten): duplicate Rakuten entery

- src/technologies.json
- removing js detection for `sweetalert` cause its used for `sweetalert` and `sweetalert2`
- adding scripts that can be detected for `sweetalert` and `sweetalert2`
- fixes #3506
> Fixes false positives for sweetalert

- src/technologies.json
Related to issue #3509, as axios is already being detected, I just added a new check to help improve a lot of missed detections
Also moved to a better category
Axios has no logo, so did not add a logo﻿
> Axios improve + move from misc to JavaScript lib

- src/drivers/webextension/js/driver.js
Fix to #3529 
In this commit: https://github.com/AliasIO/wappalyzer/commit/3097ddcde8479980f0929bf61b9bc07749433a84#diff-3a09560d3fab721a41189cfa740746e5f2ee1d7562d30fd862f17d4df9f517ec `ads: await getOption('ads', []),` got replaced with `{}`
Since line 463 had `Driver.cache.ads.push(ad)`﻿it is not going to be able to push to an object
Here is the error that caused it to throw an error when visiting websites:
> Fix runtime.lastError

- src/drivers/webextension/images/icons/WebAssembly.svg
- src/technologies.json
I wondered whether watching a Content-Type or a extension, but I choose the former. Because after I saw codes roughly, I noticed implement of "scripts" make browser evaluate a script. I don't know can browsers evaluate wasm byte-codes directly, but I tried it and it worked. Though it seemed strange action, so I decide to watch headers.
> Add WebAssembly

- src/technologies.json
Hey guys,
using wappalyzer recently I discovered, that a lot of times websites get marked as Atlassian Confluence AND Jira. However, only the Jira technology is capable of finding a version and the Confluence was not.
This is happening, because both applications have the "ajs-version-number" (which is stated within the Atlassian Jira app rule). As well, the provided html-regex ("Powered by...") is not working - at least on pages I encountered. Tested it as well manually.
So my suggestion for lower false-positives would be:
- Remove "ajs-version-number" from JIRA - because both apps have it.
- Jira pages have one attribute within a meta-tag and the body-tag: "data-version", which we can take advantage of -> therefore changed the html-regex
- Confluence pages have in addition to "Powered by …
> Improve Confluence vs Jira detection

- src/technologies.json
Actually Docusaurus is static generator website. Of course, it is used a lot as a tool for creating documentation. But with [v2](https://v2.docusaurus.io/), which many people are already using, Docusaurus has become a full-fledged SSG.
сс @AliasIO
> Add Docusaurus to the SSG category

- src/technologies.json
The meta generator value of the second (new) version of Docusaurus looks like this: `Docusaurus v2.0.0-alpha.x`.
So currently, in fact, Wapplyzer does not recognize sites created with Docusaurus v2. But without breaking the recognization of sites on Docusaurus v1 (just `Docusaurus` without specifying version).
This PR is trying to fix it.
сс @AliasIO
> Update generator regex for Docusaurus

- src/technologies.json
Desc:
> Microsoft Advertising (formerly Bing Ads, Microsoft adCenter and MSN adCenter) is a service that provides pay per click advertising on both the Bing and Yahoo! search engines. 
Website:
https://about.ads.microsoft.com/en-us
Eample websites:
https://www.etsy.com/
https://www.rainbowshops.com/my-bag
https://www.shopwudn.com/
https://www.spilsbury.com/
https://www.foxbusiness.com/
> Add Microsoft Ads / Advertising, Analytics

- src/technologies.json
Remove false positive from Oracle Commerce. The dyncharset is too vague and promotes false positives. This should be detected as a URL parameter rather than a string on the page, so instead we'll remove it for now.
fixes #3667
> Fix Oracle Commerce

- src/technologies.json
Acquia Cloud never changed their name, and their name is part of the product (like Google Analytics isn’t called just Analytics).
> Update Acquia Cloud

- src/drivers/webextension/js/driver.js
While there are many MIME types that could be detected, `text/plain` should likely be added as it's a common response type from web servers, whether it's a raw file or API response.
fixes #2971
> Add plain/text detection

- bin/convert.js
- package.json
After running multiple builds lately for testing, the build time was taking an atrocious amount of time to run. Seeing that the bulk of the build was relying on the SVG conversion shell commands, I thought I would attempt to convert that to a Node script that was a little more efficient. Based on the timings below, we're seeing roughly a 95% decrease in build time, going from over 5 minutes to just under 14 seconds.
**Before**
```
yarn build  50.41s user 15.09s system 20% cpu 5:23.98 total
```
**After**
```
yarn build  7.99s user 2.18s system 73% cpu 13.818 total
```
- Convert bash script to Node script
- If PNG, copy over as-is, don't check
- Loop through SVGs and check if the converted file exists
- Check if SVG source file has recently changed. If it has, then convert it, else just …
> Optimizing SVG conversion build time

- src/technologies.json
Twitter Ads :
https://shop.fender.com/
https://grizly.com/
https://www.pewresearch.org/
https://discoveratlanta.com/
Twitter Analytics :
https://shop.fender.com/
https://grizly.com/
https://www.pewresearch.org/
**It seems that everything is correctly indicated in the analytics, I cannot find the reason why the technology cannot be determined** 
Also deleted from Twitter widget
` "js": {
"twttr": ""
},` 
this part code , i think its more related with Twitter Ads
> Add Twitter Ads,Analytics, Update twitter widget

- src/technologies.json
[The correct name is "iubenda" (with lower case "i"), not "Iubenda"](https://www.iubenda.com/en/help/158-imprintimpressum-2)
> Change "Iubenda" to "iubenda"

- src/technologies.json
It's very common for websites using Sanity as a backend to run queries against the API using XHR/fetch. This PR adds support for detecting these requests, in the case where the site doesn't use any file/image assets.
API calls are either sent to `<projectId>.api.sanity.io` or `<projectId>.apicdn.sanity.io`. In some cases, reverse proxies are put in front of the APIs for more fine-grained cache control, in which case checking the response for `x-sanity-shard` usually detects it as being from Sanity, except if stripped in the reverse proxy.
> Detect XHR request against Sanity API

- src/technologies.json
Hi,
I have added some rules to detect HTTP authentication methods based on the `WWW-Authenticate` header. The methods added are:
- Basic
- Digest
- SPNEGO (Negotiate)
- NTLM
- Kerberos
Here are some examples of webs with those methods:
- https://www.raccordement-cigeo.fr/
- https://mail.gocdt.com/
- https://portal.firmade.it/
- https://devel.inexio.net/
> Add rules to detect HTTP authentication

- src/technologies.json
The technology has been added previously, but the detection doesn't work well on Landing Pages.
> Improve Detection on Landing Pages created with Uscreen

- src/technologies.json
Some sites filter out the "optimized with" comment, adding the `script` tag recognition will improve detection.
Since Yoast SEO also exists for other platforms, the "implies WordPress" bit isn't true.
> Improve Yoast SEO detection

- src/technologies.json
Updated previously added technologies .Specifically added:
```
dom
descriptions
xhr
```
By the parameter `html ` extensions and locally, I did not seem to define them earlier.
Examples:
https://pinchofyum.com/
https://lilluna.com/
> Update AppNexus,OpenX,Rubicon Project

- src/technologies.json
Ghost calls itself a publishing platform, so calling it just a blog is not really correct.
> Ghost is a CMS

- src/technologies.json
The previous "scripts"-regexes (present until v6.6.0) were removed and replaced with "jquery". For me the version detection has declined due to this change. May I ask, what is the reason behind this? If I have missed something, sorry for bothering and feel free to close this proposed change. 
Thanks in advance
> insert back removed jquery regexes

- src/technologies.json
**Google Ads Conversion Tracking**
website : https://support.google.com/google-ads/answer/1722022
examples: 
https://artsyabode.com/
https://www.lightinthebox.com/
https://www.runescape.com/
**Google Call Conversion Tracking**
website : https://support.google.com/google-ads/answer/6100664
examples:
https://www.sentara.com/
https://www.stairsupplies.com/
https://www.inventables.com/
**Google Remarketing Tag** 
website: https://support.google.com/google-ads/answer/2476688
examples:
https://www.lightinthebox.com/ru/
https://www.upworthy.com/
https://www.rvtrader.com/
> Add Google Ads/Call Conversion Tracking / analytics

- src/technologies.json
Changing Duda's version hint from `"version"` - which is currently too generic
> Change Duda's version hint

- src/technologies.json
We've been using Builder and Builder.io interchangeably in our online communications, we'd like to move to just using `Builder.io` , thank you
> Change Builder to Builder.io

- src/technologies.json
See discussion here: https://github.com/HTTPArchive/almanac.httparchive.org/issues/2292
Before: JS variable and request mentioned were always available for HubSpot Analytics tech.
Now: querying for the actual node of the banner.
> Fixed the identification for Hubspot consent functionality

- src/drivers/webextension/_locales/ca/messages.json
- src/drivers/webextension/_locales/de/messages.json
- src/drivers/webextension/_locales/el/messages.json
- src/drivers/webextension/_locales/en/messages.json
- src/drivers/webextension/_locales/es/messages.json
- src/drivers/webextension/_locales/fa/messages.json
- src/drivers/webextension/_locales/fr/messages.json
- src/drivers/webextension/_locales/gl_ES/messages.json
- src/drivers/webextension/_locales/gr/messages.json
- src/drivers/webextension/_locales/id/messages.json
- src/drivers/webextension/_locales/it/messages.json
- src/drivers/webextension/_locales/ja/messages.json
- src/drivers/webextension/_locales/ko/messages.json
- src/drivers/webextension/_locales/nl/messages.json
- src/drivers/webextension/_locales/pl/messages.json
- src/drivers/webextension/_locales/pt/messages.json
- src/drivers/webextension/_locales/pt_BR/messages.json
- src/drivers/webextension/_locales/ro/messages.json
- src/drivers/webextension/_locales/ru/messages.json
- src/drivers/webextension/_locales/sk/messages.json
- src/drivers/webextension/_locales/tr/messages.json
- src/drivers/webextension/_locales/uk/messages.json
- src/drivers/webextension/_locales/uz/messages.json
- src/drivers/webextension/_locales/zh_CN/messages.json
- src/drivers/webextension/_locales/zh_TW/messages.json
- src/technologies.json
Updated for following -
- Fixed for 'Salesforce commerce cloud' false positives (https://github.com/AliasIO/wappalyzer/issues/4090)
- Improved detected for 'Orckestra' (https://github.com/AliasIO/wappalyzer/issues/4362) and 'Borderfree' (https://github.com/AliasIO/wappalyzer/issues/4356)
> Fixed 'Salesforce commerce cloud'  / 'Orckestra' / 'Borderfree' / Added 'Reviews' and 'Translation' categories

- src/technologies.json
In #4421 was added `core-js` detection, but it misses the most of cases.
The global `core` variable was available to `core-js@2` in *some* cases.
The global `__core-js_shared__` property is available in modern versions in *most* cases.
The `.version` and `.versions` properties are available only in modern versions.
`window['__core-js_shared__'].versions` contains information about all loaded `core-js` versions and modes, but I have no ideas how to handle it with your regex syntax.
My detection script https://github.com/zloirock/core-js/blob/5ddafd1/scripts/usage.mjs
Top 1000 results https://gist.github.com/zloirock/7331cec2a1ba74feae09e64584ec5d0e
Top 10000 results https://gist.github.com/zloirock/1fae0b9798b50d3551432ebf100216b9
> Fix `core-js` detection

- src/technologies/m.json
The brackets used in the regex for MaxMind were wrong: they would match the _characters_ from the words `device`/`js`, not the full word.
> Fix regex brackets for MaxMind

- src/technologies/d.json
Fixing a false positive in the Drupal multisite detection (all D7 sites use sites/all path, marked for exclusion).
> Fix Drupal Multisite (false positive)

- src/technologies/p.json
The detection added in #4056 was looking for [preact-helmet](https://www.npmjs.com/package/preact-helmet), a very specific library that is not a proxy for Preact usage.
> Implement actual Preact detection

- src/technologies/p.json
File p.json contains invalid json (trailing comma).
> Invalid json in technology file (p.json)

- src/technologies/j.json
Per: https://www.wappalyzer.com/docs/dev/specification/#version-syntax the semi-colons should be escaped.
> Fix jquery patterns' version specifier

- src/technologies/v.json
Vercel also uses the `server: Vercel` header.
Check it via: `curl -sI https://vercel.com/ | grep server:`
> feat: update vercel server header

- src/technologies/v.json
Vercel was previously under the "web server" category, but they are actually a Platform that runs Next.js servers.
> Fix Vercel category

- src/technologies/g.json
https://github.com/godaddy-wordpress/primer-child-escapade
http://troysskishop.com/
http://liveurlinkc.com/
http://idaff.com/
https://www.solostroup.com/wp/
> Add GoDaddy Escapade / WordPress theme

- src/technologies/h.json
https://www.huberway.com/analytics-software
https://www.foodclub.it/
https://svapohub.com/
https://tammarometalli.com/home
> Add Huberway Analytics / analytics

- package.json
#5024
Updated jsonlint -qV ./src/technologies/*.json to jsonlint -qV ./src/technologies/
According to https://github.com/prantlf/jsonlint#readme that is all that is needed to check all json files within a directory. This takes care of the warning. I tested it out by messing up a few json files and it is working as expected. Please review and merge.
> updated the jsonlint command

- src/technologies/d.json
Dart can be used (on the web) on its own without AngularDart.
Links:
- https://dart.dev/guides/libraries#web-platform-libraries
- https://vuedart.dev/
- https://workiva.github.io/over_react/
- https://vite-plugin-dart.vercel.app/
- https://flutter.dev/web
Additionally, AngularDart is slowly dying (at least community wise) due to Flutter supporting web.
- https://github.com/angulardart/angular/pulse
- https://www.reddit.com/r/dartlang/comments/djm4ix/what_is_the_current_state_of_angulardart/f47s39v/ (comment made on Oct 2018)
> Dart shouldn't imply AngularDart

- src/drivers/webextension/images/icons/Jetpack.svg
- src/technologies/j.json
https://jetpack.com/
https://www.caasimada.net/
https://www.hardware.com.br/
https://boardingarea.com/
http://1000mg.jp/
https://www.americaspace.com/
https://appmedia.jp/
https://www.rvcj.com/
https://paultan.org/
https://joinhandshake.com/
> Add Jetpack / WP plugin

- src/technologies/y.json
https://yoast.com/wordpress/plugins/duplicate-post/
https://xg4ken.com/
https://www.kurashijouzu.jp/
https://www.aircargoweek.com/
https://systemrapid.com/
http://www.ostaulkomailta.com/blog/
http://milkbar-creative.com/
https://mycrowd.com/
http://www.waiwaithailand.com/
> Add Yoast Duplicate Post / WP plugin

- src/technologies/v.json
Meta tag: `<meta name="generator" content="VuePress 2.0.0-beta.27">`
Example
- https://v2.vuepress.vuejs.org/
> Allow for beta version of VuePress

- src/technologies/c.json
Cart functionality is too important to be missed.
"shopping-bag/basket/cart" frequently appears in various tags, so use it.
Example: https://www.bike24.de
> Update cart functionality

- src/technologies/m.json
https://mailchimp.com/integrations/woocommerce
https://shubb.com/
https://shop.amlul.com/
https://mattk.com/
https://technode.com/
https://www.justineclenquet.com/
> Add MailChimp for WooCommerce / WP plugin

- src/technologies/s.json
https://siteorigin.com/widgets-bundle/
https://makebeliefscomix.com/
https://www.sch.gr/
https://www.healthstatus.com/
https://emicalculator.net/
https://www.bigteams.com/
https://www.rmutp.ac.th/
> Add SiteOrigin Widgets Bundle / WP plugin

- src/technologies/a.json
https://amp-wp.org
http://www.elgrannegocio.com/
https://www.pinstripedprospects.com/
https://www.freeweed.it/
https://www.jetsonhacks.com/
https://biserok.org/
http://hadooptutorial.info/
> Add AMP for WordPress / WP plugin

- src/technologies/g.json
https://github.com/godaddy-wordpress/coblocks
https://www.utdallas.edu/
https://edublogs.org/
https://www.prontonetworks.com/
https://www.optimalworkshop.com/
https://mh.gob.sv/
https://mh.gob.sv/
https://www.galileo.edu/
https://digitalrev.com/
https://enviragallery.com/
https://norml.org/
> Add GoDaddy CoBlocks / WP plugin, page builder

- src/technologies/p.json
previously: `link[*='/wp-content/themes/hueman/']`
Now: `link[href*='/wp-content/themes/hueman/']`
When I was processing this pattern in another place, I was gettting this error:
> Fix Invalid CSS selector pattern

- src/technologies/g.json
Detect Google Sites that have a custom domain
http://sites.google.com
https://toolkit.openbriefing.org/
https://ecosystem.openbriefing.org/about
https://sites.google.com/view/simpleanalytics-test-site/home
```js
document.querySelector('[data-abuse-proto*="https://sites.google.com/"]')
```
> Update Google Sites / CMS

- src/technologies/s.json
Adding some fields to Squarespace Commerce that were previously assumed to be inherited from Squarespace.
> Duplicate Squarespace template version tagging for "Squarespace Commerce" websites

- src/technologies/c.json
https://wordpress.org/plugins/wp-gdpr-compliance/
https://cookieinformation.com/
https://wpbakery.com/
https://iupac.org/
https://www.americaspace.com/
https://vilmanunez.com/
https://katohika.gr/
https://www.compact-online.de/
> Add Cookie Information plugin / WP plugin, Cookie compliance

- src/technologies/s.json
removing implies from stitches because it works with any js/ts framework
> fix: removing implies for stitches

- src/technologies/c.json
https://catchthemes.com/themes/fotografie/
https://www.blackpast.org/
http://www.posinwang.com/
http://www.the-photography-blogger.com/
http://topgymfitness.pl/
https://lequebecunehistoiredefamille.com/
http://chomeur.net/
http://www.lagomera.com.pl/
> Add Catch Themes Fotografie / WP themes

- src/technologies/t.json
https://themefreesia.com/themes/Photograph/
https://film-grab.com/
http://www.cookiecoffee.com/
https://nativegrillandwings.com/
https://ulfelderphoto.com/
https://weddinglovequotes.com/
https://mystudio.gr/
> Add Theme Freesia Photograph / WP themes

- src/technologies/w.json
https://wenthemes.com/item/wordpress-themes/signify-dark/
http://www.wfku.org/
https://www.nosvoyants.com/
https://ecc-expo.com/
http://espikvlt.com/
http://julianassange.com/
https://www.crimeculture.com/
> Add WEN Themes Signify Dark / WP themes

- src/technologies/w.json
This adds a way to detect Wagtail sites based on rich text content – Wagtail uses the `data-block-key` attribute so each block has a unique identifier:
```html
<li data-block-key="3so1f">This is a list item in rich text</li>
```
I’ve implemented the detection pattern I’m proposing here by testing it on homepages of [a directory of 600+ Wagtail sites](https://madewithwagtail.org/), and of the [Majestic Million](https://majestic.com/reports/majestic-million). I didn’t find any false positives – a few non-Wagtail homepages do use the same attribute name, but not the same format for values.
Here is a sample of 10 Wagtail sites’ homepages where the previous detection methods didn’t find any matches, while the `data-block-key` check does:
```
billiger.de
edge.co.uk
gandi.net
heijmans.nl …
```
> Add detection for Wagtail’s rich text data-block-key attributes

- src/technologies/l.json
Layer0 sites include response headers in the form of `x-0-*` (https://docs.layer0.co/guides/response_headers) which also include the version of Layer0 used to deploy the site in the `x-0-version` header.
> update Layer0 definition to include response headers

- src/technologies/d.json
Multisite detection was failing on known multisites, expanded detection to other assets.
> Fix Drupal Multisite - Expand asset source detection

- README.md
"Go go" → "Go to"  
"WordpPress" → "WordPress"
> Fix a couple README typos

- src/technologies/e.json
The current `[\\S\\s.*]*` groups in ElasticSuite's second html regex match the entire html document (all non-whitespace, whitespace, literal . and *) and basically full text search Smile_Elasticsuite on the entire page. I don't think that was intended, since the pattern is surrounded by < >. Instead, I extended the first pattern from just input tags to all html tags.
> Change ElasticSuite regex

- .github/workflows/submit.yaml
- .gitignore
Hi @AliasIO,
Thanks for making wappalyzer - this extension is awesome! I was looking for some way to contribute, and thought that maybe an automated submission pipeline for the zip archive could be helpful. The github action in this PR is made to be run manually from the github action tab. The only thing you would need to create is a `SUBMIT_KEYS` github repository secret. 
This secret is a json, with the schema defined [here](https://github.com/plasmo-corp/bpp/blob/main/keys.schema.json).
Here's a sample key:
```json
{
"$schema": "https://raw.githubusercontent.com/plasmo-corp/bpp/main/keys.schema.json",
"chrome": {
"clientId": "123",
"refreshToken": "789",
"extId": "abcd"
},
"firefox": {
"extId": "123",
"apiKey": "abcd",
"apiSecret": "efgh"
}
}
```
You can find instructions on how to get …
> Creating submit github action

- bin/validate.js
- src/drivers/webextension/images/icons/Framer Sites.svg
- src/technologies/f.json
https://www.framer.com/sites
Also fixed a typo in `bin/validate.js`, where the template literal in the extraneous file error had an extra `}` character at the end.
> Add Framer Sites / Page Builder

- src/technologies/f.json
- `dom` rule replaces `html` rule that inadvertently expected discriminating class name to appear last in the class list
- Version detection for Froala 2+
- Additional discriminating class for popup editors (existing code doesn't recognize Froala on [these](https://froala.com/wysiwyg-editor/examples/edit-in-popup/) official [demos](https://froala.com/wysiwyg-editor/examples/init-on-button/))
- Additional discriminating class for Froala 1.x
> Improve Froala detection

- src/drivers/webextension/images/icons/Connectif.svg
- src/technologies/c.json
https://connectif.ai/
https://hispanoracing.com/
https://kavehome.com/es/es/
https://www.balearia.com/es
https://www.pccomponentes.com/
> Add Connectif / personalisation, marketing-auto

- src/technologies/p.json
Hey @AliasIO , 
I see traces of js objects on this site.
1 . **Locally**, I should have seen at least a positive result with 50% confidence (this is a bug that was identified before), but i see positive result with 25% confidence
priceDisplayMethod
priceDisplayPrecision
2. The  **Chrome extension** doesn't show anything at all.
Added dom, everything seems to be working now.
The bugs above, I assume, are not only related to this technology.
example:
https://www.lepetitvapoteur.com/fr/#
> Update PrestaShop / ecommerce

- src/technologies/c.json
cdnjs is a (FOSS) [content delivery network](https://en.wikipedia.org/wiki/Content_delivery_network) (CDN) hosted by [Cloudflare]
> Update cdnjs , cloudflare / cdn

- src/technologies/t.json
https://www.urbandictionary.com/
https://glosbe.com/
https://group.jumia.com/
https://targetjobs.co.uk/
https://www.modanisa.com/en/
https://onedio.com/
> Update Tailwind CSS / ui framework

- src/technologies/e.json
- src/technologies/p.json
https://yaroslavhrabovets.in.ua/
https://ibertronica.es/
https://www.domena.cz/
Hey @AliasIO , my knowledge is not enough for web servers. I have a question
In all these examples there is such a trace
`x-powered-by: Express, Phusion Passenger(R) 6.0.12`
Express **implies** Node.js , 
Can there be multiple web servers on one site?
Apache,
Express,
Node.js.
Phusion Passenger
or 
Ngnix,
Express,
Node.js.
Phusion Passenger
> Update Express, Phusion Passenger / web server

- src/drivers/webextension/images/icons/acquia-cloud-platform.svg
- src/technologies/a.json
- src/technologies/f.json
Acquia Cloud Platform CDN runs on Fastly, so this will add the new product, and update the Fastly detection that is more agnostic.
> Add Acquia Cloud Platform CDN / Update Fastly

- src/drivers/webextension/images/icons/Ordersify.svg
- src/technologies/o.json
https://ordersify.com/products/product-alerts
https://apps.shopify.com/ordersify-product-alerts
https://scrawlrbox.uk/
https://www.vpa.com.au/
https://www.dollyanddotty.co.uk/
https://adnams.co.uk/
https://www.teapigs.co.uk/
> Add Ordersify Product Alerts / shopify-apps #5830

- src/technologies/t.json
tachyons.io
https://www.infostore.com.br/
https://newsapi.org/
https://theleakycauldronblog.com/
https://theinnercircle.co/
So far, I have not added these options. There we can determine through the commented blog
/*! TACHYONS v4.11.1 | http://tachyons.io */
https://kek.gg/
https://thelightingoutlet.com.au/
https://digitalsignagepulse.com/
https://lof.se/
> Add Tachyons / ui framework

- src/technologies/m.json
Since ASP.NET and its related technologies like Blazor are no longer Windows and Internet Information Services exclusive, it would be incorrect to reference Windows Server and IIS at all.
> Update Microsoft ASP.NET / Web frameworks

- src/technologies/l.json
GitHub page: https://github.com/paulirish/lite-youtube-embed (4.2k stars)
Demo: https://paulirish.github.io/lite-youtube-embed/
**node src/drivers/npm/cli.js https://paulirish.github.io/lite-youtube-embed/**
```
{
"urls": {
"https://paulirish.github.io/lite-youtube-embed/": { "status": 200 }
},
"technologies": [
// ...
{
"slug": "lite-youtube-embed",
"name": "lite-youtube-embed",
"confidence": 100,
"version": null,
"icon": "YouTube.png",
"website": "https://github.com/paulirish/lite-youtube-embed",
"cpe": null,
"categories": [
{
"id": 59,
"slug": "javascript-libraries",
"name": "JavaScript libraries"
}
]
}
// ...
]
}
```
Sample pages (selected at random): 
- https://www.techbang.com/
- https://www.musicnotes.com/
- https://www.cgtrader.com/
- https://connectify.me/
- …
> Add lite-youtube-embed detection

- .github/workflows/submit.yml
Upgrades the Browser Plugin Publish Github action to v2. We also renamed our organization which is why that's different now!
The new version adds support for the Edge Web Store Add-Ons API and improved reliability.
⚠️ Heads up the schema's changed a bit ⚠️
Here's an updated representation: https://raw.githubusercontent.com/PlasmoHQ/bpp/v2/keys.schema.json
Here's an example: https://github.com/PlasmoHQ/bpp/blob/main/keys.template.json
> Upgrade bpp to v2

- src/drivers/npm/Dockerfile
Adding multiple files to a directory in docker requires a slash, if there is no slash then it cannot be copied to docker properly, this fix can build docker images properly
> Fix the problem that missing slash cannot be copied during docker build

- src/technologies/f.json
Discussion at #6028 had valid DOM rules to discriminate Froala 1.x from 2+ but I guess I forgot to get that merged
> Improve Froala 1.x detection

- src/technologies/w.json
There are a number of pages which use Webpack but are currently not identified correctly. The current check is on the `webpackJsonp` global variable, but in some cases Webpack uses `webpackChunk` instead, depending on the Webpack configuration.
GitHub page: https://github.com/webpack/webpack
**Example**
```
node src/drivers/npm/cli.js https://feedly.com/
```
**Before the fix:**
```
{
"urls": {
"https://feedly.com/": { "status": 200 }
},
"technologies": [
// ...
// no webpack
// ...
]
}
```
**After the fix:**
```
{
"urls": {
"https://feedly.com/": { "status": 200 }
},
"technologies": [
// ...
{
"slug": "webpack",
"name": "webpack",
"confidence": 100,
"version": null,
"icon": "webpack.svg",
"website": "https://webpack.js.org/",
"cpe": null,
"categories": [
{ "id": 19, "slug": …
```
> Improved reliability of webpack check

- src/technologies/f.json
examples:
- https://github.com/ (https://github.githubassets.com/assets/dark-d4a90c367f0c.css)
- https://stripe.com/ (https://b.stripecdn.com/mkt-statics-srv/assets/App-58f708b1.js)
> Add Fastly detection headers

- src/technologies/l.json
According to the ticket https://github.com/wappalyzer/wappalyzer/issues/5972, we are looking for script 'ls.unveilhooks.js' or 'ls.unveilhooks.min.js'.
It is just a small fix in the regex in order to escape the point "."
> Fix lazysize unveilhooks regex

- src/technologies/l.json
http://www.ezcommerce.com.br/ - >  redirect to  https://www.linx.com.br/
builtwith and similiartech says http://www.plataformacore.com.br/ but link unavailable 
https://www.casadacarabina.com.br/
https://www.boimsjeans.com.br/
https://www.superepi.com.br/
https://www.saojorge.com.br/
https://www.sieno.com.br/
https://www.souvie.com.br/
> Update Linx Commerce / ecommerce

- src/technologies/c.json
No more `html[style*='chakra-ui-color-mode']` dom from Chakra UI v2.
examples
- https://upstash.com/
- https://chakra-ui.com/
> Update Chakra UI dom Detection

- src/technologies/f.json
Framer Sites detection does not work properly.
examples
- https://basement.dev/
- https://www.capchase.design/
- https://www.exomon.xyz/
> Update Framer detection

- src/technologies/a.json
Adding more JS object detection, and updating category for CDP (was previously analytics). I also removed the Acquia Cloud implication, as customers who were using AgilOne before they were acquired, don't actually use the Acquia platform. There are other detections to independently identify that.
> Fix Acquia Customer Data Platform

- src/drivers/npm/cli.js
`--help` is an accepted option and should not return `1` (error) as exit code but success `0`. However, the CLI will still return `0` if help text is forced due to missing URL.
> Fix exiting with error code when help is called

- src/technologies/s.json
As of v1.3.2 the header is "X-Powered-By": "Dart with package:shelf"
Leaving previous value to allow detection of older versions
> Update shelf detection logic with latest header

- src/technologies/f.json
An x-served-by header starting with `cache-` could be anyone...
> fastly: drop overly general response header

- src/technologies/g.json
"Server": "Google Frontend" could be a number of other things, including
Google Cloud Run
> Google App Engine: fix website, lower confidence in header

- src/technologies/h.json
The [Alt-Svc](https://developer.mozilla.org/docs/Web/HTTP/Headers/Alt-Svc) header is used to check if the web server supports HTTP/3, I've added this check for HTTP/2 as well.
Unfortunately I couldn't find a suitable icon and the [badges](https://github.com/httpwg/wg-materials/tree/gh-pages/badge/http3) are too big.
> Add HTTP/3 detection

- src/technologies/m.json
Remove Django implication from mailman. Mailman is not necessarily used
with Django but always with Python. Also add missing CPE.
> Improve mailman CPE and implication

- src/technologies/d.json
https://www.oneeducation.co.uk/
https://drive.houtar.eu.org/
> Update DPLayer / video

- src/technologies/e.json
Product team requested that we simplify the name reported in Wappalyzer since "App Platform" is one distinct offering that Edgio provides, and isn't representative of the entire suite of tools.
> Simplify Edgio name

- src/technologies/e.json
This reverts part of #4520, where eSSENTIAL Accessibility’s description was changed so it is presented as an overlay. Whether a given site uses an overlay or not is very important, as there is [a lot of movement against overlays](https://overlayfactsheet.com/).
As far as I can tell [from their website](https://www.essentialaccessibility.com/), they don’t offer an overlay. They do have their logo featured on a lot of websites. Here is the (shortened) HTML from [piazza.com](https://piazza.com/). As far as I can tell, this is just a link with an image in it:
```html
<a href="https://www.essentialaccessibility.com/piazza" target="_blank">
</a>
```
They do offer a Windows / Mac / Android application ([see user manual](https://www.essentialaccessibility.com/user-manual/en/)), but as far as I …
> Revert description for eSSENTIAL Accessibility classifying it as overlay

- src/technologies/u.json
Right now USWDS is displayed amongst [Web frameworks](https://www.wappalyzer.com/technologies/web-frameworks). It’s a design system, with no server-side code, and even client-side it doesn’t help structure applications – it’s just an assortment of components. So I think it would be better to see it amongst [UI frameworks](https://www.wappalyzer.com/technologies/ui-frameworks), like Bootstrap, or other design systems.
> Recategorise USWDS from Web frameworks to UI frameworks

- .github/workflows/stale.yml
- .github/workflows/submit.yml
- .github/workflows/validate.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- src/technologies/i.json
- It's written Inertia.js, not Inertia like the logo
- Laravel or Ruby on Rails are implied by Inertia.js
- The confidence numbers come from the [Laravel](https://github.com/inertiajs/inertia-laravel/network/dependents) and [Rails](https://github.com/inertiajs/inertia-rails/network/dependents) repositories (16,438 vs 128 uses)
- It also implies React, Vue, or Svelte but I think those can be detected better other ways
> Added info for Inertia.js

- src/technologies/g.json
When using Google Fonts with the Next.js framework.
Next.js automatically optimizes the google font API, so wappalyzer cannot detect it.
(e.g. https://umami.is)
+ I'm not sure this line is correct.
`"<style data-href=\"https://fonts.googleapis.com/css*\""`
> Add Google Font API detection method

- src/technologies/b.json
*.b-cdn.net is the default domain for zones at bunnycdn
> feat: add bunnycdn default subdomain

- src/technologies/h.json
https://www.andrewdragon.dev/
.dev is a top-level domain name operated by Google.[1] It was proposed in ICANN's new generic top-level domain (gTLD) program, and became available to the general public on March 1, 2019, with an early access period that began on February 19.[2] To increase the security of the domains, the entire gTLD has been included in the HSTS preload-list; as a result, popular web browsers will only connect to a .dev webpage using HTTPS.[2]
> Update HSTS / security

- src/technologies/s.json
Moves to the `dom` method of selection.
Example sites
* https://www.environment.nsw.gov.au/
* https://www.vicroads.vic.gov.au/
> Update SiteCore detection.

- src/technologies/p.json
Escape `{` to allow the regular expression to be used as is in Java as well.
Also escape `.`, for consistency with the first CSS regular expression.
> Escape special regular expression characters

- src/technologies/s.json
If js object **Shopify**  comes first in the js array then confidence remains at 25% despite 100% matches and confidence in other keywords. Well, this is an old kind of problem with the summation of confidence.
I moved it to the end and confidence for some reason I don’t understand became 100% and now Shopify will show in extensions what one user complained about on the example of this site, because the extension does not show below 50% confidence if I don’t confuse anything
https://grovemade.com/product/black-pen-and-pen-stand/?initial=491
> Update Shopify / ecommerce

- src/technologies/t.json
This PR intends to add detection for the WordPress default themes Twenty Twenty-Two and Twenty Twenty-Three, which are currently missing from the list of WordPress default themes that Wappalyzer detects.
Before reviewing the code, please read the following concerns:
* Those two themes (as well as likely any WordPress default themes in the future) follow a new theme development paradigm which, while it has several benefits, makes it quite a bit harder to identify such a theme being used.
* Twenty Twenty-Two still comes with a stylesheet that identifies the theme, so this one is still relatively straightforward, however it already lacks all other criteria that Wappalyzer relies on to detect previous WordPress default themes. Twenty Twenty-Three however does not load any stylesheet that …
> Add detection for WordPress themes Twenty Twenty-Two and Twenty Twenty-Three

- src/technologies/i.json
https://clerk.dev/
This site uses Intercom but Wappalyzer cannot detect it because js loaded lazily.
> Add intercom dom detection

- src/technologies/b.json
Adds support for Google's [Business Website Builder](https://businesswebsites.google.com/welcome) CMS.
This is similar to the existing [Google My Business](https://github.com/wappalyzer/wappalyzer/blob/ee4d835aea6f1ab0432e07883b05dd6a9fd5200b/src/technologies/g.json#L1553-L1560) detection. The distinction is that that one matches subdomains of business.site while this one is business.page. They're separate CMSs.
Note that, unlike the other one, the name for this technology does not officially start with "Google". The full name is "Business Website Builder".
Some example URLs that use this technology:
- https://datang.business.page/
- https://foodadditive.business.page/
- https://times-marine.business.page/
- https://naturalorchid.business.page/
- https://icemachine.business.page/
> Business Website Builder

- src/technologies/w.json
https://wordpress.org/plugins/wp-visitors-widget/
https://zakatinst.net/ar/
https://www.hileytech.com/
https://radicalsoapbox.com/
https://maketbandung.com/
> Add WP Live Visitor Counter / wp-plugin, widget

- src/categories.json
Can we raise this category to the top?
Many people write that technology in this category is not defined. Apparently they expect to see him at the beginning
example:
https://msplaunchpaddemo.com/
> Update Page builders / priority

- src/drivers/webextension/images/icons/stackbit.svg
- src/technologies/s.json
Stackbit is a page builder tool to use in conjunction with headless CMSes and decoupled build services. Some examples of customers:
- https://www.takeda.com/
- https://www.abodu.com/
- https://vise.com/
- https://materialize.com/
- https://www.wellsterhealth.com/
- https://www.empathy.com/
This is a newer service that has been implemented with larger customers, but published case studies and companies are limited. Adding this detection would help identify other websites that are adopting this platform.
> Adding Stackbit

- src/technologies/g.json
https://docs.generatepress.com/article/installing-gp-premium/
https://generatepress.com/pricing/
https://www.spzan.com/
https://www.cartooncrazy.net/
https://www.newsit.gr/
https://attychew.com/
> Add GeneratePress GP Premium / wp-plugin

- src/drivers/webextension/images/icons/Waveme.svg
- src/technologies/w.json
http://music.flatfull.com/waveme/about/
https://www.unlocktheotherside.com/
https://realdeejays.com/
https://musicout.com/
https://anyinstrumental.com/
https://djokawa.com/
> Add Waveme / wp-theme, Waveform / widget

- src/technologies/p.json
If you check the `Phoenix` instance, or just watch the WebSocket connection - you will find that it's actually [Phoenix Framework](https://www.phoenixframework.org/), not [Sazito-Phoenix](https://github.com/Sazito/phoenix/). **I couldn't find any reference to global "Phoenix" in Sazito-Phoenix. (Sazito-Phoenix does not have it)**
<details>
<summary>Websocket connection from "Network" tab by "Phoenix Framework"</summary>
</details>
Here are the methods that "Phoenix" instance from "Phoenix Framework" has: https://github.com/phoenixframework/phoenix/blob/master/assets/js/phoenix/index.js#L201
All of them are present on the pages that were identified with Phoenix on [Wappalyzer website](https://www.wappalyzer.com/technologies/web-frameworks/phoenix/):
- `window.Phoenix.Channel`
- …
> Fix Phoenix and Phoenix Framework detection

- src/drivers/webextension/js/js.js
The change is about this condition:
```js
!(Object.getOwnPropertyDescriptor(value, method) || {}).get
```
It was first introduced in [this commit](https://github.com/wappalyzer/wappalyzer/commit/600e4f17495aa566330f0e1c2f49ca1c84240c0e#diff-6fc9ddd7a9f9994c94ccfb6a2b7c66cfa7303c7fef747f8e1d1f8a9a3d0e296b). But the problem is, it fails on some things. One such situation is when an object is a module. **In such module using getters is the intended behavior, and this condition ruins it.**
https://allegrolokalnie.pl/
`Phoenix.Channel`
**I think removing this `getOwnPropertyDescriptor` rule would drastically improve detectability on some technologies, as many technologies may have a situation similar to one with module.**
The existing check `Object.prototype.hasOwnProperty.call(value, method)` …
> Fix webextension `js` detection

- src/technologies/i.json
Oftentimes `Vary` header gets included on the first request without `X-Inertia` header, and therefore can greatly improve the detection.
- https://app.notionmailer.com/login
> Improve Inertia.js detection

- src/technologies/k.json
Not defined in this example. Also took versions
https://www.byredo.com/eu_fr/
> Update Klevu / search-engines

- src/technologies/n.json
Hello,
I have updated the CPE record for the Nginx web server. The previous CPE record in the NIST National Vulnerability Database referenced the previous version as `cpe:2.3:a:nginx:nginx:*:*:*:*:*:*:*:*`. However, Nginx is now supported by F5, so the CPE record has been updated to `cpe:2.3:a:f5:nginx:*:*:*:*:*:*:*:*`.
These changes ensure the accurate identification of Nginx versions developed or supported by F5 and help improve the accuracy of vulnerability reports.
Please review the changes and let me know if any additional modifications are required.
Thank you.
> Update Nginx CPE record

- src/technologies/v.json
Hi!
I spotted this typo for the varnish_cache CPE when trying to automatically look up CPEs found by Wappalyzer.
Thanks!
> Fixes varnich_cache -> varnish_cache typo in v.json technology file

- src/technologies/g.json
Many Origins are not classified as using "Google Publisher Tag" due to a buggy Google Publisher Tag Classification.
Default one: https://securepubads.g.doubleclick.net/tag/js/gpt.js
Limited Ads one: https://pagead2.googlesyndication.com/tag/js/gpt.js
Old: https://googletagservices.com/tag/js/gpt.js
> Update Google Publisher Tag Domains

- src/technologies/m.json
https://docs.mapbox.com/help/glossary/mapbox-js/
https://github.com/mapbox/mapbox.js
https://www.nuroa.com.ve/venta/casa-avenida-turmero?with_coords=1
https://www.colorline.no/
https://utcakereso.hu/
https://www.bca.fr/
https://www.ifsc.edu.br/
https://grains.org/
> Add Mapbox.js / maps

- src/technologies/a.json
Fixes #7677
AdOpt is not being detection on sites like https://allcomtelecom.com/
This updates the detection to look for scripts starting with `https://tag.goadopt.io/injector.js"`
It also adds `"implies": "Svelte",` as discussed in #7677
> Improve AdOpt detection

- src/technologies/j.json
Note: Only applies when the critical CSS feature is enabled, should the name change?
> Add Jetpack Boost

- src/technologies/c.json
CrownPeak is largely DXP centered around their web content platform product. This update will add the CMS category, which is already marked by the current detections, and simplify the description to keep standard with the current Wappalyzer technology descriptions.
> Update CrownPeak properties

- src/technologies/d.json
This PR improves the Drupal Multisite detection (builds upon the work in #7687) to detect images in multisite paths and not just script files.
> Improve Drupal Multisite detection

- src/technologies/w.json
This detection adds support for finding WordPress Multisite (WPMS) installations. WPMS has been used an implemented by organizations all over the world, from small nonprofits, universities, and large enterprise organizations. This extends the WordPress detection to those sites that are using the WPMS configuration. Some example sites:
- https://careers.nba.com
- https://www.leaderpub.com
- https://www.coyoteridgegolfclub.com
> Add WordPress Multisite

- src/technologies/a.json
https://www.codingthesmartway.com/
https://nquantum.net/index
> Update Astro / static-site-generator

- src/technologies/f.json
In the latest release of Front-Commerce (2.25) we worked on improving the loading performance, due to this change the link dom elements will no longer exist. 
This change keeps the `link` for previous versions and checks for an equivalent `script` for the latest version.
- [magento2.front-commerce.app](https://magento2.front-commerce.app/)
- [magento1.front-commerce.app](https://magento1.front-commerce.app/)
- [magento2-b2b.front-commerce.app](https://magento2-b2b.front-commerce.app/)
> fix(technologies): front-commerce dom elements

- src/technologies/s.json
Related: #7280 
From Astro 2.0, they have `window._$HY` for solid-js integration (even if it's not integrated)
so if the website uses Astro 2, `SolidStart` was falsely detected. 
(ref: https://github.com/withastro/astro/blob/main/packages/integrations/solid/src/client.ts#L8)
To fix this, I made js detection more strictly.
examples
Only Astro
- https://astro.build/
- https://robertonazareth.dev/
Only SolidStart
- https://start.solidjs.com/
- https://githubfk8exj-p0ad--3000--c53ab388.local-credentialless.webcontainer.io/
> Fix SolidStart falas detection

- src/technologies/c.json
https://www.vlr.gg/232732/cloud9-vs-sentinels-champions-tour-2023-americas-last-chance-qualifier-ubsf
https://adhemas.com/
As an option, I updated the regular expression. Would it be better to remove it completely? too broad a search, leave it up to you
> Update Cargo / page-builder

- src/technologies/w.json
https://woocommerce.com/products/woocommerce-subscriptions/
https://www.prontonetworks.com/
http://actualicese.com/
https://hyperallergic.com/membership/
https://craftbundles.com/
> Add WooCommerce Subscriptions / wp-plugin

- src/technologies/a.json
- src/technologies/o.json
- src/technologies/s.json
CPE Version 2.3 should consist of 13 parts (all the others do in Wappalyzer (around 270). There are three CPE strings that consist of 14 parts. This PR corrects them.
> Fix cpes that are too long

- src/technologies/w.json
https://wasm.continuation-labs.com/d3demo/
> Update WebAssembly / pl

- src/technologies/s.json
https://www.sitecore.com/products/sitecore-experience-platform
https://doc.sitecore.com/xp/en/developers/101/developer-tools/experience-edge-for-xm-apis.html
https://www.atkore.com/Resources
https://www.kennards.com.au/
https://www.kennardshire.co.nz/
Distinguished from the core cms Sitecore as I'm not sure what the platform is supposed to be
`"implies": "Microsoft ASP.NET",`
> Add Sitecore Experience Edge / caching,  Experience Platform / cms
